grpc_library(
    name = 'auth',
    srcs = ['auth.proto'],
    visibility = ['PUBLIC'],
    languages = [
        'go',
    ],
)

grpc_library(
    name = 'kitten',
    srcs = ['kitten.proto'],
    visibility = ['PUBLIC'],
    languages = [
        'go',
    ],
)