// Code generated by protoc-gen-go.
// source: protosrc/kitten.proto
// DO NOT EDIT!

/*
Package kitten is a generated protocol buffer package.

It is generated from these files:
	protosrc/kitten.proto

It has these top-level messages:
	Kitten
	GetKittenRequest
	GetKittenResponse
*/
package kitten

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Breed int32

const (
	Breed_HALP         Breed = 0
	Breed_PERSIAN      Breed = 1
	Breed_BENGAL       Breed = 2
	Breed_RUSSIAN_BLUE Breed = 3
	Breed_CORNISH_REX  Breed = 4
)

var Breed_name = map[int32]string{
	0: "HALP",
	1: "PERSIAN",
	2: "BENGAL",
	3: "RUSSIAN_BLUE",
	4: "CORNISH_REX",
}
var Breed_value = map[string]int32{
	"HALP":         0,
	"PERSIAN":      1,
	"BENGAL":       2,
	"RUSSIAN_BLUE": 3,
	"CORNISH_REX":  4,
}

func (x Breed) String() string {
	return proto.EnumName(Breed_name, int32(x))
}
func (Breed) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Kitten struct {
	Name   string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Breed  Breed   `protobuf:"varint,2,opt,name=breed,enum=Breed" json:"breed,omitempty"`
	Weight float32 `protobuf:"fixed32,3,opt,name=weight" json:"weight,omitempty"`
	Age    int32   `protobuf:"varint,4,opt,name=age" json:"age,omitempty"`
}

func (m *Kitten) Reset()                    { *m = Kitten{} }
func (m *Kitten) String() string            { return proto.CompactTextString(m) }
func (*Kitten) ProtoMessage()               {}
func (*Kitten) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetKittenRequest struct {
	// Breed of kitten requested. If not given then the server
	// may provide a kitten of any breed.
	Breed Breed `protobuf:"varint,1,opt,name=breed,enum=Breed" json:"breed,omitempty"`
}

func (m *GetKittenRequest) Reset()                    { *m = GetKittenRequest{} }
func (m *GetKittenRequest) String() string            { return proto.CompactTextString(m) }
func (*GetKittenRequest) ProtoMessage()               {}
func (*GetKittenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetKittenResponse struct {
	Kitten *Kitten `protobuf:"bytes,1,opt,name=kitten" json:"kitten,omitempty"`
}

func (m *GetKittenResponse) Reset()                    { *m = GetKittenResponse{} }
func (m *GetKittenResponse) String() string            { return proto.CompactTextString(m) }
func (*GetKittenResponse) ProtoMessage()               {}
func (*GetKittenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetKittenResponse) GetKitten() *Kitten {
	if m != nil {
		return m.Kitten
	}
	return nil
}

func init() {
	proto.RegisterType((*Kitten)(nil), "Kitten")
	proto.RegisterType((*GetKittenRequest)(nil), "GetKittenRequest")
	proto.RegisterType((*GetKittenResponse)(nil), "GetKittenResponse")
	proto.RegisterEnum("Breed", Breed_name, Breed_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for PetShop service

type PetShopClient interface {
	// Supplies one kitten to the caller.
	GetKitten(ctx context.Context, in *GetKittenRequest, opts ...grpc.CallOption) (*GetKittenResponse, error)
}

type petShopClient struct {
	cc *grpc.ClientConn
}

func NewPetShopClient(cc *grpc.ClientConn) PetShopClient {
	return &petShopClient{cc}
}

func (c *petShopClient) GetKitten(ctx context.Context, in *GetKittenRequest, opts ...grpc.CallOption) (*GetKittenResponse, error) {
	out := new(GetKittenResponse)
	err := grpc.Invoke(ctx, "/PetShop/GetKitten", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PetShop service

type PetShopServer interface {
	// Supplies one kitten to the caller.
	GetKitten(context.Context, *GetKittenRequest) (*GetKittenResponse, error)
}

func RegisterPetShopServer(s *grpc.Server, srv PetShopServer) {
	s.RegisterService(&_PetShop_serviceDesc, srv)
}

func _PetShop_GetKitten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKittenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetShopServer).GetKitten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PetShop/GetKitten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetShopServer).GetKitten(ctx, req.(*GetKittenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PetShop_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PetShop",
	HandlerType: (*PetShopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKitten",
			Handler:    _PetShop_GetKitten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("protosrc/kitten.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0xbf, 0x6d, 0xd3, 0xf4, 0xeb, 0x44, 0x74, 0x3b, 0xa0, 0x04, 0x11, 0x0c, 0x39, 0x05,
	0x0f, 0xab, 0x46, 0xaf, 0x1e, 0x1a, 0x09, 0x6d, 0xb1, 0xd6, 0xb0, 0xa1, 0xe0, 0xad, 0xa4, 0xed,
	0xd0, 0x14, 0xdb, 0x24, 0x36, 0x5b, 0xf4, 0xcf, 0x97, 0x6c, 0x8a, 0x8a, 0x7a, 0x9b, 0xdf, 0xec,
	0xbe, 0xb7, 0x6f, 0x79, 0x70, 0x5c, 0x6c, 0x73, 0x95, 0x97, 0xdb, 0xf9, 0xe5, 0xcb, 0x4a, 0x29,
	0xca, 0x84, 0x66, 0x77, 0x01, 0xe6, 0x83, 0x66, 0x44, 0x30, 0xb2, 0x64, 0x43, 0x36, 0x73, 0x98,
	0xd7, 0x91, 0x7a, 0xc6, 0x33, 0x68, 0xcd, 0xb6, 0x44, 0x0b, 0xbb, 0xe1, 0x30, 0xef, 0xd0, 0x37,
	0x45, 0x50, 0x91, 0xac, 0x97, 0x78, 0x02, 0xe6, 0x1b, 0xad, 0x96, 0xa9, 0xb2, 0x9b, 0x0e, 0xf3,
	0x1a, 0x72, 0x4f, 0xc8, 0xa1, 0x99, 0x2c, 0xc9, 0x36, 0x1c, 0xe6, 0xb5, 0x64, 0x35, 0xba, 0x57,
	0xc0, 0xfb, 0xa4, 0xea, 0x87, 0x24, 0xbd, 0xee, 0xa8, 0x54, 0x5f, 0xde, 0xec, 0x0f, 0x6f, 0xf7,
	0x16, 0xba, 0xdf, 0x14, 0x65, 0x91, 0x67, 0x25, 0xe1, 0x39, 0x98, 0x75, 0x78, 0xad, 0xb1, 0xfc,
	0xb6, 0xd8, 0x5f, 0xd8, 0xaf, 0x2f, 0x1e, 0xa1, 0xa5, 0x5d, 0xf0, 0x3f, 0x18, 0x83, 0xde, 0x28,
	0xe2, 0xff, 0xd0, 0x82, 0x76, 0x14, 0xca, 0x78, 0xd8, 0x1b, 0x73, 0x86, 0x00, 0x66, 0x10, 0x8e,
	0xfb, 0xbd, 0x11, 0x6f, 0x20, 0x87, 0x03, 0x39, 0x89, 0xab, 0x83, 0x69, 0x30, 0x9a, 0x84, 0xbc,
	0x89, 0x47, 0x60, 0xdd, 0x3f, 0xc9, 0xf1, 0x30, 0x1e, 0x4c, 0x65, 0xf8, 0xcc, 0x0d, 0xff, 0x0e,
	0xda, 0x11, 0xa9, 0x38, 0xcd, 0x0b, 0xf4, 0xa1, 0xf3, 0x99, 0x07, 0xbb, 0xe2, 0xe7, 0x6f, 0x4e,
	0x51, 0xfc, 0x8a, 0x1b, 0x5c, 0x83, 0x9b, 0x91, 0x12, 0x2a, 0xcd, 0x77, 0xcb, 0x54, 0x6d, 0x92,
	0x79, 0xba, 0xca, 0x48, 0x14, 0x6b, 0x4a, 0x4a, 0x12, 0xf4, 0x9e, 0x6c, 0x8a, 0x35, 0x95, 0x81,
	0x55, 0xab, 0xa2, 0xaa, 0x8e, 0x99, 0xa9, 0x5b, 0xb9, 0xf9, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb5,
	0x8f, 0xae, 0xe8, 0xae, 0x01, 0x00, 0x00,
}
