// Code generated by protoc-gen-go.
// source: data_gym.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of AssetDigestEntry from data.proto

// Ignoring public import of BackgroundToken from data.proto

// Ignoring public import of BuddyPokemon from data.proto

// Ignoring public import of ClientVersion from data.proto

// Ignoring public import of DownloadUrlEntry from data.proto

// Ignoring public import of PlayerBadge from data.proto

// Ignoring public import of PlayerData from data.proto

// Ignoring public import of PokedexEntry from data.proto

// Ignoring public import of PokemonData from data.proto

// Ignoring public import of PokemonDisplay from data.proto

// Ignoring public import of RedeemPasscodeReward from data.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of PlayerAvatarType from data_player.proto

// Ignoring public import of FortData from map_fort.proto

// Ignoring public import of FortLureInfo from map_fort.proto

// Ignoring public import of FortModifier from map_fort.proto

// Ignoring public import of FortSummary from map_fort.proto

// Ignoring public import of FortRenderingType from map_fort.proto

// Ignoring public import of FortSponsor from map_fort.proto

// Ignoring public import of FortType from map_fort.proto

type GymMembership struct {
	PokemonData          *PokemonData         `protobuf:"bytes,1,opt,name=pokemon_data,json=pokemonData" json:"pokemon_data,omitempty"`
	TrainerPublicProfile *PlayerPublicProfile `protobuf:"bytes,2,opt,name=trainer_public_profile,json=trainerPublicProfile" json:"trainer_public_profile,omitempty"`
	TrainingPokemon      *PokemonData         `protobuf:"bytes,3,opt,name=training_pokemon,json=trainingPokemon" json:"training_pokemon,omitempty"`
}

func (m *GymMembership) Reset()                    { *m = GymMembership{} }
func (m *GymMembership) String() string            { return proto.CompactTextString(m) }
func (*GymMembership) ProtoMessage()               {}
func (*GymMembership) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *GymMembership) GetPokemonData() *PokemonData {
	if m != nil {
		return m.PokemonData
	}
	return nil
}

func (m *GymMembership) GetTrainerPublicProfile() *PlayerPublicProfile {
	if m != nil {
		return m.TrainerPublicProfile
	}
	return nil
}

func (m *GymMembership) GetTrainingPokemon() *PokemonData {
	if m != nil {
		return m.TrainingPokemon
	}
	return nil
}

type GymState struct {
	FortData      *FortData        `protobuf:"bytes,1,opt,name=fort_data,json=fortData" json:"fort_data,omitempty"`
	Memberships   []*GymMembership `protobuf:"bytes,2,rep,name=memberships" json:"memberships,omitempty"`
	DeployLockout bool             `protobuf:"varint,3,opt,name=deploy_lockout,json=deployLockout" json:"deploy_lockout,omitempty"`
}

func (m *GymState) Reset()                    { *m = GymState{} }
func (m *GymState) String() string            { return proto.CompactTextString(m) }
func (*GymState) ProtoMessage()               {}
func (*GymState) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *GymState) GetFortData() *FortData {
	if m != nil {
		return m.FortData
	}
	return nil
}

func (m *GymState) GetMemberships() []*GymMembership {
	if m != nil {
		return m.Memberships
	}
	return nil
}

func (m *GymState) GetDeployLockout() bool {
	if m != nil {
		return m.DeployLockout
	}
	return false
}

func init() {
	proto.RegisterType((*GymMembership)(nil), "SUNProtos.Data.Gym.GymMembership")
	proto.RegisterType((*GymState)(nil), "SUNProtos.Data.Gym.GymState")
}

func init() { proto.RegisterFile("data_gym.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x25, 0xad, 0x84, 0x82, 0x43, 0x0b, 0x58, 0x08, 0x45, 0x85, 0xa1, 0x54, 0x42, 0xaa, 0x18,
	0x3c, 0x94, 0x89, 0x85, 0x01, 0x50, 0xb3, 0x50, 0x64, 0xa5, 0x62, 0x61, 0x31, 0x4e, 0xeb, 0x94,
	0xa8, 0x71, 0x6c, 0x39, 0xee, 0xe0, 0xcf, 0xe2, 0xf3, 0xd8, 0x90, 0xed, 0x00, 0x29, 0x1d, 0x58,
	0x92, 0xbb, 0xe7, 0x7b, 0xef, 0xee, 0xde, 0x81, 0xfe, 0x92, 0x6a, 0x4a, 0x56, 0x86, 0x23, 0xa9,
	0x84, 0x16, 0x10, 0xce, 0x5f, 0x9e, 0xb1, 0x8d, 0x6a, 0xf4, 0x48, 0x35, 0x45, 0x89, 0xe1, 0x03,
	0x60, 0x6b, 0xfc, 0xfb, 0xe0, 0xc4, 0xd5, 0xcb, 0x92, 0x1a, 0xa6, 0x1a, 0xa8, 0xcf, 0xa9, 0x24,
	0xb9, 0x50, 0xda, 0xe7, 0xa3, 0xcf, 0x00, 0xf4, 0x12, 0xc3, 0x67, 0x8c, 0x67, 0x4c, 0xd5, 0xef,
	0x85, 0x84, 0x77, 0xe0, 0x50, 0x8a, 0x35, 0xe3, 0xa2, 0x22, 0x96, 0x1e, 0x07, 0xc3, 0x60, 0x1c,
	0x4d, 0xce, 0xd1, 0x9f, 0x5e, 0xd8, 0xd7, 0xd8, 0x38, 0x8d, 0xe4, 0x6f, 0x02, 0xdf, 0xc0, 0x99,
	0x56, 0xb4, 0xa8, 0x98, 0x22, 0x72, 0x93, 0x95, 0xc5, 0x82, 0x48, 0x25, 0xf2, 0xa2, 0x64, 0x71,
	0xc7, 0x29, 0x5d, 0xef, 0x28, 0xf9, 0xf9, 0xfc, 0x0f, 0x3b, 0x0a, 0xf6, 0x8c, 0xf4, 0xb4, 0x51,
	0xda, 0x42, 0xe1, 0x14, 0x1c, 0x3b, 0xbc, 0xa8, 0x56, 0xa4, 0xe9, 0x1c, 0x77, 0xff, 0x9f, 0xf2,
	0xe8, 0x9b, 0xd4, 0x80, 0xa3, 0x8f, 0x00, 0x84, 0x89, 0xe1, 0x73, 0x4d, 0x35, 0x83, 0xb7, 0xe0,
	0xc0, 0xda, 0xd2, 0xde, 0xf9, 0xa2, 0xa5, 0x36, 0xa3, 0x12, 0x4d, 0xad, 0x6d, 0xf6, 0xe3, 0xe4,
	0xc2, 0xbc, 0x89, 0xe0, 0x03, 0x88, 0xf8, 0x8f, 0x7f, 0x75, 0xdc, 0x19, 0x76, 0xc7, 0xd1, 0xe4,
	0x12, 0xed, 0x1e, 0x07, 0x6d, 0x39, 0x9d, 0xb6, 0x59, 0xf0, 0x0a, 0xf4, 0x97, 0x4c, 0x96, 0xc2,
	0x90, 0x52, 0x2c, 0xd6, 0x62, 0xa3, 0xdd, 0x4a, 0x61, 0xda, 0xf3, 0xe8, 0x93, 0x07, 0xef, 0xc3,
	0xd7, 0x7d, 0x77, 0xb8, 0x1a, 0xef, 0xe1, 0x00, 0x77, 0x32, 0x9f, 0xdd, 0x7c, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x90, 0xb2, 0x90, 0x6a, 0x1b, 0x02, 0x00, 0x00,
}
