// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	data.proto
	data_avatar.proto
	data_badge.proto
	data_battle.proto
	data_capture.proto
	data_gym.proto
	data_logs.proto
	data_player.proto
	data_quests.proto
	data_redeem.proto
	enums.proto
	inventory.proto
	inventory_item.proto
	map_fort.proto
	map_pokemon.proto
	maps.proto
	networking_envelopes.proto
	networking_platform.proto
	networking_platform_requests.proto
	networking_platform_responses.proto
	networking_requests.proto
	networking_requests_messages.proto
	networking_responses.proto
	service.proto
	settings.proto
	settings_master.proto
	settings_master_item.proto
	settings_master_pokemon.proto
	settings_master_quest.proto

It has these top-level messages:
	AssetDigestEntry
	BackgroundToken
	BuddyPokemon
	ClientVersion
	DownloadUrlEntry
	PlayerBadge
	PlayerData
	PokedexEntry
	PokemonData
	PokemonDisplay
	RedeemPasscodeReward
	AvatarCustomization
	AvatarItem
	BadgeCaptureReward
	BattleAction
	BattleLog
	BattleParticipant
	BattlePokemonInfo
	BattleResults
	CaptureAward
	CaptureProbability
	GymMembership
	GymState
	ActionLogEntry
	BuddyPokemonLogEntry
	CatchPokemonLogEntry
	FortSearchLogEntry
	ContactSettings
	Currency
	DailyBonus
	EquippedBadge
	PlayerAvatar
	PlayerCamera
	PlayerCurrency
	PlayerPublicProfile
	PlayerStats
	DailyQuest
	Quest
	PokeCandy
	RedeemedAvatarItem
	RedeemedItem
	AppliedItem
	AppliedItems
	Candy
	EggIncubator
	EggIncubators
	InventoryDelta
	InventoryItem
	InventoryItemData
	InventoryKey
	InventoryUpgrade
	InventoryUpgrades
	ItemAward
	ItemData
	FortData
	FortLureInfo
	FortModifier
	FortSummary
	MapPokemon
	NearbyPokemon
	WildPokemon
	MapCell
	SpawnPoint
	AuthTicket
	RequestEnvelope
	ResponseEnvelope
	Signature
	UnknownMessage
	BuyItemAndroidRequest
	BuyItemPokeCoinsRequest
	SendEncryptedSignatureRequest
	UnknownPtr8Request
	BuyItemAndroidResponse
	BuyItemPokeCoinsResponse
	GetStoreItemsResponse
	SendEncryptedSignatureResponse
	UnknownPtr8Response
	Request
	AddFortModifierMessage
	AttackGymMessage
	CatchPokemonMessage
	CheckAwardedBadgesMessage
	CheckChallengeMessage
	ClaimCodenameMessage
	CollectDailyBonusMessage
	CollectDailyDefenderBonusMessage
	DiskEncounterMessage
	DownloadItemTemplatesMessage
	DownloadRemoteConfigVersionMessage
	DownloadSettingsMessage
	EchoMessage
	EncounterMessage
	EncounterTutorialCompleteMessage
	EquipBadgeMessage
	EvolvePokemonMessage
	FortDeployPokemonMessage
	FortDetailsMessage
	FortRecallPokemonMessage
	FortSearchMessage
	GetAssetDigestMessage
	GetBuddyWalkedMessage
	GetDownloadUrlsMessage
	GetGymDetailsMessage
	GetHatchedEggsMessage
	GetInboxMessage
	GetIncensePokemonMessage
	GetInventoryMessage
	GetMapObjectsMessage
	GetPlayerMessage
	GetPlayerProfileMessage
	IncenseEncounterMessage
	LevelUpRewardsMessage
	ListAvatarCustomizationsMessage
	MarkTutorialCompleteMessage
	NicknamePokemonMessage
	RecycleInventoryItemMessage
	RegisterBackgroundDeviceMessage
	ReleasePokemonMessage
	SetAvatarItemAsViewedMessage
	SetAvatarMessage
	SetBuddyPokemonMessage
	SetContactSettingsMessage
	SetFavoritePokemonMessage
	SetPlayerTeamMessage
	SfidaActionLogMessage
	StartGymBattleMessage
	UpdateNotificationMessage
	UpgradePokemonMessage
	UseIncenseMessage
	UseItemCaptureMessage
	UseItemEggIncubatorMessage
	UseItemEncounterMessage
	UseItemGymMessage
	UseItemPotionMessage
	UseItemReviveMessage
	UseItemXpBoostMessage
	VerifyChallengeMessage
	AddFortModifierResponse
	AttackGymResponse
	CatchPokemonResponse
	CheckAwardedBadgesResponse
	CheckChallengeResponse
	CheckCodenameAvailableResponse
	ClaimCodenameResponse
	CollectDailyBonusResponse
	CollectDailyDefenderBonusResponse
	DiskEncounterResponse
	DownloadItemTemplatesResponse
	DownloadRemoteConfigVersionResponse
	DownloadSettingsResponse
	EchoResponse
	EncounterResponse
	EncounterTutorialCompleteResponse
	EquipBadgeResponse
	EvolvePokemonResponse
	FortDeployPokemonResponse
	FortDetailsResponse
	FortRecallPokemonResponse
	FortSearchResponse
	GetAssetDigestResponse
	GetBuddyWalkedResponse
	GetDownloadUrlsResponse
	GetGymDetailsResponse
	GetHatchedEggsResponse
	GetInboxResponse
	GetIncensePokemonResponse
	GetInventoryResponse
	GetMapObjectsResponse
	GetPlayerProfileResponse
	GetPlayerResponse
	IncenseEncounterResponse
	LevelUpRewardsResponse
	ListAvatarCustomizationsResponse
	MarkTutorialCompleteResponse
	NicknamePokemonResponse
	RecycleInventoryItemResponse
	RegisterBackgroundDeviceResponse
	ReleasePokemonResponse
	SetAvatarItemAsViewedResponse
	SetAvatarResponse
	SetBuddyPokemonResponse
	SetContactSettingsResponse
	SetFavoritePokemonResponse
	SetPlayerTeamResponse
	SfidaActionLogResponse
	StartGymBattleResponse
	UpdateNotificationResponse
	UpgradePokemonResponse
	UseIncenseResponse
	UseItemCaptureResponse
	UseItemEggIncubatorResponse
	UseItemEncounterResponse
	UseItemGymResponse
	UseItemPotionResponse
	UseItemReviveResponse
	UseItemXpBoostResponse
	VerifyChallengeResponse
	AuthTicket
	Kitten
	GetKittenRequest
	GetKittenResponse
	DownloadSettingsAction
	EventSettings
	FestivalSettings
	FortSettings
	GlobalSettings
	GpsSettings
	InventorySettings
	LevelSettings
	MapSettings
	NewsSettings
	PasscodeSettings
	SfidaSettings
	TranslationSettings
	AvatarCustomizationSettings
	BadgeSettings
	CameraSettings
	EncounterSettings
	EquippedBadgeSettings
	FormSettings
	GenderSettings
	GymBattleSettings
	GymLevelSettings
	IapItemDisplay
	IapSettings
	ItemSettings
	MoveSequenceSettings
	MoveSettings
	PlayerLevelSettings
	PokemonSettings
	PokemonUpgradeSettings
	QuestSettings
	TypeEffectiveSettings
	BattleAttributes
	EggIncubatorAttributes
	ExperienceBoostAttributes
	FoodAttributes
	FortModifierAttributes
	IncenseAttributes
	InventoryUpgradeAttributes
	PokeballAttributes
	PotionAttributes
	ReviveAttributes
	CameraAttributes
	EncounterAttributes
	EvolutionBranch
	PokemonGenderSettings
	StatsAttributes
	DailyQuestSettings
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of NotificationState from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of PlayerAvatarType from data_player.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of PokeCandy from data_redeem.proto

// Ignoring public import of RedeemedAvatarItem from data_redeem.proto

// Ignoring public import of RedeemedItem from data_redeem.proto

type AssetDigestEntry struct {
	AssetId    string `protobuf:"bytes,1,opt,name=asset_id,json=assetId" json:"asset_id,omitempty"`
	BundleName string `protobuf:"bytes,2,opt,name=bundle_name,json=bundleName" json:"bundle_name,omitempty"`
	Version    int64  `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Checksum   uint32 `protobuf:"fixed32,4,opt,name=checksum" json:"checksum,omitempty"`
	Size       int32  `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	Key        []byte `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *AssetDigestEntry) Reset()                    { *m = AssetDigestEntry{} }
func (m *AssetDigestEntry) String() string            { return proto.CompactTextString(m) }
func (*AssetDigestEntry) ProtoMessage()               {}
func (*AssetDigestEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AssetDigestEntry) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *AssetDigestEntry) GetBundleName() string {
	if m != nil {
		return m.BundleName
	}
	return ""
}

func (m *AssetDigestEntry) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AssetDigestEntry) GetChecksum() uint32 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func (m *AssetDigestEntry) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *AssetDigestEntry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type BackgroundToken struct {
	Token          []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpirationTime int64  `protobuf:"varint,2,opt,name=expiration_time,json=expirationTime" json:"expiration_time,omitempty"`
	Iv             []byte `protobuf:"bytes,3,opt,name=iv,proto3" json:"iv,omitempty"`
}

func (m *BackgroundToken) Reset()                    { *m = BackgroundToken{} }
func (m *BackgroundToken) String() string            { return proto.CompactTextString(m) }
func (*BackgroundToken) ProtoMessage()               {}
func (*BackgroundToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BackgroundToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *BackgroundToken) GetExpirationTime() int64 {
	if m != nil {
		return m.ExpirationTime
	}
	return 0
}

func (m *BackgroundToken) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

type BuddyPokemon struct {
	Id            uint64  `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
	StartKmWalked float64 `protobuf:"fixed64,2,opt,name=start_km_walked,json=startKmWalked" json:"start_km_walked,omitempty"`
	LastKmAwarded float64 `protobuf:"fixed64,3,opt,name=last_km_awarded,json=lastKmAwarded" json:"last_km_awarded,omitempty"`
}

func (m *BuddyPokemon) Reset()                    { *m = BuddyPokemon{} }
func (m *BuddyPokemon) String() string            { return proto.CompactTextString(m) }
func (*BuddyPokemon) ProtoMessage()               {}
func (*BuddyPokemon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BuddyPokemon) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuddyPokemon) GetStartKmWalked() float64 {
	if m != nil {
		return m.StartKmWalked
	}
	return 0
}

func (m *BuddyPokemon) GetLastKmAwarded() float64 {
	if m != nil {
		return m.LastKmAwarded
	}
	return 0
}

type ClientVersion struct {
	MinVersion string `protobuf:"bytes,1,opt,name=min_version,json=minVersion" json:"min_version,omitempty"`
}

func (m *ClientVersion) Reset()                    { *m = ClientVersion{} }
func (m *ClientVersion) String() string            { return proto.CompactTextString(m) }
func (*ClientVersion) ProtoMessage()               {}
func (*ClientVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClientVersion) GetMinVersion() string {
	if m != nil {
		return m.MinVersion
	}
	return ""
}

type DownloadUrlEntry struct {
	AssetId  string `protobuf:"bytes,1,opt,name=asset_id,json=assetId" json:"asset_id,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Size     int32  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Checksum uint32 `protobuf:"fixed32,4,opt,name=checksum" json:"checksum,omitempty"`
}

func (m *DownloadUrlEntry) Reset()                    { *m = DownloadUrlEntry{} }
func (m *DownloadUrlEntry) String() string            { return proto.CompactTextString(m) }
func (*DownloadUrlEntry) ProtoMessage()               {}
func (*DownloadUrlEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DownloadUrlEntry) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *DownloadUrlEntry) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadUrlEntry) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DownloadUrlEntry) GetChecksum() uint32 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

type PlayerBadge struct {
	BadgeType    BadgeType `protobuf:"varint,1,opt,name=badge_type,json=badgeType,enum=SUNProtos.Enums.BadgeType" json:"badge_type,omitempty"`
	Rank         int32     `protobuf:"varint,2,opt,name=rank" json:"rank,omitempty"`
	StartValue   int32     `protobuf:"varint,3,opt,name=start_value,json=startValue" json:"start_value,omitempty"`
	EndValue     int32     `protobuf:"varint,4,opt,name=end_value,json=endValue" json:"end_value,omitempty"`
	CurrentValue float64   `protobuf:"fixed64,5,opt,name=current_value,json=currentValue" json:"current_value,omitempty"`
}

func (m *PlayerBadge) Reset()                    { *m = PlayerBadge{} }
func (m *PlayerBadge) String() string            { return proto.CompactTextString(m) }
func (*PlayerBadge) ProtoMessage()               {}
func (*PlayerBadge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerBadge) GetBadgeType() BadgeType {
	if m != nil {
		return m.BadgeType
	}
	return BadgeType_BADGE_UNSET
}

func (m *PlayerBadge) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *PlayerBadge) GetStartValue() int32 {
	if m != nil {
		return m.StartValue
	}
	return 0
}

func (m *PlayerBadge) GetEndValue() int32 {
	if m != nil {
		return m.EndValue
	}
	return 0
}

func (m *PlayerBadge) GetCurrentValue() float64 {
	if m != nil {
		return m.CurrentValue
	}
	return 0
}

type PlayerData struct {
	CreationTimestampMs     int64            `protobuf:"varint,1,opt,name=creation_timestamp_ms,json=creationTimestampMs" json:"creation_timestamp_ms,omitempty"`
	Username                string           `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Team                    TeamColor        `protobuf:"varint,5,opt,name=team,enum=SUNProtos.Enums.TeamColor" json:"team,omitempty"`
	TutorialState           []TutorialState  `protobuf:"varint,7,rep,packed,name=tutorial_state,json=tutorialState,enum=SUNProtos.Enums.TutorialState" json:"tutorial_state,omitempty"`
	Avatar                  *PlayerAvatar    `protobuf:"bytes,8,opt,name=avatar" json:"avatar,omitempty"`
	MaxPokemonStorage       int32            `protobuf:"varint,9,opt,name=max_pokemon_storage,json=maxPokemonStorage" json:"max_pokemon_storage,omitempty"`
	MaxItemStorage          int32            `protobuf:"varint,10,opt,name=max_item_storage,json=maxItemStorage" json:"max_item_storage,omitempty"`
	DailyBonus              *DailyBonus      `protobuf:"bytes,11,opt,name=daily_bonus,json=dailyBonus" json:"daily_bonus,omitempty"`
	EquippedBadge           *EquippedBadge   `protobuf:"bytes,12,opt,name=equipped_badge,json=equippedBadge" json:"equipped_badge,omitempty"`
	ContactSettings         *ContactSettings `protobuf:"bytes,13,opt,name=contact_settings,json=contactSettings" json:"contact_settings,omitempty"`
	Currencies              []*Currency      `protobuf:"bytes,14,rep,name=currencies" json:"currencies,omitempty"`
	RemainingCodenameClaims int32            `protobuf:"varint,15,opt,name=remaining_codename_claims,json=remainingCodenameClaims" json:"remaining_codename_claims,omitempty"`
	BuddyPokemon            *BuddyPokemon    `protobuf:"bytes,16,opt,name=buddy_pokemon,json=buddyPokemon" json:"buddy_pokemon,omitempty"`
	BattleLockoutEndMs      int64            `protobuf:"varint,17,opt,name=battle_lockout_end_ms,json=battleLockoutEndMs" json:"battle_lockout_end_ms,omitempty"`
	SecondaryPlayerAvatar   *PlayerAvatar    `protobuf:"bytes,18,opt,name=secondary_player_avatar,json=secondaryPlayerAvatar" json:"secondary_player_avatar,omitempty"`
	NameIsBlacklisted       bool             `protobuf:"varint,19,opt,name=name_is_blacklisted,json=nameIsBlacklisted" json:"name_is_blacklisted,omitempty"`
}

func (m *PlayerData) Reset()                    { *m = PlayerData{} }
func (m *PlayerData) String() string            { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()               {}
func (*PlayerData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlayerData) GetCreationTimestampMs() int64 {
	if m != nil {
		return m.CreationTimestampMs
	}
	return 0
}

func (m *PlayerData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PlayerData) GetTeam() TeamColor {
	if m != nil {
		return m.Team
	}
	return TeamColor_NEUTRAL
}

func (m *PlayerData) GetTutorialState() []TutorialState {
	if m != nil {
		return m.TutorialState
	}
	return nil
}

func (m *PlayerData) GetAvatar() *PlayerAvatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *PlayerData) GetMaxPokemonStorage() int32 {
	if m != nil {
		return m.MaxPokemonStorage
	}
	return 0
}

func (m *PlayerData) GetMaxItemStorage() int32 {
	if m != nil {
		return m.MaxItemStorage
	}
	return 0
}

func (m *PlayerData) GetDailyBonus() *DailyBonus {
	if m != nil {
		return m.DailyBonus
	}
	return nil
}

func (m *PlayerData) GetEquippedBadge() *EquippedBadge {
	if m != nil {
		return m.EquippedBadge
	}
	return nil
}

func (m *PlayerData) GetContactSettings() *ContactSettings {
	if m != nil {
		return m.ContactSettings
	}
	return nil
}

func (m *PlayerData) GetCurrencies() []*Currency {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *PlayerData) GetRemainingCodenameClaims() int32 {
	if m != nil {
		return m.RemainingCodenameClaims
	}
	return 0
}

func (m *PlayerData) GetBuddyPokemon() *BuddyPokemon {
	if m != nil {
		return m.BuddyPokemon
	}
	return nil
}

func (m *PlayerData) GetBattleLockoutEndMs() int64 {
	if m != nil {
		return m.BattleLockoutEndMs
	}
	return 0
}

func (m *PlayerData) GetSecondaryPlayerAvatar() *PlayerAvatar {
	if m != nil {
		return m.SecondaryPlayerAvatar
	}
	return nil
}

func (m *PlayerData) GetNameIsBlacklisted() bool {
	if m != nil {
		return m.NameIsBlacklisted
	}
	return false
}

type PokedexEntry struct {
	PokemonId            PokemonId `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId,enum=SUNProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	TimesEncountered     int32     `protobuf:"varint,2,opt,name=times_encountered,json=timesEncountered" json:"times_encountered,omitempty"`
	TimesCaptured        int32     `protobuf:"varint,3,opt,name=times_captured,json=timesCaptured" json:"times_captured,omitempty"`
	EvolutionStonePieces int32     `protobuf:"varint,4,opt,name=evolution_stone_pieces,json=evolutionStonePieces" json:"evolution_stone_pieces,omitempty"`
	EvolutionStones      int32     `protobuf:"varint,5,opt,name=evolution_stones,json=evolutionStones" json:"evolution_stones,omitempty"`
	CapturedCostumes     []Costume `protobuf:"varint,6,rep,packed,name=captured_costumes,json=capturedCostumes,enum=SUNProtos.Enums.Costume" json:"captured_costumes,omitempty"`
	CapturedForms        []Form    `protobuf:"varint,7,rep,packed,name=captured_forms,json=capturedForms,enum=SUNProtos.Enums.Form" json:"captured_forms,omitempty"`
	CapturedGenders      []Gender  `protobuf:"varint,8,rep,packed,name=captured_genders,json=capturedGenders,enum=SUNProtos.Enums.Gender" json:"captured_genders,omitempty"`
	CapturedShiny        bool      `protobuf:"varint,9,opt,name=captured_shiny,json=capturedShiny" json:"captured_shiny,omitempty"`
	EncounteredCostumes  []Costume `protobuf:"varint,10,rep,packed,name=encountered_costumes,json=encounteredCostumes,enum=SUNProtos.Enums.Costume" json:"encountered_costumes,omitempty"`
	EncounteredForms     []Form    `protobuf:"varint,11,rep,packed,name=encountered_forms,json=encounteredForms,enum=SUNProtos.Enums.Form" json:"encountered_forms,omitempty"`
	EncounteredGenders   []Gender  `protobuf:"varint,12,rep,packed,name=encountered_genders,json=encounteredGenders,enum=SUNProtos.Enums.Gender" json:"encountered_genders,omitempty"`
	EncounteredShiny     bool      `protobuf:"varint,13,opt,name=encountered_shiny,json=encounteredShiny" json:"encountered_shiny,omitempty"`
}

func (m *PokedexEntry) Reset()                    { *m = PokedexEntry{} }
func (m *PokedexEntry) String() string            { return proto.CompactTextString(m) }
func (*PokedexEntry) ProtoMessage()               {}
func (*PokedexEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PokedexEntry) GetPokemonId() PokemonId {
	if m != nil {
		return m.PokemonId
	}
	return PokemonId_MISSINGNO
}

func (m *PokedexEntry) GetTimesEncountered() int32 {
	if m != nil {
		return m.TimesEncountered
	}
	return 0
}

func (m *PokedexEntry) GetTimesCaptured() int32 {
	if m != nil {
		return m.TimesCaptured
	}
	return 0
}

func (m *PokedexEntry) GetEvolutionStonePieces() int32 {
	if m != nil {
		return m.EvolutionStonePieces
	}
	return 0
}

func (m *PokedexEntry) GetEvolutionStones() int32 {
	if m != nil {
		return m.EvolutionStones
	}
	return 0
}

func (m *PokedexEntry) GetCapturedCostumes() []Costume {
	if m != nil {
		return m.CapturedCostumes
	}
	return nil
}

func (m *PokedexEntry) GetCapturedForms() []Form {
	if m != nil {
		return m.CapturedForms
	}
	return nil
}

func (m *PokedexEntry) GetCapturedGenders() []Gender {
	if m != nil {
		return m.CapturedGenders
	}
	return nil
}

func (m *PokedexEntry) GetCapturedShiny() bool {
	if m != nil {
		return m.CapturedShiny
	}
	return false
}

func (m *PokedexEntry) GetEncounteredCostumes() []Costume {
	if m != nil {
		return m.EncounteredCostumes
	}
	return nil
}

func (m *PokedexEntry) GetEncounteredForms() []Form {
	if m != nil {
		return m.EncounteredForms
	}
	return nil
}

func (m *PokedexEntry) GetEncounteredGenders() []Gender {
	if m != nil {
		return m.EncounteredGenders
	}
	return nil
}

func (m *PokedexEntry) GetEncounteredShiny() bool {
	if m != nil {
		return m.EncounteredShiny
	}
	return false
}

type PokemonData struct {
	Id                     uint64          `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
	PokemonId              PokemonId       `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId,enum=SUNProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	Cp                     int32           `protobuf:"varint,3,opt,name=cp" json:"cp,omitempty"`
	Stamina                int32           `protobuf:"varint,4,opt,name=stamina" json:"stamina,omitempty"`
	StaminaMax             int32           `protobuf:"varint,5,opt,name=stamina_max,json=staminaMax" json:"stamina_max,omitempty"`
	Move_1                 PokemonMove     `protobuf:"varint,6,opt,name=move_1,json=move1,enum=SUNProtos.Enums.PokemonMove" json:"move_1,omitempty"`
	Move_2                 PokemonMove     `protobuf:"varint,7,opt,name=move_2,json=move2,enum=SUNProtos.Enums.PokemonMove" json:"move_2,omitempty"`
	DeployedFortId         string          `protobuf:"bytes,8,opt,name=deployed_fort_id,json=deployedFortId" json:"deployed_fort_id,omitempty"`
	OwnerName              string          `protobuf:"bytes,9,opt,name=owner_name,json=ownerName" json:"owner_name,omitempty"`
	IsEgg                  bool            `protobuf:"varint,10,opt,name=is_egg,json=isEgg" json:"is_egg,omitempty"`
	EggKmWalkedTarget      float64         `protobuf:"fixed64,11,opt,name=egg_km_walked_target,json=eggKmWalkedTarget" json:"egg_km_walked_target,omitempty"`
	EggKmWalkedStart       float64         `protobuf:"fixed64,12,opt,name=egg_km_walked_start,json=eggKmWalkedStart" json:"egg_km_walked_start,omitempty"`
	Origin                 int32           `protobuf:"varint,14,opt,name=origin" json:"origin,omitempty"`
	HeightM                float32         `protobuf:"fixed32,15,opt,name=height_m,json=heightM" json:"height_m,omitempty"`
	WeightKg               float32         `protobuf:"fixed32,16,opt,name=weight_kg,json=weightKg" json:"weight_kg,omitempty"`
	IndividualAttack       int32           `protobuf:"varint,17,opt,name=individual_attack,json=individualAttack" json:"individual_attack,omitempty"`
	IndividualDefense      int32           `protobuf:"varint,18,opt,name=individual_defense,json=individualDefense" json:"individual_defense,omitempty"`
	IndividualStamina      int32           `protobuf:"varint,19,opt,name=individual_stamina,json=individualStamina" json:"individual_stamina,omitempty"`
	CpMultiplier           float32         `protobuf:"fixed32,20,opt,name=cp_multiplier,json=cpMultiplier" json:"cp_multiplier,omitempty"`
	Pokeball               ItemId          `protobuf:"varint,21,opt,name=pokeball,enum=SUNProtos.Inventory.Item.ItemId" json:"pokeball,omitempty"`
	CapturedCellId         uint64          `protobuf:"varint,22,opt,name=captured_cell_id,json=capturedCellId" json:"captured_cell_id,omitempty"`
	BattlesAttacked        int32           `protobuf:"varint,23,opt,name=battles_attacked,json=battlesAttacked" json:"battles_attacked,omitempty"`
	BattlesDefended        int32           `protobuf:"varint,24,opt,name=battles_defended,json=battlesDefended" json:"battles_defended,omitempty"`
	EggIncubatorId         string          `protobuf:"bytes,25,opt,name=egg_incubator_id,json=eggIncubatorId" json:"egg_incubator_id,omitempty"`
	CreationTimeMs         uint64          `protobuf:"varint,26,opt,name=creation_time_ms,json=creationTimeMs" json:"creation_time_ms,omitempty"`
	NumUpgrades            int32           `protobuf:"varint,27,opt,name=num_upgrades,json=numUpgrades" json:"num_upgrades,omitempty"`
	AdditionalCpMultiplier float32         `protobuf:"fixed32,28,opt,name=additional_cp_multiplier,json=additionalCpMultiplier" json:"additional_cp_multiplier,omitempty"`
	Favorite               int32           `protobuf:"varint,29,opt,name=favorite" json:"favorite,omitempty"`
	Nickname               string          `protobuf:"bytes,30,opt,name=nickname" json:"nickname,omitempty"`
	FromFort               int32           `protobuf:"varint,31,opt,name=from_fort,json=fromFort" json:"from_fort,omitempty"`
	BuddyCandyAwarded      int32           `protobuf:"varint,32,opt,name=buddy_candy_awarded,json=buddyCandyAwarded" json:"buddy_candy_awarded,omitempty"`
	BuddyTotalKmWalked     float32         `protobuf:"fixed32,33,opt,name=buddy_total_km_walked,json=buddyTotalKmWalked" json:"buddy_total_km_walked,omitempty"`
	DisplayPokemonId       int32           `protobuf:"varint,34,opt,name=display_pokemon_id,json=displayPokemonId" json:"display_pokemon_id,omitempty"`
	DisplayCp              int32           `protobuf:"varint,35,opt,name=display_cp,json=displayCp" json:"display_cp,omitempty"`
	PokemonDisplay         *PokemonDisplay `protobuf:"bytes,36,opt,name=pokemon_display,json=pokemonDisplay" json:"pokemon_display,omitempty"`
}

func (m *PokemonData) Reset()                    { *m = PokemonData{} }
func (m *PokemonData) String() string            { return proto.CompactTextString(m) }
func (*PokemonData) ProtoMessage()               {}
func (*PokemonData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PokemonData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PokemonData) GetPokemonId() PokemonId {
	if m != nil {
		return m.PokemonId
	}
	return PokemonId_MISSINGNO
}

func (m *PokemonData) GetCp() int32 {
	if m != nil {
		return m.Cp
	}
	return 0
}

func (m *PokemonData) GetStamina() int32 {
	if m != nil {
		return m.Stamina
	}
	return 0
}

func (m *PokemonData) GetStaminaMax() int32 {
	if m != nil {
		return m.StaminaMax
	}
	return 0
}

func (m *PokemonData) GetMove_1() PokemonMove {
	if m != nil {
		return m.Move_1
	}
	return PokemonMove_MOVE_UNSET
}

func (m *PokemonData) GetMove_2() PokemonMove {
	if m != nil {
		return m.Move_2
	}
	return PokemonMove_MOVE_UNSET
}

func (m *PokemonData) GetDeployedFortId() string {
	if m != nil {
		return m.DeployedFortId
	}
	return ""
}

func (m *PokemonData) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *PokemonData) GetIsEgg() bool {
	if m != nil {
		return m.IsEgg
	}
	return false
}

func (m *PokemonData) GetEggKmWalkedTarget() float64 {
	if m != nil {
		return m.EggKmWalkedTarget
	}
	return 0
}

func (m *PokemonData) GetEggKmWalkedStart() float64 {
	if m != nil {
		return m.EggKmWalkedStart
	}
	return 0
}

func (m *PokemonData) GetOrigin() int32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *PokemonData) GetHeightM() float32 {
	if m != nil {
		return m.HeightM
	}
	return 0
}

func (m *PokemonData) GetWeightKg() float32 {
	if m != nil {
		return m.WeightKg
	}
	return 0
}

func (m *PokemonData) GetIndividualAttack() int32 {
	if m != nil {
		return m.IndividualAttack
	}
	return 0
}

func (m *PokemonData) GetIndividualDefense() int32 {
	if m != nil {
		return m.IndividualDefense
	}
	return 0
}

func (m *PokemonData) GetIndividualStamina() int32 {
	if m != nil {
		return m.IndividualStamina
	}
	return 0
}

func (m *PokemonData) GetCpMultiplier() float32 {
	if m != nil {
		return m.CpMultiplier
	}
	return 0
}

func (m *PokemonData) GetPokeball() ItemId {
	if m != nil {
		return m.Pokeball
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *PokemonData) GetCapturedCellId() uint64 {
	if m != nil {
		return m.CapturedCellId
	}
	return 0
}

func (m *PokemonData) GetBattlesAttacked() int32 {
	if m != nil {
		return m.BattlesAttacked
	}
	return 0
}

func (m *PokemonData) GetBattlesDefended() int32 {
	if m != nil {
		return m.BattlesDefended
	}
	return 0
}

func (m *PokemonData) GetEggIncubatorId() string {
	if m != nil {
		return m.EggIncubatorId
	}
	return ""
}

func (m *PokemonData) GetCreationTimeMs() uint64 {
	if m != nil {
		return m.CreationTimeMs
	}
	return 0
}

func (m *PokemonData) GetNumUpgrades() int32 {
	if m != nil {
		return m.NumUpgrades
	}
	return 0
}

func (m *PokemonData) GetAdditionalCpMultiplier() float32 {
	if m != nil {
		return m.AdditionalCpMultiplier
	}
	return 0
}

func (m *PokemonData) GetFavorite() int32 {
	if m != nil {
		return m.Favorite
	}
	return 0
}

func (m *PokemonData) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *PokemonData) GetFromFort() int32 {
	if m != nil {
		return m.FromFort
	}
	return 0
}

func (m *PokemonData) GetBuddyCandyAwarded() int32 {
	if m != nil {
		return m.BuddyCandyAwarded
	}
	return 0
}

func (m *PokemonData) GetBuddyTotalKmWalked() float32 {
	if m != nil {
		return m.BuddyTotalKmWalked
	}
	return 0
}

func (m *PokemonData) GetDisplayPokemonId() int32 {
	if m != nil {
		return m.DisplayPokemonId
	}
	return 0
}

func (m *PokemonData) GetDisplayCp() int32 {
	if m != nil {
		return m.DisplayCp
	}
	return 0
}

func (m *PokemonData) GetPokemonDisplay() *PokemonDisplay {
	if m != nil {
		return m.PokemonDisplay
	}
	return nil
}

type PokemonDisplay struct {
	Costume Costume `protobuf:"varint,1,opt,name=costume,enum=SUNProtos.Enums.Costume" json:"costume,omitempty"`
	Gender  Gender  `protobuf:"varint,2,opt,name=gender,enum=SUNProtos.Enums.Gender" json:"gender,omitempty"`
	Shiny   bool    `protobuf:"varint,3,opt,name=shiny" json:"shiny,omitempty"`
	Form    Form    `protobuf:"varint,4,opt,name=form,enum=SUNProtos.Enums.Form" json:"form,omitempty"`
}

func (m *PokemonDisplay) Reset()                    { *m = PokemonDisplay{} }
func (m *PokemonDisplay) String() string            { return proto.CompactTextString(m) }
func (*PokemonDisplay) ProtoMessage()               {}
func (*PokemonDisplay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PokemonDisplay) GetCostume() Costume {
	if m != nil {
		return m.Costume
	}
	return Costume_COSTUME_UNSET
}

func (m *PokemonDisplay) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_GENDER_UNSET
}

func (m *PokemonDisplay) GetShiny() bool {
	if m != nil {
		return m.Shiny
	}
	return false
}

func (m *PokemonDisplay) GetForm() Form {
	if m != nil {
		return m.Form
	}
	return Form_FORM_UNSET
}

type RedeemPasscodeReward struct {
	Items       []*RedeemedItem       `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	AvatarItems []*RedeemedAvatarItem `protobuf:"bytes,2,rep,name=avatar_items,json=avatarItems" json:"avatar_items,omitempty"`
	EggPokemon  []*PokemonData        `protobuf:"bytes,3,rep,name=egg_pokemon,json=eggPokemon" json:"egg_pokemon,omitempty"`
	Pokemon     []*PokemonData        `protobuf:"bytes,4,rep,name=pokemon" json:"pokemon,omitempty"`
	PokeCandy   []*PokeCandy          `protobuf:"bytes,5,rep,name=poke_candy,json=pokeCandy" json:"poke_candy,omitempty"`
	Stardust    int32                 `protobuf:"varint,6,opt,name=stardust" json:"stardust,omitempty"`
	Pokecoins   int32                 `protobuf:"varint,7,opt,name=pokecoins" json:"pokecoins,omitempty"`
}

func (m *RedeemPasscodeReward) Reset()                    { *m = RedeemPasscodeReward{} }
func (m *RedeemPasscodeReward) String() string            { return proto.CompactTextString(m) }
func (*RedeemPasscodeReward) ProtoMessage()               {}
func (*RedeemPasscodeReward) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RedeemPasscodeReward) GetItems() []*RedeemedItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *RedeemPasscodeReward) GetAvatarItems() []*RedeemedAvatarItem {
	if m != nil {
		return m.AvatarItems
	}
	return nil
}

func (m *RedeemPasscodeReward) GetEggPokemon() []*PokemonData {
	if m != nil {
		return m.EggPokemon
	}
	return nil
}

func (m *RedeemPasscodeReward) GetPokemon() []*PokemonData {
	if m != nil {
		return m.Pokemon
	}
	return nil
}

func (m *RedeemPasscodeReward) GetPokeCandy() []*PokeCandy {
	if m != nil {
		return m.PokeCandy
	}
	return nil
}

func (m *RedeemPasscodeReward) GetStardust() int32 {
	if m != nil {
		return m.Stardust
	}
	return 0
}

func (m *RedeemPasscodeReward) GetPokecoins() int32 {
	if m != nil {
		return m.Pokecoins
	}
	return 0
}

func init() {
	proto.RegisterType((*AssetDigestEntry)(nil), "SUNProtos.Data.AssetDigestEntry")
	proto.RegisterType((*BackgroundToken)(nil), "SUNProtos.Data.BackgroundToken")
	proto.RegisterType((*BuddyPokemon)(nil), "SUNProtos.Data.BuddyPokemon")
	proto.RegisterType((*ClientVersion)(nil), "SUNProtos.Data.ClientVersion")
	proto.RegisterType((*DownloadUrlEntry)(nil), "SUNProtos.Data.DownloadUrlEntry")
	proto.RegisterType((*PlayerBadge)(nil), "SUNProtos.Data.PlayerBadge")
	proto.RegisterType((*PlayerData)(nil), "SUNProtos.Data.PlayerData")
	proto.RegisterType((*PokedexEntry)(nil), "SUNProtos.Data.PokedexEntry")
	proto.RegisterType((*PokemonData)(nil), "SUNProtos.Data.PokemonData")
	proto.RegisterType((*PokemonDisplay)(nil), "SUNProtos.Data.PokemonDisplay")
	proto.RegisterType((*RedeemPasscodeReward)(nil), "SUNProtos.Data.RedeemPasscodeReward")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xe1, 0x72, 0xdb, 0xb8,
	0x11, 0xae, 0x24, 0xcb, 0x96, 0x57, 0xb2, 0x2c, 0xc3, 0x76, 0xc2, 0x38, 0xb9, 0x44, 0x51, 0xae,
	0x57, 0x65, 0xae, 0xe7, 0x6b, 0x7c, 0xed, 0x4c, 0xd3, 0xde, 0x4c, 0xc7, 0x96, 0x7d, 0x57, 0x4f,
	0xce, 0x37, 0x2e, 0xec, 0x5c, 0x67, 0xda, 0x1f, 0x2c, 0x44, 0x22, 0x0c, 0x46, 0x24, 0xc8, 0x12,
	0xa0, 0x62, 0xf5, 0x11, 0xfa, 0xa7, 0xef, 0xd1, 0x07, 0xe8, 0xdf, 0xbe, 0x43, 0x1f, 0xa6, 0xbf,
	0x3b, 0x58, 0x80, 0x14, 0x95, 0xc4, 0xc9, 0xf5, 0x8f, 0x0d, 0x7c, 0xfb, 0xed, 0x02, 0x58, 0x2c,
	0x76, 0x97, 0x02, 0x08, 0x99, 0x66, 0x87, 0x59, 0x9e, 0xea, 0x94, 0xf4, 0xaf, 0x5e, 0x7e, 0x7f,
	0x69, 0x46, 0xea, 0xf0, 0x94, 0x69, 0x76, 0xd0, 0xe5, 0xb2, 0x48, 0x94, 0x15, 0x1e, 0xec, 0x18,
	0xa2, 0x9f, 0xc5, 0x6c, 0xc1, 0x73, 0x07, 0xed, 0x09, 0x39, 0xe7, 0x52, 0xa7, 0xf9, 0xc2, 0x17,
	0x9a, 0x27, 0x2b, 0xc4, 0x9c, 0x87, 0xbc, 0x84, 0x46, 0xff, 0x6c, 0xc0, 0xe0, 0x58, 0x29, 0xae,
	0x4f, 0x45, 0xc4, 0x95, 0x3e, 0x93, 0x3a, 0x5f, 0x90, 0x7b, 0xd0, 0x61, 0x06, 0xf3, 0x45, 0xe8,
	0x35, 0x86, 0x8d, 0xf1, 0x26, 0xdd, 0xc0, 0xf9, 0x79, 0x48, 0x1e, 0x41, 0x77, 0x5a, 0xc8, 0x30,
	0xe6, 0xbe, 0x64, 0x09, 0xf7, 0x9a, 0x28, 0x05, 0x0b, 0x7d, 0xcf, 0x12, 0x4e, 0x3c, 0xd8, 0x98,
	0xf3, 0x5c, 0x89, 0x54, 0x7a, 0xad, 0x61, 0x63, 0xdc, 0xa2, 0xe5, 0x94, 0x1c, 0x40, 0x27, 0x78,
	0xcd, 0x83, 0x99, 0x2a, 0x12, 0x6f, 0x6d, 0xd8, 0x18, 0x6f, 0xd0, 0x6a, 0x4e, 0x08, 0xac, 0x29,
	0xf1, 0x37, 0xee, 0xb5, 0x87, 0x8d, 0x71, 0x9b, 0xe2, 0x98, 0x0c, 0xa0, 0x35, 0xe3, 0x0b, 0x6f,
	0x7d, 0xd8, 0x18, 0xf7, 0xa8, 0x19, 0x8e, 0xfe, 0x02, 0xdb, 0x27, 0x2c, 0x98, 0x45, 0x79, 0x5a,
	0xc8, 0xf0, 0x3a, 0x9d, 0x71, 0x49, 0xf6, 0xa0, 0xad, 0xcd, 0x00, 0xf7, 0xd9, 0xa3, 0x76, 0x42,
	0x7e, 0x06, 0xdb, 0xfc, 0x26, 0x13, 0x39, 0xd3, 0x22, 0x95, 0xbe, 0x16, 0x6e, 0xa7, 0x2d, 0xda,
	0x5f, 0xc2, 0xd7, 0x22, 0xe1, 0xa4, 0x0f, 0x4d, 0x31, 0xc7, 0x8d, 0xf6, 0x68, 0x53, 0xcc, 0x47,
	0x12, 0x7a, 0x27, 0x45, 0x18, 0x2e, 0x2e, 0xd3, 0x19, 0x4f, 0x52, 0x89, 0x72, 0xeb, 0x83, 0x75,
	0xda, 0x14, 0x21, 0xf9, 0x0c, 0xb6, 0x95, 0x66, 0xb9, 0xf6, 0x67, 0x89, 0xff, 0x86, 0xc5, 0x33,
	0x1e, 0xa2, 0xe1, 0x06, 0xdd, 0x42, 0xf8, 0x45, 0xf2, 0x47, 0x04, 0x0d, 0x2f, 0x66, 0x0a, 0x69,
	0xec, 0x0d, 0xcb, 0x43, 0x1e, 0xe2, 0x22, 0x0d, 0xba, 0x65, 0xe0, 0x17, 0xc9, 0xb1, 0x05, 0x47,
	0xbf, 0x80, 0xad, 0x49, 0x2c, 0xb8, 0xd4, 0x3f, 0x38, 0x27, 0x3d, 0x82, 0x6e, 0x22, 0xa4, 0x5f,
	0xba, 0xd0, 0x7a, 0x1f, 0x12, 0x21, 0x1d, 0x61, 0x94, 0xc2, 0xe0, 0x34, 0x7d, 0x23, 0xe3, 0x94,
	0x85, 0x2f, 0xf3, 0xf8, 0xa3, 0xf7, 0x35, 0x80, 0x56, 0x91, 0xc7, 0xee, 0x9e, 0xcc, 0xb0, 0x72,
	0x75, 0xab, 0xe6, 0xea, 0x0f, 0x5c, 0xcd, 0xe8, 0xdf, 0x0d, 0xe8, 0x5e, 0x62, 0x6c, 0x9d, 0xb0,
	0x30, 0xe2, 0xe4, 0x39, 0xc0, 0xd4, 0x0c, 0x7c, 0xbd, 0xc8, 0x38, 0x2e, 0xd7, 0x3f, 0x3a, 0x38,
	0x5c, 0xc6, 0xe7, 0x19, 0x46, 0x26, 0x72, 0xaf, 0x17, 0x19, 0xa7, 0x9b, 0xd3, 0x72, 0x68, 0x96,
	0xce, 0x99, 0x9c, 0xe1, 0x6e, 0xda, 0x14, 0xc7, 0xe6, 0xc0, 0xd6, 0xa3, 0x73, 0x16, 0x17, 0xe5,
	0xae, 0x00, 0xa1, 0x1f, 0x0c, 0x42, 0xee, 0xc3, 0x26, 0x97, 0xa1, 0x13, 0xaf, 0xa1, 0xb8, 0xc3,
	0x65, 0x68, 0x85, 0x4f, 0x60, 0x2b, 0x28, 0xf2, 0x9c, 0xcb, 0x52, 0xbf, 0x8d, 0x5e, 0xee, 0x39,
	0x10, 0x49, 0xa3, 0xff, 0x6c, 0x00, 0xd8, 0x13, 0x98, 0xb7, 0x43, 0x8e, 0x60, 0x3f, 0xc8, 0xf9,
	0x32, 0x34, 0x94, 0x66, 0x49, 0xe6, 0x27, 0x0a, 0xcf, 0xd2, 0xa2, 0xbb, 0xa5, 0xf0, 0xba, 0x94,
	0x5d, 0x28, 0xe3, 0xa0, 0x42, 0xf1, 0xbc, 0x16, 0xf3, 0xd5, 0x9c, 0x1c, 0xc2, 0x9a, 0xe6, 0x2c,
	0xc1, 0xa5, 0xdf, 0xe7, 0x8a, 0x6b, 0xce, 0x92, 0x49, 0x1a, 0xa7, 0x39, 0x45, 0x1e, 0x39, 0x87,
	0xbe, 0x2e, 0x74, 0x9a, 0x0b, 0x16, 0xfb, 0x4a, 0x33, 0xcd, 0xbd, 0x8d, 0x61, 0x6b, 0xdc, 0x3f,
	0x7a, 0xf8, 0xae, 0xa6, 0xa3, 0x5d, 0x19, 0xd6, 0x49, 0x73, 0xd0, 0xa0, 0x5b, 0xba, 0x0e, 0x91,
	0xdf, 0xc2, 0x3a, 0x9b, 0x33, 0xcd, 0x72, 0xaf, 0x33, 0x6c, 0x8c, 0xbb, 0x47, 0x4f, 0x0e, 0x57,
	0xf3, 0xc4, 0xa1, 0x3d, 0xb6, 0xfb, 0x77, 0x8c, 0x54, 0xea, 0x54, 0xc8, 0x21, 0xec, 0x26, 0xec,
	0xc6, 0xcf, 0x6c, 0xa8, 0xfb, 0x4a, 0xa7, 0x39, 0x8b, 0xb8, 0xb7, 0x89, 0x2e, 0xde, 0x49, 0xd8,
	0x8d, 0x7b, 0x04, 0x57, 0x56, 0x40, 0xc6, 0x30, 0x30, 0x7c, 0x93, 0x4f, 0x2a, 0x32, 0x20, 0xb9,
	0x9f, 0xb0, 0x9b, 0x73, 0xcd, 0x93, 0x92, 0x79, 0x02, 0xdd, 0x90, 0x89, 0x78, 0xe1, 0x4f, 0x53,
	0x59, 0x28, 0xaf, 0x8b, 0x7b, 0x7b, 0x7c, 0xcb, 0xde, 0x4e, 0x0d, 0xf3, 0xc4, 0x10, 0x29, 0x84,
	0xd5, 0x98, 0xbc, 0x80, 0x3e, 0xff, 0x6b, 0x21, 0xb2, 0x8c, 0x87, 0x3e, 0x46, 0x90, 0xd7, 0x43,
	0x33, 0x9f, 0xde, 0x62, 0xe6, 0xcc, 0x91, 0x31, 0xf0, 0xe8, 0x16, 0xaf, 0x4f, 0xc9, 0x1f, 0x60,
	0x10, 0xa4, 0x52, 0xb3, 0x40, 0xfb, 0x8a, 0x6b, 0x2d, 0x64, 0xa4, 0xbc, 0x2d, 0x34, 0xf7, 0xd9,
	0x2d, 0xe6, 0x26, 0x96, 0x7e, 0xe5, 0xd8, 0x74, 0x3b, 0x58, 0x05, 0xc8, 0xef, 0x00, 0x6c, 0x90,
	0x05, 0x82, 0x2b, 0xaf, 0x3f, 0x6c, 0x8d, 0xbb, 0x47, 0x8f, 0x6e, 0x33, 0x66, 0x89, 0x0b, 0x5a,
	0x53, 0x21, 0xbf, 0x81, 0x7b, 0x39, 0x4f, 0x98, 0x90, 0x42, 0x46, 0x7e, 0x90, 0x86, 0xdc, 0x04,
	0x93, 0x1f, 0xc4, 0x4c, 0x24, 0xca, 0xdb, 0x46, 0xbf, 0xde, 0xad, 0x08, 0x13, 0x27, 0x9f, 0xa0,
	0x98, 0x1c, 0xc3, 0xd6, 0xd4, 0xa4, 0xa9, 0xf2, 0xf2, 0xbc, 0x01, 0x1e, 0xe6, 0xc1, 0xdb, 0xeb,
	0xd7, 0x73, 0x19, 0xed, 0x4d, 0xeb, 0x99, 0xed, 0x19, 0xec, 0x4f, 0x99, 0xd6, 0x31, 0xf7, 0xe3,
	0x34, 0x98, 0xa5, 0x85, 0xf6, 0xcd, 0x2b, 0x4b, 0x94, 0xb7, 0x83, 0xaf, 0x80, 0x58, 0xe1, 0x77,
	0x56, 0x76, 0x26, 0xc3, 0x0b, 0x45, 0xfe, 0x0c, 0x77, 0x15, 0x0f, 0x52, 0x19, 0xb2, 0x7c, 0xe1,
	0xca, 0x8d, 0xef, 0xc2, 0x8f, 0xfc, 0xf8, 0xf0, 0xdb, 0xaf, 0x6c, 0xd4, 0x61, 0x13, 0x8d, 0xe8,
	0x00, 0xa1, 0xfc, 0x69, 0xcc, 0x82, 0x59, 0x2c, 0x94, 0xe6, 0xa1, 0xb7, 0x3b, 0x6c, 0x8c, 0x3b,
	0x74, 0xc7, 0x88, 0xce, 0xd5, 0xc9, 0x52, 0x30, 0xfa, 0x6f, 0x1b, 0x7a, 0xe6, 0x2c, 0x21, 0xbf,
	0xb1, 0x49, 0xf0, 0x39, 0x40, 0x19, 0xca, 0x2e, 0x0d, 0xbe, 0xef, 0x31, 0xba, 0xe3, 0x9f, 0x87,
	0x74, 0x33, 0x2b, 0x87, 0xe4, 0x73, 0xd8, 0xc1, 0x44, 0xe0, 0x73, 0x19, 0xa4, 0x85, 0xd4, 0x3c,
	0x77, 0x79, 0xbd, 0x4d, 0x07, 0x28, 0x38, 0x5b, 0xe2, 0xe4, 0xa7, 0xd0, 0xb7, 0xe4, 0x80, 0x65,
	0xba, 0xc8, 0x5d, 0x66, 0x6f, 0xd3, 0x2d, 0x44, 0x27, 0x0e, 0x24, 0xbf, 0x84, 0x3b, 0x7c, 0x9e,
	0xc6, 0x05, 0xa6, 0x19, 0xa5, 0x53, 0xc9, 0xfd, 0x4c, 0xf0, 0x80, 0x2b, 0x97, 0xc3, 0xf6, 0x2a,
	0xe9, 0x95, 0x11, 0x5e, 0xa2, 0x8c, 0x3c, 0x85, 0xc1, 0x5b, 0x5a, 0xca, 0xd5, 0xc4, 0xed, 0x55,
	0xbe, 0x22, 0x67, 0xb0, 0x53, 0xee, 0xc0, 0x0f, 0x52, 0xa5, 0x8b, 0x84, 0x2b, 0x6f, 0x1d, 0x33,
	0x89, 0xf7, 0xce, 0xb1, 0x27, 0x96, 0x40, 0x07, 0xa5, 0x8a, 0x03, 0x14, 0xf9, 0x1a, 0xfa, 0x95,
	0x99, 0x57, 0x69, 0x9e, 0x28, 0x97, 0x8d, 0xf6, 0xdf, 0xb1, 0xf1, 0x4d, 0x9a, 0x27, 0x74, 0xab,
	0x24, 0x9b, 0x99, 0x22, 0x27, 0x50, 0x59, 0xf4, 0x23, 0x2e, 0x43, 0x9e, 0x2b, 0xaf, 0x83, 0xfa,
	0x77, 0xdf, 0xd1, 0xff, 0x16, 0xe5, 0x74, 0xbb, 0x54, 0xb0, 0x73, 0x65, 0x1c, 0x5a, 0xd9, 0x50,
	0xaf, 0x85, 0x5c, 0x60, 0x0a, 0xea, 0x2c, 0x97, 0xba, 0x32, 0x20, 0x79, 0x01, 0x7b, 0xb5, 0xeb,
	0x59, 0x1e, 0x19, 0x3e, 0x72, 0xe4, 0xdd, 0x9a, 0x56, 0x75, 0xea, 0x13, 0xd8, 0xa9, 0x1b, 0xb3,
	0x07, 0xef, 0x7e, 0xe8, 0xe0, 0x83, 0x1a, 0xdf, 0x9e, 0xfd, 0xf7, 0x50, 0x37, 0x5d, 0x1d, 0xbf,
	0xf7, 0xe1, 0xe3, 0x93, 0x9a, 0x4e, 0xe9, 0x81, 0xcf, 0x57, 0x77, 0x63, 0x9d, 0xb0, 0x85, 0x4e,
	0xa8, 0x2f, 0x8b, 0x7e, 0x18, 0xfd, 0xbd, 0x0b, 0x5d, 0x17, 0xc5, 0x58, 0xce, 0xde, 0x6e, 0x51,
	0x56, 0xdf, 0x41, 0xf3, 0xff, 0x79, 0x07, 0x7d, 0x68, 0x06, 0x99, 0x0b, 0xe7, 0x66, 0x90, 0x99,
	0x5e, 0xce, 0x14, 0x40, 0x21, 0x99, 0x0b, 0xda, 0x72, 0xea, 0xaa, 0xb6, 0x19, 0xfa, 0x09, 0xbb,
	0x71, 0x21, 0x0a, 0x0e, 0xba, 0x60, 0x37, 0xe4, 0x2b, 0x58, 0x4f, 0xd2, 0x39, 0xf7, 0x9f, 0x61,
	0xff, 0xd6, 0x5f, 0x49, 0x4d, 0x2b, 0x3b, 0xb8, 0x48, 0xe7, 0x9c, 0xb6, 0x0d, 0xf7, 0x59, 0xa5,
	0x74, 0xe4, 0x6d, 0xfc, 0x58, 0xa5, 0x23, 0x53, 0x96, 0x42, 0x9e, 0xc5, 0xe9, 0xc2, 0xde, 0x23,
	0x36, 0x41, 0x1d, 0x2c, 0xd1, 0xfd, 0x12, 0xff, 0x26, 0xcd, 0x4d, 0x2f, 0xf4, 0x09, 0x40, 0xfa,
	0x46, 0xf2, 0xdc, 0xb6, 0xae, 0x9b, 0xc8, 0xd9, 0x44, 0x04, 0x3b, 0xd7, 0x7d, 0x58, 0x17, 0xca,
	0xe7, 0x51, 0x84, 0x55, 0xad, 0x43, 0xdb, 0x42, 0x9d, 0x45, 0x11, 0xf9, 0x12, 0xf6, 0x78, 0x14,
	0x2d, 0x1b, 0x3e, 0x5f, 0xb3, 0x3c, 0xe2, 0x1a, 0xab, 0x5a, 0x83, 0xee, 0xf0, 0x28, 0x2a, 0xbb,
	0xbe, 0x6b, 0x14, 0x90, 0x2f, 0x60, 0x77, 0x55, 0x01, 0x9b, 0x19, 0x2c, 0x5f, 0x0d, 0x3a, 0xa8,
	0xf1, 0xaf, 0x0c, 0x4e, 0xee, 0xc0, 0x7a, 0x9a, 0x8b, 0x48, 0x48, 0xaf, 0x8f, 0x5e, 0x74, 0x33,
	0xd3, 0xd4, 0xbd, 0xe6, 0x22, 0x7a, 0xad, 0xfd, 0x04, 0xcb, 0x41, 0x93, 0x6e, 0xd8, 0xf9, 0x85,
	0x69, 0x89, 0xde, 0x58, 0xd1, 0x2c, 0xc2, 0xd4, 0xdf, 0xa4, 0x1d, 0x0b, 0xbc, 0x88, 0x4c, 0x30,
	0x09, 0x19, 0x8a, 0xb9, 0x08, 0x0b, 0x16, 0xfb, 0x4c, 0x6b, 0x16, 0xcc, 0x30, 0xa9, 0xb7, 0xe9,
	0x60, 0x29, 0x38, 0x46, 0x9c, 0x7c, 0x01, 0xa4, 0x46, 0x0e, 0xf9, 0x2b, 0x2e, 0x15, 0xc7, 0x6c,
	0xde, 0xa6, 0x35, 0x33, 0xa7, 0x56, 0xf0, 0x16, 0xbd, 0x8c, 0x8d, 0xdd, 0xb7, 0xe9, 0x57, 0x2e,
	0x4a, 0x4c, 0x77, 0x96, 0xf9, 0x49, 0x11, 0x6b, 0x91, 0xc5, 0x82, 0xe7, 0xde, 0x1e, 0xee, 0xb5,
	0x17, 0x64, 0x17, 0x15, 0x46, 0xbe, 0x86, 0x8e, 0x89, 0xc0, 0x29, 0x8b, 0x63, 0x6f, 0x1f, 0xaf,
	0x7d, 0x58, 0xbb, 0xf6, 0xf3, 0xf2, 0x3b, 0xe6, 0xd0, 0x34, 0x18, 0xf8, 0xe7, 0x3c, 0xa4, 0x95,
	0x86, 0xb9, 0xfd, 0x65, 0x16, 0xe4, 0x71, 0x6c, 0x6e, 0xff, 0xce, 0xb0, 0x31, 0x5e, 0xa3, 0x55,
	0x52, 0x99, 0xf0, 0x38, 0x3e, 0x0f, 0x4d, 0x6a, 0xb5, 0x35, 0x4d, 0x39, 0xa7, 0xf0, 0xd0, 0xbb,
	0x6b, 0x53, 0xab, 0xc3, 0x8f, 0x1d, 0x5c, 0xa7, 0xa2, 0x4b, 0x4c, 0xfb, 0xee, 0xad, 0x50, 0x4f,
	0x1d, 0x6c, 0xd6, 0x37, 0x97, 0x2d, 0x64, 0x50, 0x4c, 0x99, 0x4e, 0x73, 0xb3, 0xfe, 0x3d, 0x1b,
	0x7d, 0x3c, 0x8a, 0xce, 0x4b, 0xf8, 0x1c, 0x99, 0x2b, 0x6d, 0xa7, 0xa9, 0xb5, 0x07, 0x6e, 0xa7,
	0xb5, 0x8e, 0xf3, 0x42, 0x91, 0xc7, 0xd0, 0x93, 0x45, 0xe2, 0x17, 0x59, 0x94, 0xb3, 0x90, 0x2b,
	0xef, 0x3e, 0x2e, 0xdd, 0x95, 0x45, 0xf2, 0xd2, 0x41, 0xe4, 0xd7, 0xe0, 0xb1, 0x30, 0x14, 0x46,
	0x89, 0xc5, 0xfe, 0xaa, 0x93, 0x1f, 0xa0, 0x93, 0xef, 0x2c, 0xe5, 0x93, 0xba, 0xbb, 0x0f, 0xa0,
	0xf3, 0x8a, 0xcd, 0xd3, 0x5c, 0x68, 0xee, 0x7d, 0x62, 0xbb, 0xe9, 0x72, 0x6e, 0x64, 0x52, 0x04,
	0x33, 0x7c, 0x1e, 0x0f, 0x6d, 0x97, 0x5b, 0xce, 0x4d, 0xcc, 0xbd, 0xca, 0xd3, 0x04, 0x9f, 0x98,
	0xf7, 0xc8, 0x29, 0xe6, 0x69, 0x62, 0xde, 0x96, 0x29, 0xde, 0xb6, 0x1f, 0x09, 0x98, 0x0c, 0x17,
	0xd5, 0x27, 0xcf, 0xd0, 0x06, 0x06, 0x8a, 0x26, 0x46, 0xe2, 0x3e, 0x7b, 0xb0, 0xf9, 0x40, 0xbe,
	0x4e, 0x35, 0x8b, 0x6b, 0x1f, 0x53, 0x8f, 0x71, 0xef, 0x04, 0x85, 0xd7, 0x46, 0x56, 0x7d, 0x51,
	0xfd, 0x1c, 0x48, 0x28, 0x94, 0xe9, 0x3a, 0xfc, 0x5a, 0x7a, 0x1b, 0xd9, 0xb8, 0x76, 0x92, 0x2a,
	0xa9, 0x99, 0xa7, 0x5e, 0xb2, 0x83, 0xcc, 0x7b, 0x82, 0xac, 0x4d, 0x87, 0x4c, 0x32, 0xf2, 0x2d,
	0x6c, 0x97, 0x46, 0x1c, 0xe8, 0x7d, 0x8a, 0x1d, 0xcc, 0xc3, 0x77, 0x3a, 0x18, 0x97, 0x69, 0x2d,
	0x8b, 0xf6, 0xb3, 0x95, 0xf9, 0xe8, 0x5f, 0x0d, 0xe8, 0xaf, 0x52, 0xc8, 0x11, 0x6c, 0xb8, 0xda,
	0xe4, 0x9a, 0x90, 0xdb, 0x4b, 0x53, 0x49, 0x24, 0x5f, 0xc2, 0xba, 0x2d, 0x1f, 0x2e, 0x5f, 0xdf,
	0x5a, 0x3d, 0x1c, 0xcd, 0x7c, 0xf6, 0xda, 0x2a, 0xd1, 0xb2, 0xa9, 0x0a, 0x27, 0xe4, 0x29, 0xac,
	0x99, 0x4a, 0x86, 0xc9, 0xfa, 0xd6, 0x42, 0x86, 0x94, 0xd1, 0x3f, 0x5a, 0xb0, 0x47, 0xf1, 0x87,
	0x80, 0x4b, 0xa6, 0x94, 0x69, 0x3f, 0x29, 0x37, 0x97, 0x43, 0x9e, 0x43, 0xdb, 0x74, 0xf8, 0xe6,
	0x6b, 0xa8, 0xf5, 0xbe, 0x96, 0xce, 0x2a, 0xb9, 0x7f, 0x3c, 0x34, 0x0f, 0x92, 0x5a, 0x0d, 0xf2,
	0x1d, 0xf4, 0x6c, 0x3b, 0xe8, 0x5b, 0x0b, 0x4d, 0xb4, 0xf0, 0xf4, 0x23, 0x16, 0x6c, 0xff, 0x87,
	0x76, 0xba, 0xac, 0x1a, 0x9b, 0xc6, 0xa4, 0x6b, 0x5e, 0x56, 0xd9, 0xe1, 0xb6, 0xd0, 0xd8, 0xfd,
	0xdb, 0xee, 0x87, 0x69, 0x46, 0x81, 0x47, 0x51, 0xd9, 0xde, 0xfe, 0x0a, 0x36, 0x4a, 0xcd, 0xb5,
	0x8f, 0x6b, 0x96, 0x5c, 0xd3, 0xd5, 0x9b, 0xa1, 0x8d, 0x63, 0xaf, 0x8d, 0x9a, 0xc3, 0x5b, 0x0e,
	0x60, 0x0c, 0x60, 0x54, 0xdb, 0x12, 0x8a, 0x43, 0xf3, 0x84, 0x4c, 0xba, 0x0f, 0x0b, 0xa5, 0xb1,
	0xf2, 0xb5, 0x69, 0x35, 0x27, 0x0f, 0x00, 0x89, 0x41, 0x2a, 0xa4, 0xc2, 0x0a, 0xd7, 0xa6, 0x4b,
	0xe0, 0xa4, 0xf3, 0xa7, 0x75, 0xfc, 0x49, 0x46, 0x5d, 0xfe, 0xe4, 0xb2, 0x71, 0xd9, 0xbc, 0x6c,
	0x4d, 0xed, 0xfc, 0xab, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xc8, 0xb1, 0xf0, 0x09, 0x12,
	0x00, 0x00,
}
