// Code generated by protoc-gen-go.
// source: data_quests.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of NotificationState from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of TutorialState from enums.proto

type DailyQuest struct {
	CurrentPeriodBucket int32 `protobuf:"varint,1,opt,name=current_period_bucket,json=currentPeriodBucket" json:"current_period_bucket,omitempty"`
	CurrentStreakCount  int32 `protobuf:"varint,2,opt,name=current_streak_count,json=currentStreakCount" json:"current_streak_count,omitempty"`
}

func (m *DailyQuest) Reset()                    { *m = DailyQuest{} }
func (m *DailyQuest) String() string            { return proto.CompactTextString(m) }
func (*DailyQuest) ProtoMessage()               {}
func (*DailyQuest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *DailyQuest) GetCurrentPeriodBucket() int32 {
	if m != nil {
		return m.CurrentPeriodBucket
	}
	return 0
}

func (m *DailyQuest) GetCurrentStreakCount() int32 {
	if m != nil {
		return m.CurrentStreakCount
	}
	return 0
}

type Quest struct {
	QuestType  QuestType   `protobuf:"varint,1,opt,name=quest_type,json=questType,enum=SUNProtos.Enums.QuestType" json:"quest_type,omitempty"`
	DailyQuest *DailyQuest `protobuf:"bytes,2,opt,name=daily_quest,json=dailyQuest" json:"daily_quest,omitempty"`
}

func (m *Quest) Reset()                    { *m = Quest{} }
func (m *Quest) String() string            { return proto.CompactTextString(m) }
func (*Quest) ProtoMessage()               {}
func (*Quest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *Quest) GetQuestType() QuestType {
	if m != nil {
		return m.QuestType
	}
	return QuestType_QUEST_UNKNOWN_TYPE
}

func (m *Quest) GetDailyQuest() *DailyQuest {
	if m != nil {
		return m.DailyQuest
	}
	return nil
}

func init() {
	proto.RegisterType((*DailyQuest)(nil), "SUNProtos.Data.Quests.DailyQuest")
	proto.RegisterType((*Quest)(nil), "SUNProtos.Data.Quests.Quest")
}

func init() { proto.RegisterFile("data_quests.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x8d, 0x70, 0xa2, 0x13, 0x10, 0x5c, 0x3d, 0x38, 0xae, 0xd2, 0xab, 0xac, 0x16, 0x89,
	0x95, 0x6d, 0x3c, 0x5b, 0x89, 0x39, 0x6d, 0x6c, 0x96, 0xbd, 0xec, 0x14, 0x21, 0x9a, 0xdd, 0xec,
	0xce, 0x16, 0xf9, 0x03, 0xfe, 0x6e, 0xc9, 0x24, 0x31, 0x8d, 0xdd, 0x83, 0x6f, 0x1e, 0xef, 0xbd,
	0x81, 0x2b, 0xa3, 0x49, 0xab, 0x2e, 0x62, 0xa0, 0x20, 0x9d, 0xb7, 0x64, 0xc5, 0xfa, 0xf0, 0xf1,
	0x5a, 0x0c, 0x2a, 0xc8, 0xbd, 0x26, 0x2d, 0xdf, 0x18, 0x6e, 0x53, 0x6c, 0xe3, 0xf7, 0x74, 0xb3,
	0xf3, 0x00, 0x7b, 0x5d, 0x7f, 0xf5, 0xcc, 0x44, 0x06, 0xeb, 0x2a, 0x7a, 0x8f, 0x2d, 0x29, 0x87,
	0xbe, 0xb6, 0x46, 0x1d, 0x63, 0xd5, 0x20, 0x6d, 0x92, 0xdb, 0xe4, 0x7e, 0x55, 0x5e, 0x4f, 0xb0,
	0x60, 0x96, 0x33, 0x12, 0x0f, 0x70, 0x33, 0x7b, 0x02, 0x79, 0xd4, 0x8d, 0xaa, 0x6c, 0x6c, 0x69,
	0x73, 0xca, 0x16, 0x31, 0xb1, 0x03, 0xa3, 0xe7, 0x81, 0xec, 0x7e, 0x12, 0x58, 0x8d, 0x79, 0x4f,
	0x00, 0xdc, 0x58, 0x51, 0xef, 0x90, 0x43, 0x2e, 0xb3, 0xad, 0x5c, 0x6a, 0xbf, 0x70, 0x53, 0xbe,
	0x7d, 0xef, 0x1d, 0x96, 0x17, 0xdd, 0x2c, 0x45, 0x0e, 0xa9, 0x19, 0x8a, 0x8f, 0x93, 0x39, 0x2d,
	0xcd, 0xee, 0xe4, 0xbf, 0x93, 0xe5, 0x32, 0xb1, 0x04, 0xf3, 0xa7, 0xf3, 0xf3, 0xcf, 0x33, 0xfe,
	0x42, 0x28, 0x4e, 0x8e, 0xa3, 0x7a, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xed, 0xe7, 0x1d, 0xec,
	0x48, 0x01, 0x00, 0x00,
}
