// Code generated by protoc-gen-go.
// source: data_capture.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of NotificationState from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

type CaptureAward struct {
	ActivityType []ActivityType `protobuf:"varint,1,rep,packed,name=activity_type,json=activityType,enum=SUNProtos.Enums.ActivityType" json:"activity_type,omitempty"`
	Xp           []int32        `protobuf:"varint,2,rep,packed,name=xp" json:"xp,omitempty"`
	Candy        []int32        `protobuf:"varint,3,rep,packed,name=candy" json:"candy,omitempty"`
	Stardust     []int32        `protobuf:"varint,4,rep,packed,name=stardust" json:"stardust,omitempty"`
}

func (m *CaptureAward) Reset()                    { *m = CaptureAward{} }
func (m *CaptureAward) String() string            { return proto.CompactTextString(m) }
func (*CaptureAward) ProtoMessage()               {}
func (*CaptureAward) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *CaptureAward) GetActivityType() []ActivityType {
	if m != nil {
		return m.ActivityType
	}
	return nil
}

func (m *CaptureAward) GetXp() []int32 {
	if m != nil {
		return m.Xp
	}
	return nil
}

func (m *CaptureAward) GetCandy() []int32 {
	if m != nil {
		return m.Candy
	}
	return nil
}

func (m *CaptureAward) GetStardust() []int32 {
	if m != nil {
		return m.Stardust
	}
	return nil
}

type CaptureProbability struct {
	PokeballType           []ItemId  `protobuf:"varint,1,rep,packed,name=pokeball_type,json=pokeballType,enum=SUNProtos.Inventory.Item.ItemId" json:"pokeball_type,omitempty"`
	CaptureProbability     []float32 `protobuf:"fixed32,2,rep,packed,name=capture_probability,json=captureProbability" json:"capture_probability,omitempty"`
	ReticleDifficultyScale float64   `protobuf:"fixed64,12,opt,name=reticle_difficulty_scale,json=reticleDifficultyScale" json:"reticle_difficulty_scale,omitempty"`
}

func (m *CaptureProbability) Reset()                    { *m = CaptureProbability{} }
func (m *CaptureProbability) String() string            { return proto.CompactTextString(m) }
func (*CaptureProbability) ProtoMessage()               {}
func (*CaptureProbability) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *CaptureProbability) GetPokeballType() []ItemId {
	if m != nil {
		return m.PokeballType
	}
	return nil
}

func (m *CaptureProbability) GetCaptureProbability() []float32 {
	if m != nil {
		return m.CaptureProbability
	}
	return nil
}

func (m *CaptureProbability) GetReticleDifficultyScale() float64 {
	if m != nil {
		return m.ReticleDifficultyScale
	}
	return 0
}

func init() {
	proto.RegisterType((*CaptureAward)(nil), "SUNProtos.Data.Capture.CaptureAward")
	proto.RegisterType((*CaptureProbability)(nil), "SUNProtos.Data.Capture.CaptureProbability")
}

func init() { proto.RegisterFile("data_capture.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xff, 0xe9, 0xfe, 0x93, 0x11, 0x37, 0x91, 0x28, 0x23, 0x0c, 0x94, 0xb2, 0xd3, 0x4e,
	0x3d, 0xb8, 0x8b, 0xd7, 0xcd, 0x29, 0xf4, 0x22, 0x65, 0xd3, 0x8b, 0x97, 0xf2, 0x36, 0xcd, 0x20,
	0xd8, 0xb5, 0x21, 0x7d, 0x3b, 0x97, 0xef, 0xe3, 0xe7, 0xf1, 0x33, 0x49, 0x9b, 0xae, 0x1b, 0x78,
	0x29, 0x2f, 0xcf, 0xef, 0x69, 0xde, 0xe7, 0x49, 0x28, 0x4b, 0x01, 0x21, 0x16, 0xa0, 0xb1, 0x32,
	0x32, 0xd0, 0xa6, 0xc0, 0x82, 0x8d, 0x37, 0xef, 0xaf, 0x51, 0x3d, 0x95, 0xc1, 0x0a, 0x10, 0x82,
	0x27, 0x47, 0x27, 0x97, 0x32, 0xaf, 0x76, 0xa5, 0x33, 0x4d, 0x6e, 0x55, 0xbe, 0x97, 0x39, 0x16,
	0xc6, 0xc6, 0x0a, 0xe5, 0xce, 0xa9, 0xd3, 0x6f, 0x42, 0x87, 0xad, 0x7d, 0xf1, 0x05, 0x26, 0x65,
	0x2f, 0x74, 0x04, 0x02, 0xd5, 0x5e, 0xa1, 0x8d, 0xd1, 0x6a, 0xc9, 0x89, 0xdf, 0x9b, 0x5d, 0x3d,
	0xdc, 0x05, 0xa7, 0x1d, 0xcf, 0xcd, 0xa9, 0x8b, 0xd6, 0xf5, 0x66, 0xb5, 0x5c, 0x7a, 0xd7, 0x64,
	0x3d, 0x84, 0x33, 0x85, 0x31, 0xea, 0x1d, 0x34, 0xf7, 0xfc, 0xde, 0xac, 0xdf, 0x50, 0xef, 0xa0,
	0x19, 0xa7, 0x7d, 0x01, 0x79, 0x6a, 0x79, 0xaf, 0x93, 0x9d, 0xc0, 0xee, 0xe9, 0xa0, 0x44, 0x30,
	0x69, 0x55, 0x22, 0xff, 0xdf, 0xc1, 0x4e, 0x9b, 0xfe, 0x10, 0xca, 0xda, 0x98, 0x91, 0x29, 0x12,
	0x48, 0x54, 0xa6, 0xd0, 0xb2, 0x90, 0x8e, 0x74, 0xf1, 0x29, 0x13, 0xc8, 0xb2, 0xf3, 0xb0, 0xfe,
	0x59, 0xd8, 0xf0, 0xd8, 0x3a, 0x08, 0xeb, 0xd6, 0xf5, 0x27, 0x4c, 0x5d, 0xde, 0xe3, 0xaf, 0x4d,
	0xde, 0x39, 0xbd, 0x69, 0x2f, 0x35, 0xd6, 0xa7, 0x0d, 0x4d, 0x01, 0xaf, 0xb1, 0x33, 0xf1, 0x77,
	0xff, 0x23, 0xe5, 0x46, 0xa2, 0x12, 0x99, 0x8c, 0x53, 0xb5, 0xdd, 0x2a, 0x51, 0x65, 0x68, 0xe3,
	0x52, 0x40, 0x26, 0xf9, 0xd0, 0x27, 0x33, 0xb2, 0x1e, 0xb7, 0x7c, 0xd5, 0xe1, 0x4d, 0x4d, 0x97,
	0x83, 0x8f, 0x8b, 0xe6, 0x01, 0xca, 0xe8, 0x5f, 0x44, 0x12, 0x37, 0xcf, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xc4, 0x7f, 0xf6, 0xeb, 0xdd, 0x01, 0x00, 0x00,
}
