// Code generated by protoc-gen-go.
// source: networking_platform_responses.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of PlayerAvatarType from data_player.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// THESE ARE SOMEWHAT SPECULATED, failed may be 2
type BuyItemAndroidResponse_Status int32

const (
	BuyItemAndroidResponse_UNKNOWN BuyItemAndroidResponse_Status = 0
	BuyItemAndroidResponse_SUCCESS BuyItemAndroidResponse_Status = 1
)

var BuyItemAndroidResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
}
var BuyItemAndroidResponse_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"SUCCESS": 1,
}

func (x BuyItemAndroidResponse_Status) String() string {
	return proto.EnumName(BuyItemAndroidResponse_Status_name, int32(x))
}
func (BuyItemAndroidResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor19, []int{0, 0}
}

// THESE ARE SOMEWHAT SPECULATED, should be a NOT ENOUGH ROOM status too for bag being full somewhere.
type BuyItemPokeCoinsResponse_Status int32

const (
	BuyItemPokeCoinsResponse_UNKNOWN              BuyItemPokeCoinsResponse_Status = 0
	BuyItemPokeCoinsResponse_SUCCESS              BuyItemPokeCoinsResponse_Status = 1
	BuyItemPokeCoinsResponse_NOT_ENOUGH_POKECOINS BuyItemPokeCoinsResponse_Status = 3
)

var BuyItemPokeCoinsResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	3: "NOT_ENOUGH_POKECOINS",
}
var BuyItemPokeCoinsResponse_Status_value = map[string]int32{
	"UNKNOWN":              0,
	"SUCCESS":              1,
	"NOT_ENOUGH_POKECOINS": 3,
}

func (x BuyItemPokeCoinsResponse_Status) String() string {
	return proto.EnumName(BuyItemPokeCoinsResponse_Status_name, int32(x))
}
func (BuyItemPokeCoinsResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor19, []int{1, 0}
}

type GetStoreItemsResponse_Status int32

const (
	GetStoreItemsResponse_UNDEFINED GetStoreItemsResponse_Status = 0
	GetStoreItemsResponse_OKAY      GetStoreItemsResponse_Status = 1
)

var GetStoreItemsResponse_Status_name = map[int32]string{
	0: "UNDEFINED",
	1: "OKAY",
}
var GetStoreItemsResponse_Status_value = map[string]int32{
	"UNDEFINED": 0,
	"OKAY":      1,
}

func (x GetStoreItemsResponse_Status) String() string {
	return proto.EnumName(GetStoreItemsResponse_Status_name, int32(x))
}
func (GetStoreItemsResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor19, []int{2, 0}
}

type BuyItemAndroidResponse struct {
	Result        BuyItemAndroidResponse_Status `protobuf:"varint,1,opt,name=result,enum=SUNProtos.Networking.Platform.Responses.BuyItemAndroidResponse_Status" json:"result,omitempty"`
	PurchaseToken string                        `protobuf:"bytes,2,opt,name=purchase_token,json=purchaseToken" json:"purchase_token,omitempty"`
}

func (m *BuyItemAndroidResponse) Reset()                    { *m = BuyItemAndroidResponse{} }
func (m *BuyItemAndroidResponse) String() string            { return proto.CompactTextString(m) }
func (*BuyItemAndroidResponse) ProtoMessage()               {}
func (*BuyItemAndroidResponse) Descriptor() ([]byte, []int) { return fileDescriptor19, []int{0} }

func (m *BuyItemAndroidResponse) GetResult() BuyItemAndroidResponse_Status {
	if m != nil {
		return m.Result
	}
	return BuyItemAndroidResponse_UNKNOWN
}

func (m *BuyItemAndroidResponse) GetPurchaseToken() string {
	if m != nil {
		return m.PurchaseToken
	}
	return ""
}

type BuyItemPokeCoinsResponse struct {
	Result BuyItemPokeCoinsResponse_Status `protobuf:"varint,1,opt,name=result,enum=SUNProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse_Status" json:"result,omitempty"`
}

func (m *BuyItemPokeCoinsResponse) Reset()                    { *m = BuyItemPokeCoinsResponse{} }
func (m *BuyItemPokeCoinsResponse) String() string            { return proto.CompactTextString(m) }
func (*BuyItemPokeCoinsResponse) ProtoMessage()               {}
func (*BuyItemPokeCoinsResponse) Descriptor() ([]byte, []int) { return fileDescriptor19, []int{1} }

func (m *BuyItemPokeCoinsResponse) GetResult() BuyItemPokeCoinsResponse_Status {
	if m != nil {
		return m.Result
	}
	return BuyItemPokeCoinsResponse_UNKNOWN
}

type GetStoreItemsResponse struct {
	Status           GetStoreItemsResponse_Status       `protobuf:"varint,1,opt,name=status,enum=SUNProtos.Networking.Platform.Responses.GetStoreItemsResponse_Status" json:"status,omitempty"`
	Items            []*GetStoreItemsResponse_StoreItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	PlayerCurrencies []*Currency                        `protobuf:"bytes,3,rep,name=player_currencies,json=playerCurrencies" json:"player_currencies,omitempty"`
	Unknown4         string                             `protobuf:"bytes,4,opt,name=unknown4" json:"unknown4,omitempty"`
}

func (m *GetStoreItemsResponse) Reset()                    { *m = GetStoreItemsResponse{} }
func (m *GetStoreItemsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStoreItemsResponse) ProtoMessage()               {}
func (*GetStoreItemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor19, []int{2} }

func (m *GetStoreItemsResponse) GetStatus() GetStoreItemsResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetStoreItemsResponse_UNDEFINED
}

func (m *GetStoreItemsResponse) GetItems() []*GetStoreItemsResponse_StoreItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetStoreItemsResponse) GetPlayerCurrencies() []*Currency {
	if m != nil {
		return m.PlayerCurrencies
	}
	return nil
}

func (m *GetStoreItemsResponse) GetUnknown4() string {
	if m != nil {
		return m.Unknown4
	}
	return ""
}

type GetStoreItemsResponse_StoreItem struct {
	ItemId         string            `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	IsIap          bool              `protobuf:"varint,2,opt,name=is_iap,json=isIap" json:"is_iap,omitempty"`
	CurrencyToBuy  *Currency         `protobuf:"bytes,3,opt,name=currency_to_buy,json=currencyToBuy" json:"currency_to_buy,omitempty"`
	YieldsCurrency *Currency         `protobuf:"bytes,4,opt,name=yields_currency,json=yieldsCurrency" json:"yields_currency,omitempty"`
	YieldsItem     *ItemData         `protobuf:"bytes,5,opt,name=yields_item,json=yieldsItem" json:"yields_item,omitempty"`
	Tags           map[string]string `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Unknown7       int32             `protobuf:"varint,7,opt,name=unknown7" json:"unknown7,omitempty"`
}

func (m *GetStoreItemsResponse_StoreItem) Reset()         { *m = GetStoreItemsResponse_StoreItem{} }
func (m *GetStoreItemsResponse_StoreItem) String() string { return proto.CompactTextString(m) }
func (*GetStoreItemsResponse_StoreItem) ProtoMessage()    {}
func (*GetStoreItemsResponse_StoreItem) Descriptor() ([]byte, []int) {
	return fileDescriptor19, []int{2, 0}
}

func (m *GetStoreItemsResponse_StoreItem) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *GetStoreItemsResponse_StoreItem) GetIsIap() bool {
	if m != nil {
		return m.IsIap
	}
	return false
}

func (m *GetStoreItemsResponse_StoreItem) GetCurrencyToBuy() *Currency {
	if m != nil {
		return m.CurrencyToBuy
	}
	return nil
}

func (m *GetStoreItemsResponse_StoreItem) GetYieldsCurrency() *Currency {
	if m != nil {
		return m.YieldsCurrency
	}
	return nil
}

func (m *GetStoreItemsResponse_StoreItem) GetYieldsItem() *ItemData {
	if m != nil {
		return m.YieldsItem
	}
	return nil
}

func (m *GetStoreItemsResponse_StoreItem) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetStoreItemsResponse_StoreItem) GetUnknown7() int32 {
	if m != nil {
		return m.Unknown7
	}
	return 0
}

type SendEncryptedSignatureResponse struct {
	Received bool `protobuf:"varint,1,opt,name=received" json:"received,omitempty"`
}

func (m *SendEncryptedSignatureResponse) Reset()                    { *m = SendEncryptedSignatureResponse{} }
func (m *SendEncryptedSignatureResponse) String() string            { return proto.CompactTextString(m) }
func (*SendEncryptedSignatureResponse) ProtoMessage()               {}
func (*SendEncryptedSignatureResponse) Descriptor() ([]byte, []int) { return fileDescriptor19, []int{3} }

func (m *SendEncryptedSignatureResponse) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

type UnknownPtr8Response struct {
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *UnknownPtr8Response) Reset()                    { *m = UnknownPtr8Response{} }
func (m *UnknownPtr8Response) String() string            { return proto.CompactTextString(m) }
func (*UnknownPtr8Response) ProtoMessage()               {}
func (*UnknownPtr8Response) Descriptor() ([]byte, []int) { return fileDescriptor19, []int{4} }

func (m *UnknownPtr8Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BuyItemAndroidResponse)(nil), "SUNProtos.Networking.Platform.Responses.BuyItemAndroidResponse")
	proto.RegisterType((*BuyItemPokeCoinsResponse)(nil), "SUNProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse")
	proto.RegisterType((*GetStoreItemsResponse)(nil), "SUNProtos.Networking.Platform.Responses.GetStoreItemsResponse")
	proto.RegisterType((*GetStoreItemsResponse_StoreItem)(nil), "SUNProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem")
	proto.RegisterType((*SendEncryptedSignatureResponse)(nil), "SUNProtos.Networking.Platform.Responses.SendEncryptedSignatureResponse")
	proto.RegisterType((*UnknownPtr8Response)(nil), "SUNProtos.Networking.Platform.Responses.UnknownPtr8Response")
	proto.RegisterEnum("SUNProtos.Networking.Platform.Responses.BuyItemAndroidResponse_Status", BuyItemAndroidResponse_Status_name, BuyItemAndroidResponse_Status_value)
	proto.RegisterEnum("SUNProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse_Status", BuyItemPokeCoinsResponse_Status_name, BuyItemPokeCoinsResponse_Status_value)
	proto.RegisterEnum("SUNProtos.Networking.Platform.Responses.GetStoreItemsResponse_Status", GetStoreItemsResponse_Status_name, GetStoreItemsResponse_Status_value)
}

func init() { proto.RegisterFile("networking_platform_responses.proto", fileDescriptor19) }

var fileDescriptor19 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0xc7, 0x97, 0x75, 0x4d, 0xdb, 0x33, 0x6d, 0xeb, 0xfc, 0x6d, 0x1f, 0x51, 0x2f, 0xa0, 0x04,
	0x21, 0x7a, 0x15, 0x24, 0x40, 0xda, 0x84, 0x76, 0xb3, 0x75, 0xd9, 0x56, 0x0d, 0xa5, 0x55, 0xd2,
	0x0a, 0x81, 0xc4, 0x82, 0xd7, 0x78, 0x25, 0x6a, 0x6b, 0x57, 0xb6, 0xb3, 0x29, 0x2f, 0xc6, 0x05,
	0xb7, 0xbc, 0x00, 0x8f, 0x84, 0x1c, 0x27, 0x61, 0x1a, 0x43, 0x74, 0x12, 0x37, 0x91, 0x8f, 0x75,
	0xfe, 0xbf, 0xf3, 0x3f, 0xf6, 0x71, 0xe0, 0x19, 0x25, 0xf2, 0x86, 0xf1, 0x69, 0x4c, 0x27, 0xe1,
	0x62, 0x86, 0xe5, 0x15, 0xe3, 0xf3, 0x90, 0x13, 0xb1, 0x60, 0x54, 0x10, 0xe1, 0x2c, 0x38, 0x93,
	0x0c, 0xbd, 0x08, 0x46, 0xde, 0x40, 0xad, 0x84, 0xe3, 0x95, 0xe9, 0xce, 0x20, 0x4f, 0x77, 0xfc,
	0x22, 0xbd, 0xb5, 0x1d, 0x61, 0x89, 0x15, 0x27, 0x25, 0x5c, 0x6b, 0x5b, 0x3b, 0x31, 0xbd, 0x26,
	0x54, 0x32, 0x9e, 0x86, 0xb1, 0x24, 0x73, 0xbd, 0x6b, 0x7f, 0x37, 0xe0, 0xff, 0xa3, 0x24, 0xed,
	0x49, 0x32, 0x3f, 0xa4, 0x11, 0x67, 0x71, 0x54, 0x40, 0xd0, 0x05, 0x98, 0x9c, 0x88, 0x64, 0x26,
	0x2d, 0xa3, 0x6d, 0x74, 0x36, 0x5f, 0x9d, 0x38, 0x4b, 0x56, 0x77, 0xee, 0x07, 0x3a, 0x81, 0xc4,
	0x32, 0x11, 0x7e, 0x4e, 0x45, 0xcf, 0x61, 0x73, 0x91, 0xf0, 0xf1, 0x17, 0x2c, 0x48, 0x28, 0xd9,
	0x94, 0x50, 0x6b, 0xb5, 0x6d, 0x74, 0x1a, 0xfe, 0x46, 0xb1, 0x3b, 0x54, 0x9b, 0xb6, 0x0d, 0xa6,
	0x16, 0xa2, 0x75, 0xa8, 0x8d, 0xbc, 0x73, 0xaf, 0xff, 0xde, 0x6b, 0xae, 0xa8, 0x20, 0x18, 0x75,
	0xbb, 0x6e, 0x10, 0x34, 0x0d, 0xfb, 0x9b, 0x01, 0x56, 0x5e, 0x74, 0xc0, 0xa6, 0xa4, 0xcb, 0x62,
	0x2a, 0xca, 0x3e, 0x3e, 0xdf, 0xe9, 0xe3, 0xec, 0xa1, 0x7d, 0xfc, 0x86, 0xbc, 0xd3, 0x89, 0x7d,
	0xf0, 0x77, 0x8b, 0xc8, 0x82, 0x1d, 0xaf, 0x3f, 0x0c, 0x5d, 0xaf, 0x3f, 0x3a, 0x3d, 0x0b, 0x07,
	0xfd, 0x73, 0xb7, 0xdb, 0xef, 0x79, 0x41, 0xb3, 0x62, 0x7f, 0x35, 0x61, 0xf7, 0x94, 0xc8, 0x40,
	0x32, 0x4e, 0x54, 0xb9, 0x5f, 0xce, 0x3f, 0x81, 0x29, 0x32, 0x6e, 0xee, 0xdc, 0x5d, 0xda, 0xf9,
	0xbd, 0xbc, 0xd2, 0xb6, 0x86, 0xa2, 0x0b, 0xa8, 0xaa, 0x49, 0x10, 0xd6, 0x6a, 0xbb, 0xd2, 0x59,
	0x7f, 0xc0, 0xb9, 0xfc, 0x89, 0x9e, 0x6f, 0xf9, 0x1a, 0x8b, 0xde, 0xc1, 0xb6, 0x9e, 0xc0, 0x70,
	0x9c, 0x70, 0x4e, 0xe8, 0x38, 0x26, 0xc2, 0xaa, 0x64, 0xb5, 0x9e, 0xdc, 0xaa, 0x75, 0x8c, 0x25,
	0x56, 0x55, 0xd4, 0xa8, 0x76, 0x75, 0x62, 0xea, 0x37, 0xb5, 0xb2, 0x5b, 0x0a, 0x51, 0x0b, 0xea,
	0x09, 0x9d, 0x52, 0x76, 0x43, 0xdf, 0x58, 0x6b, 0xd9, 0xa0, 0x94, 0x71, 0xeb, 0x47, 0x05, 0x1a,
	0x65, 0x79, 0xf4, 0x08, 0x6a, 0xca, 0x40, 0x18, 0x47, 0xd9, 0xb9, 0x35, 0x7c, 0x53, 0x85, 0xbd,
	0x08, 0xed, 0x82, 0x19, 0x8b, 0x30, 0xc6, 0x8b, 0x6c, 0xd2, 0xea, 0x7e, 0x35, 0x16, 0x3d, 0xbc,
	0x40, 0xa7, 0xb0, 0x95, 0x1b, 0x4c, 0x43, 0xc9, 0xc2, 0xcb, 0x24, 0xb5, 0x2a, 0x6d, 0x63, 0x19,
	0x97, 0x1b, 0x85, 0x6e, 0xc8, 0x8e, 0x92, 0x14, 0x9d, 0xc1, 0x56, 0x1a, 0x93, 0x59, 0x24, 0x8a,
	0x86, 0xd3, 0xcc, 0xe9, 0x12, 0xa0, 0x4d, 0xad, 0x2b, 0x62, 0xd4, 0x85, 0xf5, 0x9c, 0xa4, 0xac,
	0x5b, 0xd5, 0x8c, 0x62, 0xdf, 0xa2, 0xf4, 0x8a, 0xc7, 0xec, 0xa8, 0x96, 0xb3, 0x8f, 0x02, 0xfb,
	0xa0, 0x65, 0xd9, 0x39, 0x5c, 0xc1, 0x9a, 0xc4, 0x13, 0x61, 0x99, 0xd9, 0x91, 0xfb, 0xff, 0xea,
	0x7a, 0x9d, 0x21, 0x9e, 0x08, 0x97, 0x4a, 0x9e, 0xfa, 0x19, 0xff, 0xd6, 0xcd, 0xec, 0x59, 0xb5,
	0xb6, 0xd1, 0xa9, 0x96, 0x37, 0xb3, 0xd7, 0xda, 0x83, 0x46, 0x99, 0x8e, 0x9a, 0x50, 0x99, 0x92,
	0x34, 0xbf, 0x14, 0xb5, 0x44, 0x3b, 0x50, 0xbd, 0xc6, 0xb3, 0x84, 0xe4, 0x4f, 0x5f, 0x07, 0x6f,
	0x57, 0xf7, 0x0d, 0xfb, 0x69, 0xf9, 0xa6, 0x36, 0xa0, 0x31, 0xf2, 0x8e, 0xdd, 0x93, 0x9e, 0xe7,
	0x1e, 0x37, 0x57, 0x50, 0x1d, 0xd6, 0xfa, 0xe7, 0x87, 0x1f, 0x9a, 0x86, 0x7d, 0x00, 0x8f, 0x03,
	0x42, 0x23, 0x97, 0x8e, 0x79, 0xba, 0x90, 0x24, 0x0a, 0xe2, 0x09, 0xc5, 0x32, 0xe1, 0xa4, 0x7c,
	0x40, 0x2d, 0xa8, 0x73, 0x32, 0x26, 0xf1, 0x35, 0xd1, 0xa3, 0x50, 0xf7, 0xcb, 0xd8, 0x7e, 0x09,
	0xff, 0x8d, 0xb4, 0xcb, 0x81, 0xe4, 0xfb, 0xa5, 0xc4, 0x82, 0xda, 0x9c, 0x08, 0x81, 0x27, 0x85,
	0xa7, 0x22, 0x3c, 0xaa, 0x7f, 0x34, 0xb3, 0x7f, 0xa6, 0x18, 0xac, 0x0c, 0x8c, 0x4b, 0xbd, 0x7e,
	0xfd, 0x33, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x50, 0x87, 0xdc, 0xb8, 0x05, 0x00, 0x00,
}
