// Code generated by protoc-gen-go.
// source: networking_requests_messages.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of BattleAction from data_battle.proto

// Ignoring public import of BattleLog from data_battle.proto

// Ignoring public import of BattleParticipant from data_battle.proto

// Ignoring public import of BattlePokemonInfo from data_battle.proto

// Ignoring public import of BattleResults from data_battle.proto

// Ignoring public import of BattleActionType from data_battle.proto

// Ignoring public import of BattleState from data_battle.proto

// Ignoring public import of BattleType from data_battle.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of NotificationState from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of PlayerAvatarType from data_player.proto

type AddFortModifierMessage struct {
	ModifierType    ItemId  `protobuf:"varint,1,opt,name=modifier_type,json=modifierType,enum=SUNProtos.Inventory.Item.ItemId" json:"modifier_type,omitempty"`
	FortId          string  `protobuf:"bytes,2,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *AddFortModifierMessage) Reset()                    { *m = AddFortModifierMessage{} }
func (m *AddFortModifierMessage) String() string            { return proto.CompactTextString(m) }
func (*AddFortModifierMessage) ProtoMessage()               {}
func (*AddFortModifierMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{0} }

func (m *AddFortModifierMessage) GetModifierType() ItemId {
	if m != nil {
		return m.ModifierType
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *AddFortModifierMessage) GetFortId() string {
	if m != nil {
		return m.FortId
	}
	return ""
}

func (m *AddFortModifierMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *AddFortModifierMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type AttackGymMessage struct {
	GymId               string          `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	BattleId            string          `protobuf:"bytes,2,opt,name=battle_id,json=battleId" json:"battle_id,omitempty"`
	AttackActions       []*BattleAction `protobuf:"bytes,3,rep,name=attack_actions,json=attackActions" json:"attack_actions,omitempty"`
	LastRetrievedAction *BattleAction   `protobuf:"bytes,4,opt,name=last_retrieved_action,json=lastRetrievedAction" json:"last_retrieved_action,omitempty"`
	PlayerLatitude      float64         `protobuf:"fixed64,5,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude     float64         `protobuf:"fixed64,6,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *AttackGymMessage) Reset()                    { *m = AttackGymMessage{} }
func (m *AttackGymMessage) String() string            { return proto.CompactTextString(m) }
func (*AttackGymMessage) ProtoMessage()               {}
func (*AttackGymMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{1} }

func (m *AttackGymMessage) GetGymId() string {
	if m != nil {
		return m.GymId
	}
	return ""
}

func (m *AttackGymMessage) GetBattleId() string {
	if m != nil {
		return m.BattleId
	}
	return ""
}

func (m *AttackGymMessage) GetAttackActions() []*BattleAction {
	if m != nil {
		return m.AttackActions
	}
	return nil
}

func (m *AttackGymMessage) GetLastRetrievedAction() *BattleAction {
	if m != nil {
		return m.LastRetrievedAction
	}
	return nil
}

func (m *AttackGymMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *AttackGymMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type CatchPokemonMessage struct {
	EncounterId           uint64  `protobuf:"fixed64,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	Pokeball              ItemId  `protobuf:"varint,2,opt,name=pokeball,enum=SUNProtos.Inventory.Item.ItemId" json:"pokeball,omitempty"`
	NormalizedReticleSize float64 `protobuf:"fixed64,3,opt,name=normalized_reticle_size,json=normalizedReticleSize" json:"normalized_reticle_size,omitempty"`
	SpawnPointId          string  `protobuf:"bytes,4,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
	HitPokemon            bool    `protobuf:"varint,5,opt,name=hit_pokemon,json=hitPokemon" json:"hit_pokemon,omitempty"`
	SpinModifier          float64 `protobuf:"fixed64,6,opt,name=spin_modifier,json=spinModifier" json:"spin_modifier,omitempty"`
	NormalizedHitPosition float64 `protobuf:"fixed64,7,opt,name=normalized_hit_position,json=normalizedHitPosition" json:"normalized_hit_position,omitempty"`
}

func (m *CatchPokemonMessage) Reset()                    { *m = CatchPokemonMessage{} }
func (m *CatchPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*CatchPokemonMessage) ProtoMessage()               {}
func (*CatchPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{2} }

func (m *CatchPokemonMessage) GetEncounterId() uint64 {
	if m != nil {
		return m.EncounterId
	}
	return 0
}

func (m *CatchPokemonMessage) GetPokeball() ItemId {
	if m != nil {
		return m.Pokeball
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *CatchPokemonMessage) GetNormalizedReticleSize() float64 {
	if m != nil {
		return m.NormalizedReticleSize
	}
	return 0
}

func (m *CatchPokemonMessage) GetSpawnPointId() string {
	if m != nil {
		return m.SpawnPointId
	}
	return ""
}

func (m *CatchPokemonMessage) GetHitPokemon() bool {
	if m != nil {
		return m.HitPokemon
	}
	return false
}

func (m *CatchPokemonMessage) GetSpinModifier() float64 {
	if m != nil {
		return m.SpinModifier
	}
	return 0
}

func (m *CatchPokemonMessage) GetNormalizedHitPosition() float64 {
	if m != nil {
		return m.NormalizedHitPosition
	}
	return 0
}

type CheckAwardedBadgesMessage struct {
}

func (m *CheckAwardedBadgesMessage) Reset()                    { *m = CheckAwardedBadgesMessage{} }
func (m *CheckAwardedBadgesMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckAwardedBadgesMessage) ProtoMessage()               {}
func (*CheckAwardedBadgesMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{3} }

type CheckChallengeMessage struct {
	DebugRequest bool `protobuf:"varint,1,opt,name=debug_request,json=debugRequest" json:"debug_request,omitempty"`
}

func (m *CheckChallengeMessage) Reset()                    { *m = CheckChallengeMessage{} }
func (m *CheckChallengeMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckChallengeMessage) ProtoMessage()               {}
func (*CheckChallengeMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{4} }

func (m *CheckChallengeMessage) GetDebugRequest() bool {
	if m != nil {
		return m.DebugRequest
	}
	return false
}

type ClaimCodenameMessage struct {
	Codename string `protobuf:"bytes,1,opt,name=codename" json:"codename,omitempty"`
	Force    bool   `protobuf:"varint,2,opt,name=force" json:"force,omitempty"`
}

func (m *ClaimCodenameMessage) Reset()                    { *m = ClaimCodenameMessage{} }
func (m *ClaimCodenameMessage) String() string            { return proto.CompactTextString(m) }
func (*ClaimCodenameMessage) ProtoMessage()               {}
func (*ClaimCodenameMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{5} }

func (m *ClaimCodenameMessage) GetCodename() string {
	if m != nil {
		return m.Codename
	}
	return ""
}

func (m *ClaimCodenameMessage) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type CollectDailyBonusMessage struct {
}

func (m *CollectDailyBonusMessage) Reset()                    { *m = CollectDailyBonusMessage{} }
func (m *CollectDailyBonusMessage) String() string            { return proto.CompactTextString(m) }
func (*CollectDailyBonusMessage) ProtoMessage()               {}
func (*CollectDailyBonusMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{6} }

type CollectDailyDefenderBonusMessage struct {
}

func (m *CollectDailyDefenderBonusMessage) Reset()         { *m = CollectDailyDefenderBonusMessage{} }
func (m *CollectDailyDefenderBonusMessage) String() string { return proto.CompactTextString(m) }
func (*CollectDailyDefenderBonusMessage) ProtoMessage()    {}
func (*CollectDailyDefenderBonusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{7}
}

type DiskEncounterMessage struct {
	EncounterId     uint64  `protobuf:"varint,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	FortId          string  `protobuf:"bytes,2,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *DiskEncounterMessage) Reset()                    { *m = DiskEncounterMessage{} }
func (m *DiskEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*DiskEncounterMessage) ProtoMessage()               {}
func (*DiskEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{8} }

func (m *DiskEncounterMessage) GetEncounterId() uint64 {
	if m != nil {
		return m.EncounterId
	}
	return 0
}

func (m *DiskEncounterMessage) GetFortId() string {
	if m != nil {
		return m.FortId
	}
	return ""
}

func (m *DiskEncounterMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *DiskEncounterMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type DownloadItemTemplatesMessage struct {
	Paginate      bool   `protobuf:"varint,1,opt,name=paginate" json:"paginate,omitempty"`
	PageOffset    int32  `protobuf:"varint,2,opt,name=page_offset,json=pageOffset" json:"page_offset,omitempty"`
	PageTimestamp uint64 `protobuf:"varint,3,opt,name=page_timestamp,json=pageTimestamp" json:"page_timestamp,omitempty"`
}

func (m *DownloadItemTemplatesMessage) Reset()                    { *m = DownloadItemTemplatesMessage{} }
func (m *DownloadItemTemplatesMessage) String() string            { return proto.CompactTextString(m) }
func (*DownloadItemTemplatesMessage) ProtoMessage()               {}
func (*DownloadItemTemplatesMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{9} }

func (m *DownloadItemTemplatesMessage) GetPaginate() bool {
	if m != nil {
		return m.Paginate
	}
	return false
}

func (m *DownloadItemTemplatesMessage) GetPageOffset() int32 {
	if m != nil {
		return m.PageOffset
	}
	return 0
}

func (m *DownloadItemTemplatesMessage) GetPageTimestamp() uint64 {
	if m != nil {
		return m.PageTimestamp
	}
	return 0
}

type DownloadRemoteConfigVersionMessage struct {
	Platform           Platform `protobuf:"varint,1,opt,name=platform,enum=SUNProtos.Enums.Platform" json:"platform,omitempty"`
	DeviceManufacturer string   `protobuf:"bytes,2,opt,name=device_manufacturer,json=deviceManufacturer" json:"device_manufacturer,omitempty"`
	DeviceModel        string   `protobuf:"bytes,3,opt,name=device_model,json=deviceModel" json:"device_model,omitempty"`
	Locale             string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	AppVersion         uint32   `protobuf:"varint,5,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
}

func (m *DownloadRemoteConfigVersionMessage) Reset()         { *m = DownloadRemoteConfigVersionMessage{} }
func (m *DownloadRemoteConfigVersionMessage) String() string { return proto.CompactTextString(m) }
func (*DownloadRemoteConfigVersionMessage) ProtoMessage()    {}
func (*DownloadRemoteConfigVersionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{10}
}

func (m *DownloadRemoteConfigVersionMessage) GetPlatform() Platform {
	if m != nil {
		return m.Platform
	}
	return Platform_UNSET
}

func (m *DownloadRemoteConfigVersionMessage) GetDeviceManufacturer() string {
	if m != nil {
		return m.DeviceManufacturer
	}
	return ""
}

func (m *DownloadRemoteConfigVersionMessage) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *DownloadRemoteConfigVersionMessage) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *DownloadRemoteConfigVersionMessage) GetAppVersion() uint32 {
	if m != nil {
		return m.AppVersion
	}
	return 0
}

type DownloadSettingsMessage struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *DownloadSettingsMessage) Reset()                    { *m = DownloadSettingsMessage{} }
func (m *DownloadSettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*DownloadSettingsMessage) ProtoMessage()               {}
func (*DownloadSettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{11} }

func (m *DownloadSettingsMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type EchoMessage struct {
}

func (m *EchoMessage) Reset()                    { *m = EchoMessage{} }
func (m *EchoMessage) String() string            { return proto.CompactTextString(m) }
func (*EchoMessage) ProtoMessage()               {}
func (*EchoMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{12} }

type EncounterMessage struct {
	EncounterId     uint64  `protobuf:"fixed64,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	SpawnPointId    string  `protobuf:"bytes,2,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *EncounterMessage) Reset()                    { *m = EncounterMessage{} }
func (m *EncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*EncounterMessage) ProtoMessage()               {}
func (*EncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{13} }

func (m *EncounterMessage) GetEncounterId() uint64 {
	if m != nil {
		return m.EncounterId
	}
	return 0
}

func (m *EncounterMessage) GetSpawnPointId() string {
	if m != nil {
		return m.SpawnPointId
	}
	return ""
}

func (m *EncounterMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *EncounterMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type EncounterTutorialCompleteMessage struct {
	PokemonId PokemonId `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId,enum=SUNProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
}

func (m *EncounterTutorialCompleteMessage) Reset()         { *m = EncounterTutorialCompleteMessage{} }
func (m *EncounterTutorialCompleteMessage) String() string { return proto.CompactTextString(m) }
func (*EncounterTutorialCompleteMessage) ProtoMessage()    {}
func (*EncounterTutorialCompleteMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{14}
}

func (m *EncounterTutorialCompleteMessage) GetPokemonId() PokemonId {
	if m != nil {
		return m.PokemonId
	}
	return PokemonId_MISSINGNO
}

type EquipBadgeMessage struct {
	BadgeType BadgeType `protobuf:"varint,1,opt,name=badge_type,json=badgeType,enum=SUNProtos.Enums.BadgeType" json:"badge_type,omitempty"`
}

func (m *EquipBadgeMessage) Reset()                    { *m = EquipBadgeMessage{} }
func (m *EquipBadgeMessage) String() string            { return proto.CompactTextString(m) }
func (*EquipBadgeMessage) ProtoMessage()               {}
func (*EquipBadgeMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{15} }

func (m *EquipBadgeMessage) GetBadgeType() BadgeType {
	if m != nil {
		return m.BadgeType
	}
	return BadgeType_BADGE_UNSET
}

type EvolvePokemonMessage struct {
	PokemonId                uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	EvolutionItemRequirement ItemId `protobuf:"varint,2,opt,name=evolution_item_requirement,json=evolutionItemRequirement,enum=SUNProtos.Inventory.Item.ItemId" json:"evolution_item_requirement,omitempty"`
}

func (m *EvolvePokemonMessage) Reset()                    { *m = EvolvePokemonMessage{} }
func (m *EvolvePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*EvolvePokemonMessage) ProtoMessage()               {}
func (*EvolvePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{16} }

func (m *EvolvePokemonMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

func (m *EvolvePokemonMessage) GetEvolutionItemRequirement() ItemId {
	if m != nil {
		return m.EvolutionItemRequirement
	}
	return ItemId_ITEM_UNKNOWN
}

type FortDeployPokemonMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PokemonId       uint64  `protobuf:"fixed64,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *FortDeployPokemonMessage) Reset()                    { *m = FortDeployPokemonMessage{} }
func (m *FortDeployPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*FortDeployPokemonMessage) ProtoMessage()               {}
func (*FortDeployPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{17} }

func (m *FortDeployPokemonMessage) GetFortId() string {
	if m != nil {
		return m.FortId
	}
	return ""
}

func (m *FortDeployPokemonMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

func (m *FortDeployPokemonMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *FortDeployPokemonMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type FortDetailsMessage struct {
	FortId    string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *FortDetailsMessage) Reset()                    { *m = FortDetailsMessage{} }
func (m *FortDetailsMessage) String() string            { return proto.CompactTextString(m) }
func (*FortDetailsMessage) ProtoMessage()               {}
func (*FortDetailsMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{18} }

func (m *FortDetailsMessage) GetFortId() string {
	if m != nil {
		return m.FortId
	}
	return ""
}

func (m *FortDetailsMessage) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *FortDetailsMessage) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type FortRecallPokemonMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PokemonId       uint64  `protobuf:"fixed64,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *FortRecallPokemonMessage) Reset()                    { *m = FortRecallPokemonMessage{} }
func (m *FortRecallPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*FortRecallPokemonMessage) ProtoMessage()               {}
func (*FortRecallPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{19} }

func (m *FortRecallPokemonMessage) GetFortId() string {
	if m != nil {
		return m.FortId
	}
	return ""
}

func (m *FortRecallPokemonMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

func (m *FortRecallPokemonMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *FortRecallPokemonMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type FortSearchMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,2,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,3,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
	FortLatitude    float64 `protobuf:"fixed64,4,opt,name=fort_latitude,json=fortLatitude" json:"fort_latitude,omitempty"`
	FortLongitude   float64 `protobuf:"fixed64,5,opt,name=fort_longitude,json=fortLongitude" json:"fort_longitude,omitempty"`
}

func (m *FortSearchMessage) Reset()                    { *m = FortSearchMessage{} }
func (m *FortSearchMessage) String() string            { return proto.CompactTextString(m) }
func (*FortSearchMessage) ProtoMessage()               {}
func (*FortSearchMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{20} }

func (m *FortSearchMessage) GetFortId() string {
	if m != nil {
		return m.FortId
	}
	return ""
}

func (m *FortSearchMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *FortSearchMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

func (m *FortSearchMessage) GetFortLatitude() float64 {
	if m != nil {
		return m.FortLatitude
	}
	return 0
}

func (m *FortSearchMessage) GetFortLongitude() float64 {
	if m != nil {
		return m.FortLongitude
	}
	return 0
}

type GetAssetDigestMessage struct {
	Platform           Platform `protobuf:"varint,1,opt,name=platform,enum=SUNProtos.Enums.Platform" json:"platform,omitempty"`
	DeviceManufacturer string   `protobuf:"bytes,2,opt,name=device_manufacturer,json=deviceManufacturer" json:"device_manufacturer,omitempty"`
	DeviceModel        string   `protobuf:"bytes,3,opt,name=device_model,json=deviceModel" json:"device_model,omitempty"`
	Locale             string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	AppVersion         uint32   `protobuf:"varint,5,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
	Paginate           bool     `protobuf:"varint,6,opt,name=paginate" json:"paginate,omitempty"`
	PageOffset         int32    `protobuf:"varint,7,opt,name=page_offset,json=pageOffset" json:"page_offset,omitempty"`
	PageTimestamp      uint64   `protobuf:"varint,8,opt,name=page_timestamp,json=pageTimestamp" json:"page_timestamp,omitempty"`
}

func (m *GetAssetDigestMessage) Reset()                    { *m = GetAssetDigestMessage{} }
func (m *GetAssetDigestMessage) String() string            { return proto.CompactTextString(m) }
func (*GetAssetDigestMessage) ProtoMessage()               {}
func (*GetAssetDigestMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{21} }

func (m *GetAssetDigestMessage) GetPlatform() Platform {
	if m != nil {
		return m.Platform
	}
	return Platform_UNSET
}

func (m *GetAssetDigestMessage) GetDeviceManufacturer() string {
	if m != nil {
		return m.DeviceManufacturer
	}
	return ""
}

func (m *GetAssetDigestMessage) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *GetAssetDigestMessage) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *GetAssetDigestMessage) GetAppVersion() uint32 {
	if m != nil {
		return m.AppVersion
	}
	return 0
}

func (m *GetAssetDigestMessage) GetPaginate() bool {
	if m != nil {
		return m.Paginate
	}
	return false
}

func (m *GetAssetDigestMessage) GetPageOffset() int32 {
	if m != nil {
		return m.PageOffset
	}
	return 0
}

func (m *GetAssetDigestMessage) GetPageTimestamp() uint64 {
	if m != nil {
		return m.PageTimestamp
	}
	return 0
}

type GetBuddyWalkedMessage struct {
}

func (m *GetBuddyWalkedMessage) Reset()                    { *m = GetBuddyWalkedMessage{} }
func (m *GetBuddyWalkedMessage) String() string            { return proto.CompactTextString(m) }
func (*GetBuddyWalkedMessage) ProtoMessage()               {}
func (*GetBuddyWalkedMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{22} }

type GetDownloadUrlsMessage struct {
	AssetId []string `protobuf:"bytes,1,rep,name=asset_id,json=assetId" json:"asset_id,omitempty"`
}

func (m *GetDownloadUrlsMessage) Reset()                    { *m = GetDownloadUrlsMessage{} }
func (m *GetDownloadUrlsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetDownloadUrlsMessage) ProtoMessage()               {}
func (*GetDownloadUrlsMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{23} }

func (m *GetDownloadUrlsMessage) GetAssetId() []string {
	if m != nil {
		return m.AssetId
	}
	return nil
}

type GetGymDetailsMessage struct {
	GymId           string  `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,2,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,3,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
	GymLatitude     float64 `protobuf:"fixed64,4,opt,name=gym_latitude,json=gymLatitude" json:"gym_latitude,omitempty"`
	GymLongitude    float64 `protobuf:"fixed64,5,opt,name=gym_longitude,json=gymLongitude" json:"gym_longitude,omitempty"`
	ClientVersion   string  `protobuf:"bytes,6,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
}

func (m *GetGymDetailsMessage) Reset()                    { *m = GetGymDetailsMessage{} }
func (m *GetGymDetailsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetGymDetailsMessage) ProtoMessage()               {}
func (*GetGymDetailsMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{24} }

func (m *GetGymDetailsMessage) GetGymId() string {
	if m != nil {
		return m.GymId
	}
	return ""
}

func (m *GetGymDetailsMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *GetGymDetailsMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

func (m *GetGymDetailsMessage) GetGymLatitude() float64 {
	if m != nil {
		return m.GymLatitude
	}
	return 0
}

func (m *GetGymDetailsMessage) GetGymLongitude() float64 {
	if m != nil {
		return m.GymLongitude
	}
	return 0
}

func (m *GetGymDetailsMessage) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

type GetHatchedEggsMessage struct {
}

func (m *GetHatchedEggsMessage) Reset()                    { *m = GetHatchedEggsMessage{} }
func (m *GetHatchedEggsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetHatchedEggsMessage) ProtoMessage()               {}
func (*GetHatchedEggsMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{25} }

type GetInboxMessage struct {
}

func (m *GetInboxMessage) Reset()                    { *m = GetInboxMessage{} }
func (m *GetInboxMessage) String() string            { return proto.CompactTextString(m) }
func (*GetInboxMessage) ProtoMessage()               {}
func (*GetInboxMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{26} }

type GetIncensePokemonMessage struct {
	PlayerLatitude  float64 `protobuf:"fixed64,1,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,2,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *GetIncensePokemonMessage) Reset()                    { *m = GetIncensePokemonMessage{} }
func (m *GetIncensePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*GetIncensePokemonMessage) ProtoMessage()               {}
func (*GetIncensePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{27} }

func (m *GetIncensePokemonMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *GetIncensePokemonMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type GetInventoryMessage struct {
	LastTimestampMs int64 `protobuf:"varint,1,opt,name=last_timestamp_ms,json=lastTimestampMs" json:"last_timestamp_ms,omitempty"`
	ItemBeenSeen    int32 `protobuf:"varint,2,opt,name=item_been_seen,json=itemBeenSeen" json:"item_been_seen,omitempty"`
}

func (m *GetInventoryMessage) Reset()                    { *m = GetInventoryMessage{} }
func (m *GetInventoryMessage) String() string            { return proto.CompactTextString(m) }
func (*GetInventoryMessage) ProtoMessage()               {}
func (*GetInventoryMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{28} }

func (m *GetInventoryMessage) GetLastTimestampMs() int64 {
	if m != nil {
		return m.LastTimestampMs
	}
	return 0
}

func (m *GetInventoryMessage) GetItemBeenSeen() int32 {
	if m != nil {
		return m.ItemBeenSeen
	}
	return 0
}

type GetMapObjectsMessage struct {
	CellId           []uint64 `protobuf:"varint,1,rep,packed,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	SinceTimestampMs []int64  `protobuf:"varint,2,rep,packed,name=since_timestamp_ms,json=sinceTimestampMs" json:"since_timestamp_ms,omitempty"`
	Latitude         float64  `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude        float64  `protobuf:"fixed64,4,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *GetMapObjectsMessage) Reset()                    { *m = GetMapObjectsMessage{} }
func (m *GetMapObjectsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetMapObjectsMessage) ProtoMessage()               {}
func (*GetMapObjectsMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{29} }

func (m *GetMapObjectsMessage) GetCellId() []uint64 {
	if m != nil {
		return m.CellId
	}
	return nil
}

func (m *GetMapObjectsMessage) GetSinceTimestampMs() []int64 {
	if m != nil {
		return m.SinceTimestampMs
	}
	return nil
}

func (m *GetMapObjectsMessage) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GetMapObjectsMessage) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type GetPlayerMessage struct {
	PlayerLocale *GetPlayerMessage_PlayerLocale `protobuf:"bytes,1,opt,name=player_locale,json=playerLocale" json:"player_locale,omitempty"`
}

func (m *GetPlayerMessage) Reset()                    { *m = GetPlayerMessage{} }
func (m *GetPlayerMessage) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerMessage) ProtoMessage()               {}
func (*GetPlayerMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{30} }

func (m *GetPlayerMessage) GetPlayerLocale() *GetPlayerMessage_PlayerLocale {
	if m != nil {
		return m.PlayerLocale
	}
	return nil
}

type GetPlayerMessage_PlayerLocale struct {
	Country  string `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	Timezone string `protobuf:"bytes,3,opt,name=timezone" json:"timezone,omitempty"`
}

func (m *GetPlayerMessage_PlayerLocale) Reset()         { *m = GetPlayerMessage_PlayerLocale{} }
func (m *GetPlayerMessage_PlayerLocale) String() string { return proto.CompactTextString(m) }
func (*GetPlayerMessage_PlayerLocale) ProtoMessage()    {}
func (*GetPlayerMessage_PlayerLocale) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{30, 0}
}

func (m *GetPlayerMessage_PlayerLocale) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *GetPlayerMessage_PlayerLocale) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetPlayerMessage_PlayerLocale) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

type GetPlayerProfileMessage struct {
	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
}

func (m *GetPlayerProfileMessage) Reset()                    { *m = GetPlayerProfileMessage{} }
func (m *GetPlayerProfileMessage) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerProfileMessage) ProtoMessage()               {}
func (*GetPlayerProfileMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{31} }

func (m *GetPlayerProfileMessage) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type IncenseEncounterMessage struct {
	EncounterId       uint64 `protobuf:"varint,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	EncounterLocation string `protobuf:"bytes,2,opt,name=encounter_location,json=encounterLocation" json:"encounter_location,omitempty"`
}

func (m *IncenseEncounterMessage) Reset()                    { *m = IncenseEncounterMessage{} }
func (m *IncenseEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*IncenseEncounterMessage) ProtoMessage()               {}
func (*IncenseEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{32} }

func (m *IncenseEncounterMessage) GetEncounterId() uint64 {
	if m != nil {
		return m.EncounterId
	}
	return 0
}

func (m *IncenseEncounterMessage) GetEncounterLocation() string {
	if m != nil {
		return m.EncounterLocation
	}
	return ""
}

type LevelUpRewardsMessage struct {
	Level int32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
}

func (m *LevelUpRewardsMessage) Reset()                    { *m = LevelUpRewardsMessage{} }
func (m *LevelUpRewardsMessage) String() string            { return proto.CompactTextString(m) }
func (*LevelUpRewardsMessage) ProtoMessage()               {}
func (*LevelUpRewardsMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{33} }

func (m *LevelUpRewardsMessage) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type ListAvatarCustomizationsMessage struct {
	AvatarType PlayerAvatarType `protobuf:"varint,1,opt,name=avatar_type,json=avatarType,enum=SUNProtos.Data.Player.PlayerAvatarType" json:"avatar_type,omitempty"`
	Slot       []Slot           `protobuf:"varint,2,rep,packed,name=slot,enum=SUNProtos.Enums.Slot" json:"slot,omitempty"`
	Filters    []Filter         `protobuf:"varint,3,rep,packed,name=filters,enum=SUNProtos.Enums.Filter" json:"filters,omitempty"`
	Start      int32            `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	Limit      int32            `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListAvatarCustomizationsMessage) Reset()         { *m = ListAvatarCustomizationsMessage{} }
func (m *ListAvatarCustomizationsMessage) String() string { return proto.CompactTextString(m) }
func (*ListAvatarCustomizationsMessage) ProtoMessage()    {}
func (*ListAvatarCustomizationsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{34}
}

func (m *ListAvatarCustomizationsMessage) GetAvatarType() PlayerAvatarType {
	if m != nil {
		return m.AvatarType
	}
	return PlayerAvatarType_PLAYER_AVATAR_MALE
}

func (m *ListAvatarCustomizationsMessage) GetSlot() []Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

func (m *ListAvatarCustomizationsMessage) GetFilters() []Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ListAvatarCustomizationsMessage) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListAvatarCustomizationsMessage) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type MarkTutorialCompleteMessage struct {
	TutorialsCompleted    []TutorialState `protobuf:"varint,1,rep,packed,name=tutorials_completed,json=tutorialsCompleted,enum=SUNProtos.Enums.TutorialState" json:"tutorials_completed,omitempty"`
	SendMarketingEmails   bool            `protobuf:"varint,2,opt,name=send_marketing_emails,json=sendMarketingEmails" json:"send_marketing_emails,omitempty"`
	SendPushNotifications bool            `protobuf:"varint,3,opt,name=send_push_notifications,json=sendPushNotifications" json:"send_push_notifications,omitempty"`
}

func (m *MarkTutorialCompleteMessage) Reset()                    { *m = MarkTutorialCompleteMessage{} }
func (m *MarkTutorialCompleteMessage) String() string            { return proto.CompactTextString(m) }
func (*MarkTutorialCompleteMessage) ProtoMessage()               {}
func (*MarkTutorialCompleteMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{35} }

func (m *MarkTutorialCompleteMessage) GetTutorialsCompleted() []TutorialState {
	if m != nil {
		return m.TutorialsCompleted
	}
	return nil
}

func (m *MarkTutorialCompleteMessage) GetSendMarketingEmails() bool {
	if m != nil {
		return m.SendMarketingEmails
	}
	return false
}

func (m *MarkTutorialCompleteMessage) GetSendPushNotifications() bool {
	if m != nil {
		return m.SendPushNotifications
	}
	return false
}

type NicknamePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	Nickname  string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
}

func (m *NicknamePokemonMessage) Reset()                    { *m = NicknamePokemonMessage{} }
func (m *NicknamePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*NicknamePokemonMessage) ProtoMessage()               {}
func (*NicknamePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{36} }

func (m *NicknamePokemonMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

func (m *NicknamePokemonMessage) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type RecycleInventoryItemMessage struct {
	ItemId ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=SUNProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *RecycleInventoryItemMessage) Reset()                    { *m = RecycleInventoryItemMessage{} }
func (m *RecycleInventoryItemMessage) String() string            { return proto.CompactTextString(m) }
func (*RecycleInventoryItemMessage) ProtoMessage()               {}
func (*RecycleInventoryItemMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{37} }

func (m *RecycleInventoryItemMessage) GetItemId() ItemId {
	if m != nil {
		return m.ItemId
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *RecycleInventoryItemMessage) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RegisterBackgroundDeviceMessage struct {
	DeviceType string `protobuf:"bytes,1,opt,name=device_type,json=deviceType" json:"device_type,omitempty"`
	DeviceId   string `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *RegisterBackgroundDeviceMessage) Reset()         { *m = RegisterBackgroundDeviceMessage{} }
func (m *RegisterBackgroundDeviceMessage) String() string { return proto.CompactTextString(m) }
func (*RegisterBackgroundDeviceMessage) ProtoMessage()    {}
func (*RegisterBackgroundDeviceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{38}
}

func (m *RegisterBackgroundDeviceMessage) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *RegisterBackgroundDeviceMessage) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type ReleasePokemonMessage struct {
	PokemonId  uint64   `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	PokemonIds []uint64 `protobuf:"fixed64,2,rep,packed,name=pokemon_ids,json=pokemonIds" json:"pokemon_ids,omitempty"`
}

func (m *ReleasePokemonMessage) Reset()                    { *m = ReleasePokemonMessage{} }
func (m *ReleasePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*ReleasePokemonMessage) ProtoMessage()               {}
func (*ReleasePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{39} }

func (m *ReleasePokemonMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

func (m *ReleasePokemonMessage) GetPokemonIds() []uint64 {
	if m != nil {
		return m.PokemonIds
	}
	return nil
}

type SetAvatarItemAsViewedMessage struct {
	AvatarTemplateId []string `protobuf:"bytes,1,rep,name=avatar_template_id,json=avatarTemplateId" json:"avatar_template_id,omitempty"`
}

func (m *SetAvatarItemAsViewedMessage) Reset()                    { *m = SetAvatarItemAsViewedMessage{} }
func (m *SetAvatarItemAsViewedMessage) String() string            { return proto.CompactTextString(m) }
func (*SetAvatarItemAsViewedMessage) ProtoMessage()               {}
func (*SetAvatarItemAsViewedMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{40} }

func (m *SetAvatarItemAsViewedMessage) GetAvatarTemplateId() []string {
	if m != nil {
		return m.AvatarTemplateId
	}
	return nil
}

type SetAvatarMessage struct {
	PlayerAvatar *PlayerAvatar `protobuf:"bytes,2,opt,name=player_avatar,json=playerAvatar" json:"player_avatar,omitempty"`
}

func (m *SetAvatarMessage) Reset()                    { *m = SetAvatarMessage{} }
func (m *SetAvatarMessage) String() string            { return proto.CompactTextString(m) }
func (*SetAvatarMessage) ProtoMessage()               {}
func (*SetAvatarMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{41} }

func (m *SetAvatarMessage) GetPlayerAvatar() *PlayerAvatar {
	if m != nil {
		return m.PlayerAvatar
	}
	return nil
}

type SetBuddyPokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *SetBuddyPokemonMessage) Reset()                    { *m = SetBuddyPokemonMessage{} }
func (m *SetBuddyPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*SetBuddyPokemonMessage) ProtoMessage()               {}
func (*SetBuddyPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{42} }

func (m *SetBuddyPokemonMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

type SetContactSettingsMessage struct {
	ContactSettings *ContactSettings `protobuf:"bytes,1,opt,name=contact_settings,json=contactSettings" json:"contact_settings,omitempty"`
}

func (m *SetContactSettingsMessage) Reset()                    { *m = SetContactSettingsMessage{} }
func (m *SetContactSettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*SetContactSettingsMessage) ProtoMessage()               {}
func (*SetContactSettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{43} }

func (m *SetContactSettingsMessage) GetContactSettings() *ContactSettings {
	if m != nil {
		return m.ContactSettings
	}
	return nil
}

type SetFavoritePokemonMessage struct {
	PokemonId  int64 `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	IsFavorite bool  `protobuf:"varint,2,opt,name=is_favorite,json=isFavorite" json:"is_favorite,omitempty"`
}

func (m *SetFavoritePokemonMessage) Reset()                    { *m = SetFavoritePokemonMessage{} }
func (m *SetFavoritePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*SetFavoritePokemonMessage) ProtoMessage()               {}
func (*SetFavoritePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{44} }

func (m *SetFavoritePokemonMessage) GetPokemonId() int64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

func (m *SetFavoritePokemonMessage) GetIsFavorite() bool {
	if m != nil {
		return m.IsFavorite
	}
	return false
}

type SetPlayerTeamMessage struct {
	Team TeamColor `protobuf:"varint,1,opt,name=team,enum=SUNProtos.Enums.TeamColor" json:"team,omitempty"`
}

func (m *SetPlayerTeamMessage) Reset()                    { *m = SetPlayerTeamMessage{} }
func (m *SetPlayerTeamMessage) String() string            { return proto.CompactTextString(m) }
func (*SetPlayerTeamMessage) ProtoMessage()               {}
func (*SetPlayerTeamMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{45} }

func (m *SetPlayerTeamMessage) GetTeam() TeamColor {
	if m != nil {
		return m.Team
	}
	return TeamColor_NEUTRAL
}

type SfidaActionLogMessage struct {
}

func (m *SfidaActionLogMessage) Reset()                    { *m = SfidaActionLogMessage{} }
func (m *SfidaActionLogMessage) String() string            { return proto.CompactTextString(m) }
func (*SfidaActionLogMessage) ProtoMessage()               {}
func (*SfidaActionLogMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{46} }

type StartGymBattleMessage struct {
	GymId               string   `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	AttackingPokemonIds []uint64 `protobuf:"fixed64,2,rep,packed,name=attacking_pokemon_ids,json=attackingPokemonIds" json:"attacking_pokemon_ids,omitempty"`
	DefendingPokemonId  uint64   `protobuf:"fixed64,3,opt,name=defending_pokemon_id,json=defendingPokemonId" json:"defending_pokemon_id,omitempty"`
	PlayerLatitude      float64  `protobuf:"fixed64,4,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude     float64  `protobuf:"fixed64,5,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *StartGymBattleMessage) Reset()                    { *m = StartGymBattleMessage{} }
func (m *StartGymBattleMessage) String() string            { return proto.CompactTextString(m) }
func (*StartGymBattleMessage) ProtoMessage()               {}
func (*StartGymBattleMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{47} }

func (m *StartGymBattleMessage) GetGymId() string {
	if m != nil {
		return m.GymId
	}
	return ""
}

func (m *StartGymBattleMessage) GetAttackingPokemonIds() []uint64 {
	if m != nil {
		return m.AttackingPokemonIds
	}
	return nil
}

func (m *StartGymBattleMessage) GetDefendingPokemonId() uint64 {
	if m != nil {
		return m.DefendingPokemonId
	}
	return 0
}

func (m *StartGymBattleMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *StartGymBattleMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type UpdateNotificationMessage struct {
	NotificationIds   []string          `protobuf:"bytes,1,rep,name=notification_ids,json=notificationIds" json:"notification_ids,omitempty"`
	CreateTimestampMs []int64           `protobuf:"varint,2,rep,packed,name=create_timestamp_ms,json=createTimestampMs" json:"create_timestamp_ms,omitempty"`
	State             NotificationState `protobuf:"varint,3,opt,name=state,enum=SUNProtos.Enums.NotificationState" json:"state,omitempty"`
}

func (m *UpdateNotificationMessage) Reset()                    { *m = UpdateNotificationMessage{} }
func (m *UpdateNotificationMessage) String() string            { return proto.CompactTextString(m) }
func (*UpdateNotificationMessage) ProtoMessage()               {}
func (*UpdateNotificationMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{48} }

func (m *UpdateNotificationMessage) GetNotificationIds() []string {
	if m != nil {
		return m.NotificationIds
	}
	return nil
}

func (m *UpdateNotificationMessage) GetCreateTimestampMs() []int64 {
	if m != nil {
		return m.CreateTimestampMs
	}
	return nil
}

func (m *UpdateNotificationMessage) GetState() NotificationState {
	if m != nil {
		return m.State
	}
	return NotificationState_UNSET_STATE
}

type UpgradePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UpgradePokemonMessage) Reset()                    { *m = UpgradePokemonMessage{} }
func (m *UpgradePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*UpgradePokemonMessage) ProtoMessage()               {}
func (*UpgradePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{49} }

func (m *UpgradePokemonMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

type UseIncenseMessage struct {
	IncenseType ItemId `protobuf:"varint,1,opt,name=incense_type,json=incenseType,enum=SUNProtos.Inventory.Item.ItemId" json:"incense_type,omitempty"`
}

func (m *UseIncenseMessage) Reset()                    { *m = UseIncenseMessage{} }
func (m *UseIncenseMessage) String() string            { return proto.CompactTextString(m) }
func (*UseIncenseMessage) ProtoMessage()               {}
func (*UseIncenseMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{50} }

func (m *UseIncenseMessage) GetIncenseType() ItemId {
	if m != nil {
		return m.IncenseType
	}
	return ItemId_ITEM_UNKNOWN
}

type UseItemCaptureMessage struct {
	ItemId       ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=SUNProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	EncounterId  uint64 `protobuf:"fixed64,2,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	SpawnPointId string `protobuf:"bytes,3,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
}

func (m *UseItemCaptureMessage) Reset()                    { *m = UseItemCaptureMessage{} }
func (m *UseItemCaptureMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemCaptureMessage) ProtoMessage()               {}
func (*UseItemCaptureMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{51} }

func (m *UseItemCaptureMessage) GetItemId() ItemId {
	if m != nil {
		return m.ItemId
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *UseItemCaptureMessage) GetEncounterId() uint64 {
	if m != nil {
		return m.EncounterId
	}
	return 0
}

func (m *UseItemCaptureMessage) GetSpawnPointId() string {
	if m != nil {
		return m.SpawnPointId
	}
	return ""
}

type UseItemEggIncubatorMessage struct {
	ItemId    string `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemEggIncubatorMessage) Reset()                    { *m = UseItemEggIncubatorMessage{} }
func (m *UseItemEggIncubatorMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemEggIncubatorMessage) ProtoMessage()               {}
func (*UseItemEggIncubatorMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{52} }

func (m *UseItemEggIncubatorMessage) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *UseItemEggIncubatorMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

type UseItemEncounterMessage struct {
	Item           ItemId `protobuf:"varint,1,opt,name=item,enum=SUNProtos.Inventory.Item.ItemId" json:"item,omitempty"`
	EncounterId    uint64 `protobuf:"fixed64,2,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	SpawnPointGuid string `protobuf:"bytes,3,opt,name=spawn_point_guid,json=spawnPointGuid" json:"spawn_point_guid,omitempty"`
}

func (m *UseItemEncounterMessage) Reset()                    { *m = UseItemEncounterMessage{} }
func (m *UseItemEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemEncounterMessage) ProtoMessage()               {}
func (*UseItemEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{53} }

func (m *UseItemEncounterMessage) GetItem() ItemId {
	if m != nil {
		return m.Item
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *UseItemEncounterMessage) GetEncounterId() uint64 {
	if m != nil {
		return m.EncounterId
	}
	return 0
}

func (m *UseItemEncounterMessage) GetSpawnPointGuid() string {
	if m != nil {
		return m.SpawnPointGuid
	}
	return ""
}

type UseItemGymMessage struct {
	ItemId          ItemId  `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=SUNProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	GymId           string  `protobuf:"bytes,2,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *UseItemGymMessage) Reset()                    { *m = UseItemGymMessage{} }
func (m *UseItemGymMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemGymMessage) ProtoMessage()               {}
func (*UseItemGymMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{54} }

func (m *UseItemGymMessage) GetItemId() ItemId {
	if m != nil {
		return m.ItemId
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *UseItemGymMessage) GetGymId() string {
	if m != nil {
		return m.GymId
	}
	return ""
}

func (m *UseItemGymMessage) GetPlayerLatitude() float64 {
	if m != nil {
		return m.PlayerLatitude
	}
	return 0
}

func (m *UseItemGymMessage) GetPlayerLongitude() float64 {
	if m != nil {
		return m.PlayerLongitude
	}
	return 0
}

type UseItemPotionMessage struct {
	ItemId    ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=SUNProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"fixed64,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemPotionMessage) Reset()                    { *m = UseItemPotionMessage{} }
func (m *UseItemPotionMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemPotionMessage) ProtoMessage()               {}
func (*UseItemPotionMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{55} }

func (m *UseItemPotionMessage) GetItemId() ItemId {
	if m != nil {
		return m.ItemId
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *UseItemPotionMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

type UseItemReviveMessage struct {
	ItemId    ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=SUNProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"fixed64,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemReviveMessage) Reset()                    { *m = UseItemReviveMessage{} }
func (m *UseItemReviveMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemReviveMessage) ProtoMessage()               {}
func (*UseItemReviveMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{56} }

func (m *UseItemReviveMessage) GetItemId() ItemId {
	if m != nil {
		return m.ItemId
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *UseItemReviveMessage) GetPokemonId() uint64 {
	if m != nil {
		return m.PokemonId
	}
	return 0
}

type UseItemXpBoostMessage struct {
	ItemId ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=SUNProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
}

func (m *UseItemXpBoostMessage) Reset()                    { *m = UseItemXpBoostMessage{} }
func (m *UseItemXpBoostMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemXpBoostMessage) ProtoMessage()               {}
func (*UseItemXpBoostMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{57} }

func (m *UseItemXpBoostMessage) GetItemId() ItemId {
	if m != nil {
		return m.ItemId
	}
	return ItemId_ITEM_UNKNOWN
}

type VerifyChallengeMessage struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *VerifyChallengeMessage) Reset()                    { *m = VerifyChallengeMessage{} }
func (m *VerifyChallengeMessage) String() string            { return proto.CompactTextString(m) }
func (*VerifyChallengeMessage) ProtoMessage()               {}
func (*VerifyChallengeMessage) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{58} }

func (m *VerifyChallengeMessage) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*AddFortModifierMessage)(nil), "SUNProtos.Networking.Requests.Messages.AddFortModifierMessage")
	proto.RegisterType((*AttackGymMessage)(nil), "SUNProtos.Networking.Requests.Messages.AttackGymMessage")
	proto.RegisterType((*CatchPokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.CatchPokemonMessage")
	proto.RegisterType((*CheckAwardedBadgesMessage)(nil), "SUNProtos.Networking.Requests.Messages.CheckAwardedBadgesMessage")
	proto.RegisterType((*CheckChallengeMessage)(nil), "SUNProtos.Networking.Requests.Messages.CheckChallengeMessage")
	proto.RegisterType((*ClaimCodenameMessage)(nil), "SUNProtos.Networking.Requests.Messages.ClaimCodenameMessage")
	proto.RegisterType((*CollectDailyBonusMessage)(nil), "SUNProtos.Networking.Requests.Messages.CollectDailyBonusMessage")
	proto.RegisterType((*CollectDailyDefenderBonusMessage)(nil), "SUNProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage")
	proto.RegisterType((*DiskEncounterMessage)(nil), "SUNProtos.Networking.Requests.Messages.DiskEncounterMessage")
	proto.RegisterType((*DownloadItemTemplatesMessage)(nil), "SUNProtos.Networking.Requests.Messages.DownloadItemTemplatesMessage")
	proto.RegisterType((*DownloadRemoteConfigVersionMessage)(nil), "SUNProtos.Networking.Requests.Messages.DownloadRemoteConfigVersionMessage")
	proto.RegisterType((*DownloadSettingsMessage)(nil), "SUNProtos.Networking.Requests.Messages.DownloadSettingsMessage")
	proto.RegisterType((*EchoMessage)(nil), "SUNProtos.Networking.Requests.Messages.EchoMessage")
	proto.RegisterType((*EncounterMessage)(nil), "SUNProtos.Networking.Requests.Messages.EncounterMessage")
	proto.RegisterType((*EncounterTutorialCompleteMessage)(nil), "SUNProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage")
	proto.RegisterType((*EquipBadgeMessage)(nil), "SUNProtos.Networking.Requests.Messages.EquipBadgeMessage")
	proto.RegisterType((*EvolvePokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.EvolvePokemonMessage")
	proto.RegisterType((*FortDeployPokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.FortDeployPokemonMessage")
	proto.RegisterType((*FortDetailsMessage)(nil), "SUNProtos.Networking.Requests.Messages.FortDetailsMessage")
	proto.RegisterType((*FortRecallPokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.FortRecallPokemonMessage")
	proto.RegisterType((*FortSearchMessage)(nil), "SUNProtos.Networking.Requests.Messages.FortSearchMessage")
	proto.RegisterType((*GetAssetDigestMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetAssetDigestMessage")
	proto.RegisterType((*GetBuddyWalkedMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetBuddyWalkedMessage")
	proto.RegisterType((*GetDownloadUrlsMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetDownloadUrlsMessage")
	proto.RegisterType((*GetGymDetailsMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetGymDetailsMessage")
	proto.RegisterType((*GetHatchedEggsMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetHatchedEggsMessage")
	proto.RegisterType((*GetInboxMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetInboxMessage")
	proto.RegisterType((*GetIncensePokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetIncensePokemonMessage")
	proto.RegisterType((*GetInventoryMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetInventoryMessage")
	proto.RegisterType((*GetMapObjectsMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetMapObjectsMessage")
	proto.RegisterType((*GetPlayerMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetPlayerMessage")
	proto.RegisterType((*GetPlayerMessage_PlayerLocale)(nil), "SUNProtos.Networking.Requests.Messages.GetPlayerMessage.PlayerLocale")
	proto.RegisterType((*GetPlayerProfileMessage)(nil), "SUNProtos.Networking.Requests.Messages.GetPlayerProfileMessage")
	proto.RegisterType((*IncenseEncounterMessage)(nil), "SUNProtos.Networking.Requests.Messages.IncenseEncounterMessage")
	proto.RegisterType((*LevelUpRewardsMessage)(nil), "SUNProtos.Networking.Requests.Messages.LevelUpRewardsMessage")
	proto.RegisterType((*ListAvatarCustomizationsMessage)(nil), "SUNProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage")
	proto.RegisterType((*MarkTutorialCompleteMessage)(nil), "SUNProtos.Networking.Requests.Messages.MarkTutorialCompleteMessage")
	proto.RegisterType((*NicknamePokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.NicknamePokemonMessage")
	proto.RegisterType((*RecycleInventoryItemMessage)(nil), "SUNProtos.Networking.Requests.Messages.RecycleInventoryItemMessage")
	proto.RegisterType((*RegisterBackgroundDeviceMessage)(nil), "SUNProtos.Networking.Requests.Messages.RegisterBackgroundDeviceMessage")
	proto.RegisterType((*ReleasePokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.ReleasePokemonMessage")
	proto.RegisterType((*SetAvatarItemAsViewedMessage)(nil), "SUNProtos.Networking.Requests.Messages.SetAvatarItemAsViewedMessage")
	proto.RegisterType((*SetAvatarMessage)(nil), "SUNProtos.Networking.Requests.Messages.SetAvatarMessage")
	proto.RegisterType((*SetBuddyPokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.SetBuddyPokemonMessage")
	proto.RegisterType((*SetContactSettingsMessage)(nil), "SUNProtos.Networking.Requests.Messages.SetContactSettingsMessage")
	proto.RegisterType((*SetFavoritePokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.SetFavoritePokemonMessage")
	proto.RegisterType((*SetPlayerTeamMessage)(nil), "SUNProtos.Networking.Requests.Messages.SetPlayerTeamMessage")
	proto.RegisterType((*SfidaActionLogMessage)(nil), "SUNProtos.Networking.Requests.Messages.SfidaActionLogMessage")
	proto.RegisterType((*StartGymBattleMessage)(nil), "SUNProtos.Networking.Requests.Messages.StartGymBattleMessage")
	proto.RegisterType((*UpdateNotificationMessage)(nil), "SUNProtos.Networking.Requests.Messages.UpdateNotificationMessage")
	proto.RegisterType((*UpgradePokemonMessage)(nil), "SUNProtos.Networking.Requests.Messages.UpgradePokemonMessage")
	proto.RegisterType((*UseIncenseMessage)(nil), "SUNProtos.Networking.Requests.Messages.UseIncenseMessage")
	proto.RegisterType((*UseItemCaptureMessage)(nil), "SUNProtos.Networking.Requests.Messages.UseItemCaptureMessage")
	proto.RegisterType((*UseItemEggIncubatorMessage)(nil), "SUNProtos.Networking.Requests.Messages.UseItemEggIncubatorMessage")
	proto.RegisterType((*UseItemEncounterMessage)(nil), "SUNProtos.Networking.Requests.Messages.UseItemEncounterMessage")
	proto.RegisterType((*UseItemGymMessage)(nil), "SUNProtos.Networking.Requests.Messages.UseItemGymMessage")
	proto.RegisterType((*UseItemPotionMessage)(nil), "SUNProtos.Networking.Requests.Messages.UseItemPotionMessage")
	proto.RegisterType((*UseItemReviveMessage)(nil), "SUNProtos.Networking.Requests.Messages.UseItemReviveMessage")
	proto.RegisterType((*UseItemXpBoostMessage)(nil), "SUNProtos.Networking.Requests.Messages.UseItemXpBoostMessage")
	proto.RegisterType((*VerifyChallengeMessage)(nil), "SUNProtos.Networking.Requests.Messages.VerifyChallengeMessage")
}

func init() { proto.RegisterFile("networking_requests_messages.proto", fileDescriptor21) }

var fileDescriptor21 = []byte{
	// 2402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x59, 0xcf, 0x77, 0x23, 0x47,
	0xf1, 0xff, 0x8e, 0x6c, 0xcb, 0x72, 0xd9, 0xd6, 0xda, 0x63, 0x6b, 0xed, 0xf5, 0xe6, 0x4b, 0x9c,
	0x59, 0x92, 0x38, 0x3c, 0x22, 0x82, 0x03, 0xe1, 0xc7, 0xcb, 0xc5, 0x96, 0xbd, 0x5e, 0xf1, 0xec,
	0x8d, 0x18, 0xed, 0x26, 0x79, 0xfc, 0x1a, 0xda, 0x33, 0x25, 0xb9, 0xa3, 0x99, 0xe9, 0xc9, 0x74,
	0xcb, 0x8b, 0xf6, 0xc8, 0xff, 0xc0, 0x09, 0xde, 0xe3, 0xc6, 0x15, 0xae, 0x9c, 0xf8, 0x07, 0x72,
	0xe2, 0xc8, 0x89, 0x63, 0x8e, 0x5c, 0xb8, 0xf3, 0xfa, 0xc7, 0xb4, 0xc6, 0x92, 0x77, 0xad, 0xcd,
	0xb2, 0x3c, 0x1e, 0x17, 0x7b, 0xba, 0xaa, 0xba, 0xba, 0xaa, 0xba, 0xea, 0xd3, 0xd5, 0x2d, 0xf0,
	0x52, 0x14, 0x4f, 0x58, 0x3e, 0xa0, 0x69, 0x3f, 0xc8, 0xf1, 0xf3, 0x21, 0x72, 0xc1, 0x83, 0x04,
	0x39, 0x27, 0x7d, 0xe4, 0xcd, 0x2c, 0x67, 0x82, 0xb9, 0x6f, 0x75, 0x1f, 0x3f, 0xec, 0xc8, 0x2f,
	0xde, 0x7c, 0x68, 0xa5, 0x9b, 0xbe, 0x91, 0x6e, 0x9e, 0x19, 0xe9, 0x9d, 0x4d, 0x9a, 0x5e, 0x62,
	0x2a, 0x58, 0x3e, 0x0a, 0xa8, 0xc0, 0x44, 0xcf, 0xde, 0x59, 0x8f, 0x88, 0x20, 0xc1, 0x39, 0x11,
	0x22, 0x46, 0x43, 0x5a, 0xc6, 0x74, 0x98, 0xf0, 0x2b, 0xfc, 0x2c, 0x26, 0x23, 0xcc, 0x35, 0xc9,
	0xfb, 0xc2, 0x81, 0xdb, 0x07, 0x51, 0x74, 0x9f, 0xe5, 0xe2, 0x8c, 0x45, 0xb4, 0x47, 0x31, 0x37,
	0x8b, 0xb8, 0xc7, 0xb0, 0x9a, 0x18, 0x52, 0x20, 0x46, 0x19, 0x6e, 0x3b, 0xbb, 0xce, 0x5e, 0x7d,
	0x7f, 0xb7, 0x39, 0xb6, 0xb1, 0x5d, 0x58, 0xd1, 0x6c, 0x4b, 0x2b, 0xe4, 0x9f, 0x76, 0xe4, 0xaf,
	0x14, 0xd3, 0x1e, 0x8d, 0x32, 0x74, 0xb7, 0x60, 0xb1, 0xc7, 0x72, 0x11, 0xd0, 0x68, 0xbb, 0xb2,
	0xeb, 0xec, 0x2d, 0xf9, 0x55, 0x39, 0x6c, 0x47, 0xee, 0xdb, 0x70, 0x4b, 0x9b, 0x12, 0xc4, 0x44,
	0x50, 0x31, 0x8c, 0x70, 0x7b, 0x6e, 0xd7, 0xd9, 0x73, 0xfc, 0xba, 0x26, 0x9f, 0x1a, 0xaa, 0xfb,
	0x0e, 0xac, 0x15, 0x82, 0x2c, 0xed, 0x6b, 0xc9, 0x79, 0x25, 0x69, 0x14, 0x9c, 0x16, 0x64, 0xef,
	0x2f, 0x15, 0x58, 0x3b, 0x10, 0x82, 0x84, 0x83, 0x93, 0x51, 0x52, 0x38, 0xd2, 0x80, 0x6a, 0x7f,
	0x94, 0x48, 0x03, 0x1c, 0x65, 0xc0, 0x42, 0x7f, 0x94, 0xb4, 0x23, 0xf7, 0x2e, 0x2c, 0xe9, 0x50,
	0x8d, 0x4d, 0xab, 0x69, 0x42, 0x3b, 0x72, 0x7f, 0x04, 0x75, 0xa2, 0xf4, 0x04, 0x24, 0x14, 0x94,
	0xa5, 0x7c, 0x7b, 0x6e, 0x77, 0x6e, 0x6f, 0x79, 0xff, 0x5e, 0xc9, 0xfb, 0x23, 0x22, 0x48, 0xf3,
	0x50, 0x47, 0x5b, 0xff, 0x3b, 0x50, 0xb2, 0xfe, 0xaa, 0x9e, 0xaa, 0x47, 0xdc, 0xfd, 0x04, 0x1a,
	0x31, 0xe1, 0x22, 0xc8, 0x51, 0xe4, 0x14, 0x2f, 0x31, 0x32, 0x3a, 0x95, 0x13, 0x33, 0xaa, 0xdc,
	0x90, 0x1a, 0xfc, 0x42, 0x81, 0x26, 0x5e, 0x17, 0xc1, 0x85, 0x99, 0x23, 0x58, 0xbd, 0x3e, 0x82,
	0x7f, 0xad, 0xc0, 0x46, 0x8b, 0x88, 0xf0, 0xa2, 0xc3, 0x06, 0x98, 0xb0, 0xb4, 0x08, 0xe2, 0x1b,
	0xb0, 0x82, 0x69, 0xc8, 0x86, 0xa9, 0xc0, 0xbc, 0x08, 0x65, 0xd5, 0x5f, 0xb6, 0xb4, 0x76, 0xe4,
	0x7e, 0x08, 0xb5, 0x8c, 0x0d, 0xf0, 0x9c, 0xc4, 0xb1, 0x8a, 0xe7, 0x2c, 0xb9, 0x62, 0x67, 0xb8,
	0x1f, 0xc0, 0x56, 0xca, 0xf2, 0x84, 0xc4, 0xf4, 0x29, 0x46, 0x32, 0x56, 0x34, 0x8c, 0x31, 0xe0,
	0xf4, 0x69, 0x91, 0x16, 0x8d, 0x31, 0xdb, 0xd7, 0xdc, 0x2e, 0x7d, 0x8a, 0xee, 0xd7, 0xa1, 0xce,
	0x33, 0xf2, 0x24, 0x0d, 0x32, 0x46, 0x53, 0x95, 0x66, 0xf3, 0x6a, 0x2f, 0x57, 0x14, 0xb5, 0x23,
	0x89, 0xed, 0xc8, 0x7d, 0x1d, 0x96, 0x2f, 0xa8, 0x08, 0x32, 0xed, 0x94, 0x0a, 0x53, 0xcd, 0x87,
	0x0b, 0x2a, 0x8c, 0x9b, 0xee, 0x3d, 0x58, 0xe5, 0x19, 0x4d, 0x83, 0x22, 0x77, 0x4d, 0x7c, 0x56,
	0x24, 0xb1, 0xa8, 0x8c, 0x09, 0x1b, 0xb5, 0x42, 0x4e, 0xd5, 0x5e, 0x2e, 0x4e, 0xda, 0xf8, 0x40,
	0xea, 0xd6, 0x4c, 0xef, 0x2e, 0xdc, 0x69, 0x5d, 0x60, 0x38, 0x38, 0x78, 0x42, 0xf2, 0x08, 0xa3,
	0x43, 0x12, 0xf5, 0x91, 0x9b, 0xc8, 0x7a, 0x1f, 0x42, 0x43, 0x31, 0x5b, 0x17, 0x24, 0x8e, 0x31,
	0xed, 0x63, 0x11, 0xf2, 0x7b, 0xb0, 0x1a, 0xe1, 0xf9, 0xd0, 0xa2, 0x85, 0x8a, 0x79, 0xcd, 0x5f,
	0x51, 0x44, 0x83, 0x09, 0xde, 0x03, 0xd8, 0x6c, 0xc5, 0x84, 0x26, 0x2d, 0x16, 0x61, 0x4a, 0x12,
	0x3b, 0x79, 0x07, 0x6a, 0xa1, 0x21, 0x99, 0xb4, 0xb7, 0x63, 0x77, 0x13, 0x16, 0x7a, 0x2c, 0x0f,
	0x51, 0xed, 0x52, 0xcd, 0xd7, 0x03, 0x6f, 0x07, 0xb6, 0x5b, 0x2c, 0x8e, 0x31, 0x14, 0x47, 0x84,
	0xc6, 0xa3, 0x43, 0x96, 0x0e, 0xad, 0x8d, 0x1e, 0xec, 0x96, 0x79, 0x47, 0xd8, 0xc3, 0x34, 0xc2,
	0xfc, 0x8a, 0xcc, 0x1f, 0x1c, 0xd8, 0x3c, 0xa2, 0x7c, 0x70, 0x5c, 0xa4, 0xc4, 0xf3, 0x52, 0x67,
	0xfe, 0x6a, 0xea, 0xfc, 0x47, 0x41, 0xe2, 0xd7, 0x0e, 0xbc, 0x76, 0xc4, 0x9e, 0xa4, 0x31, 0x23,
	0x91, 0x4c, 0xc3, 0x47, 0x98, 0x64, 0x31, 0x11, 0x76, 0x47, 0x64, 0xec, 0x32, 0xd2, 0xa7, 0x29,
	0x11, 0x68, 0x62, 0x6e, 0xc7, 0x32, 0x91, 0x32, 0xd2, 0xc7, 0x80, 0xf5, 0x7a, 0x1c, 0x85, 0xb2,
	0x76, 0xc1, 0x07, 0x49, 0xfa, 0x48, 0x51, 0xdc, 0x37, 0xa1, 0xae, 0x04, 0x04, 0x4d, 0x90, 0x0b,
	0x92, 0x64, 0xca, 0xe0, 0x79, 0x7f, 0x55, 0x52, 0x1f, 0x15, 0x44, 0xef, 0x4b, 0x07, 0xbc, 0xc2,
	0x08, 0x1f, 0x13, 0x26, 0xb0, 0xc5, 0xd2, 0x1e, 0xed, 0x7f, 0x8c, 0x39, 0xa7, 0xe3, 0xb2, 0xfb,
	0x2e, 0xd4, 0xa4, 0x6d, 0x3d, 0x96, 0x27, 0x06, 0x7f, 0xef, 0x94, 0x6a, 0xea, 0x58, 0x81, 0x7b,
	0xc7, 0x08, 0xf8, 0x56, 0xd4, 0xfd, 0x16, 0x6c, 0x44, 0x78, 0x49, 0x43, 0x0c, 0x12, 0x92, 0x0e,
	0x7b, 0x24, 0x14, 0xc3, 0x1c, 0x73, 0x13, 0x5b, 0x57, 0xb3, 0xce, 0x4a, 0x1c, 0xb9, 0x47, 0xc5,
	0x04, 0x16, 0x61, 0xac, 0x6c, 0x5e, 0xf2, 0x97, 0x8d, 0xa4, 0x24, 0xb9, 0xb7, 0xa1, 0x1a, 0xb3,
	0x90, 0xc4, 0x68, 0x0a, 0xcc, 0x8c, 0x64, 0x44, 0x48, 0x96, 0x05, 0x97, 0xda, 0x70, 0x55, 0x5a,
	0xab, 0x3e, 0x90, 0x2c, 0x33, 0xae, 0x78, 0xef, 0xc2, 0x56, 0xe1, 0x69, 0x17, 0x85, 0xa0, 0x69,
	0xdf, 0x46, 0xda, 0x85, 0xf9, 0x0b, 0xc2, 0x2f, 0x4c, 0x86, 0xaa, 0x6f, 0x6f, 0x15, 0x96, 0x8f,
	0xc3, 0x0b, 0x56, 0xa4, 0xd5, 0x1f, 0x1d, 0x58, 0x9b, 0x29, 0xa5, 0x26, 0xd0, 0x68, 0x1a, 0x17,
	0x2a, 0xd7, 0xe0, 0xc2, 0xab, 0xc8, 0xaf, 0x9f, 0xc3, 0xae, 0x35, 0xf8, 0xd1, 0x50, 0xb0, 0x9c,
	0x92, 0xb8, 0xc5, 0x92, 0x2c, 0x46, 0x61, 0xcb, 0xf3, 0x07, 0x00, 0x06, 0x8b, 0x0a, 0xf3, 0xeb,
	0xfb, 0x3b, 0xd3, 0x3b, 0xab, 0x45, 0xda, 0x91, 0xbf, 0x94, 0x15, 0x9f, 0xde, 0x43, 0x58, 0x3f,
	0xfe, 0x7c, 0x48, 0x33, 0x85, 0x22, 0x25, 0x7d, 0xe7, 0x72, 0x5c, 0x3e, 0xa9, 0xa7, 0xf5, 0xa9,
	0x29, 0xf2, 0x54, 0xf6, 0x97, 0xce, 0x8b, 0x4f, 0xef, 0x37, 0x0e, 0x6c, 0x1e, 0x5f, 0xb2, 0xf8,
	0x12, 0x27, 0x20, 0xff, 0xff, 0xa7, 0x6c, 0xac, 0x96, 0xec, 0x70, 0x7f, 0x01, 0x3b, 0x78, 0xc9,
	0xe2, 0xa1, 0x44, 0x38, 0xd5, 0x85, 0x28, 0x9c, 0xa2, 0x39, 0x26, 0x98, 0x8a, 0x99, 0x0f, 0x80,
	0x6d, 0xab, 0x43, 0x12, 0xfc, 0xb1, 0x06, 0x89, 0x27, 0xdb, 0xb2, 0x2f, 0x39, 0xc2, 0x2c, 0x66,
	0xa3, 0x09, 0xdb, 0x4a, 0x80, 0xe1, 0x5c, 0x01, 0x8c, 0xab, 0x46, 0x57, 0x26, 0x8d, 0x7e, 0x15,
	0xfb, 0xdd, 0x07, 0x57, 0xdb, 0x29, 0x08, 0x8d, 0xf9, 0x8d, 0x16, 0xee, 0x40, 0xcd, 0xae, 0x5d,
	0x51, 0x1a, 0xed, 0xd8, 0x7d, 0x0d, 0x96, 0xc6, 0xcb, 0x69, 0xc3, 0xc6, 0x04, 0x1b, 0x11, 0x1f,
	0x43, 0x12, 0xc7, 0xff, 0xc5, 0x11, 0xf9, 0xc2, 0x81, 0x75, 0x69, 0x68, 0x17, 0x49, 0x1e, 0x5e,
	0xdc, 0x68, 0xe1, 0x35, 0x26, 0x54, 0x66, 0x36, 0x61, 0xee, 0x5a, 0x13, 0xe4, 0xe1, 0xa9, 0x16,
	0xb3, 0x1a, 0xb5, 0xa9, 0x2b, 0x92, 0x68, 0xf5, 0xbd, 0x09, 0x75, 0x2d, 0x64, 0xb5, 0xe9, 0xfe,
	0x49, 0x4d, 0xbd, 0xd2, 0x55, 0x36, 0x4e, 0x50, 0x1c, 0x70, 0x8e, 0xe2, 0x88, 0xf6, 0x91, 0x8b,
	0xff, 0x21, 0x78, 0xbe, 0x72, 0xda, 0x55, 0x9f, 0x7f, 0xda, 0x2d, 0xce, 0x70, 0xda, 0xd5, 0xae,
	0x3b, 0xed, 0xb6, 0x54, 0x00, 0x0f, 0x87, 0x51, 0x34, 0xfa, 0x84, 0xc4, 0x03, 0x8c, 0x0a, 0x74,
	0x7f, 0x1f, 0x6e, 0x9f, 0xa0, 0x28, 0x8e, 0x87, 0xc7, 0xf9, 0xb8, 0x7e, 0xee, 0x40, 0x8d, 0xc8,
	0x80, 0xeb, 0x74, 0x99, 0xdb, 0x5b, 0xf2, 0x17, 0xd5, 0xb8, 0x1d, 0x79, 0xff, 0x70, 0x60, 0xf3,
	0x04, 0xc5, 0xc9, 0x28, 0x99, 0xa8, 0xb9, 0x67, 0x74, 0xfa, 0xaf, 0x22, 0xbf, 0xde, 0x80, 0x15,
	0xb9, 0xd4, 0x44, 0x7a, 0x2d, 0xf7, 0x47, 0x89, 0xd5, 0x76, 0x0f, 0x56, 0x95, 0xc8, 0x44, 0x72,
	0xc9, 0x79, 0x63, 0x3d, 0x6f, 0x42, 0x3d, 0x8c, 0x29, 0xa6, 0xc2, 0xee, 0x50, 0x55, 0x99, 0xbe,
	0xaa, 0xa9, 0xc5, 0x19, 0xaa, 0x03, 0xf8, 0x40, 0x36, 0xe6, 0x18, 0x1d, 0xf7, 0xed, 0x09, 0xea,
	0xad, 0xc3, 0xad, 0x13, 0x14, 0xed, 0xf4, 0x9c, 0xfd, 0xaa, 0x20, 0xa5, 0xb0, 0xad, 0x48, 0x21,
	0xa6, 0x7c, 0x12, 0xd3, 0xaf, 0x09, 0x85, 0x33, 0x73, 0x28, 0x2a, 0xcf, 0xc2, 0xbf, 0x0d, 0xb5,
	0x9e, 0x81, 0xf7, 0x62, 0xa9, 0x6f, 0xc0, 0xba, 0xba, 0xf6, 0xd8, 0xd4, 0x08, 0x12, 0xae, 0x16,
	0x9b, 0xf3, 0x6f, 0x49, 0x86, 0xcd, 0x8e, 0x33, 0x2e, 0x0f, 0x6b, 0x75, 0x82, 0x9c, 0x23, 0xa6,
	0x01, 0x47, 0x4c, 0x4d, 0x63, 0xb5, 0x22, 0xa9, 0x87, 0x88, 0x69, 0x17, 0x31, 0xf5, 0x7e, 0xaf,
	0xf7, 0xfd, 0x8c, 0x64, 0x1f, 0x9d, 0x7f, 0x86, 0xa1, 0xb0, 0xfb, 0x7e, 0x17, 0x16, 0x43, 0x8c,
	0xe3, 0x22, 0x55, 0xe6, 0x0f, 0x2b, 0x6b, 0x8e, 0x5f, 0x95, 0xa4, 0x76, 0xe4, 0xbe, 0x07, 0x2e,
	0xa7, 0x69, 0x88, 0x57, 0x0d, 0xa9, 0xec, 0xce, 0xed, 0xcd, 0x29, 0xb9, 0x35, 0xc5, 0x2d, 0x5b,
	0x53, 0x46, 0xe8, 0xb9, 0xe7, 0x21, 0xf4, 0xfc, 0x24, 0x42, 0xff, 0xdd, 0x81, 0xb5, 0x13, 0x14,
	0x1d, 0x15, 0xa1, 0xc2, 0xba, 0xcf, 0x60, 0xd5, 0x86, 0x52, 0x15, 0xa8, 0xa3, 0xee, 0x7d, 0xc7,
	0xcd, 0xd9, 0x2e, 0xfb, 0xcd, 0x49, 0x85, 0xcd, 0x8e, 0xd9, 0x00, 0xa9, 0xcc, 0x5f, 0xc9, 0x4a,
	0xa3, 0x9d, 0x5f, 0xc2, 0x4a, 0x99, 0xeb, 0x6e, 0xc3, 0xa2, 0xea, 0x44, 0xf2, 0x91, 0x29, 0x89,
	0x62, 0xa8, 0x9d, 0x4c, 0xfb, 0x43, 0xd2, 0xc7, 0xe2, 0xf6, 0x5b, 0x8c, 0x25, 0x4f, 0x06, 0xeb,
	0x29, 0x4b, 0xd1, 0x40, 0x8d, 0x1d, 0x7b, 0x3f, 0x84, 0x2d, 0x6b, 0x50, 0x27, 0x67, 0x3d, 0x1a,
	0xdb, 0x26, 0x44, 0xa2, 0x85, 0x76, 0xb4, 0x74, 0xed, 0x00, 0x4d, 0x7a, 0x48, 0x12, 0xf4, 0x06,
	0xb0, 0x65, 0xd2, 0xf2, 0xab, 0x5c, 0x12, 0xde, 0x05, 0x77, 0x2c, 0x22, 0x43, 0xa9, 0x2e, 0x5e,
	0xda, 0xf6, 0x75, 0xcb, 0x39, 0x35, 0x0c, 0xef, 0x5d, 0x68, 0x9c, 0xe2, 0x25, 0xc6, 0x8f, 0x33,
	0x1f, 0xe5, 0xbd, 0xcb, 0x66, 0xcb, 0x26, 0x2c, 0xc4, 0x92, 0xa1, 0xd6, 0x58, 0xf0, 0xf5, 0xc0,
	0xfb, 0xa7, 0x03, 0xaf, 0x9f, 0x52, 0x2e, 0x0e, 0x2e, 0x89, 0x20, 0x79, 0x6b, 0xc8, 0x05, 0x4b,
	0xe8, 0x53, 0xa5, 0xca, 0xce, 0x7c, 0x00, 0xcb, 0x44, 0xb1, 0xcb, 0x6d, 0xd6, 0xdb, 0x93, 0xf7,
	0x77, 0x1d, 0x1b, 0xf3, 0x4f, 0xab, 0x53, 0x3d, 0x17, 0x10, 0xfb, 0xed, 0xbe, 0x03, 0xf3, 0x3c,
	0x66, 0x42, 0xa5, 0x61, 0x7d, 0xbf, 0x31, 0x75, 0x68, 0x74, 0x63, 0x26, 0x7c, 0x25, 0xe2, 0x7e,
	0x1b, 0x16, 0x7b, 0x34, 0x16, 0x98, 0xeb, 0x37, 0x88, 0xfa, 0xfe, 0xd6, 0x94, 0xf4, 0x7d, 0xc5,
	0xf7, 0x0b, 0x39, 0xe9, 0x21, 0x17, 0x24, 0x17, 0x2a, 0x41, 0x17, 0x7c, 0x3d, 0x50, 0x7e, 0xd3,
	0x84, 0x0a, 0x85, 0x43, 0xd2, 0x6f, 0x39, 0xf0, 0xfe, 0xe6, 0xc0, 0xdd, 0x33, 0x92, 0x0f, 0x9e,
	0xd5, 0xa9, 0x7e, 0x04, 0x1b, 0xc2, 0xb0, 0x78, 0x10, 0x1a, 0xa6, 0xae, 0xb3, 0xfa, 0xfe, 0xd7,
	0xa6, 0x4c, 0x29, 0xd4, 0x74, 0x05, 0x11, 0xe8, 0xbb, 0x76, 0x6a, 0xa1, 0x36, 0x72, 0xf7, 0xa1,
	0xc1, 0x31, 0x8d, 0x82, 0x84, 0xe4, 0x03, 0x94, 0xb7, 0x81, 0x00, 0x13, 0x09, 0xe2, 0xe6, 0x36,
	0xba, 0x21, 0x99, 0x67, 0x05, 0xef, 0x58, 0xb1, 0xe4, 0xc5, 0x5b, 0xcd, 0xc9, 0x86, 0xfc, 0x22,
	0x48, 0x99, 0xa0, 0x3d, 0xaa, 0x77, 0x99, 0xab, 0xfc, 0xac, 0xf9, 0x4a, 0x65, 0x67, 0xc8, 0x2f,
	0x1e, 0x96, 0x99, 0x5e, 0x17, 0x6e, 0x3f, 0xa4, 0xe1, 0x40, 0xa6, 0xe3, 0x8b, 0x35, 0xb7, 0x3b,
	0x50, 0x4b, 0xcd, 0xc4, 0xa2, 0x3a, 0x8a, 0xb1, 0x97, 0xc2, 0x5d, 0x1f, 0xc3, 0x51, 0x18, 0xa3,
	0xc5, 0x3c, 0xd9, 0xbb, 0x8e, 0x5b, 0xf1, 0x45, 0x85, 0x65, 0xb6, 0xaf, 0xbf, 0xb9, 0x09, 0xae,
	0x52, 0xf5, 0x5f, 0xee, 0x90, 0xca, 0x62, 0x83, 0x7e, 0x7a, 0xe0, 0x05, 0xf0, 0xba, 0x8f, 0x7d,
	0xca, 0x05, 0xe6, 0x87, 0x24, 0x1c, 0xf4, 0x73, 0x36, 0x4c, 0xa3, 0x23, 0x7d, 0xf4, 0x8f, 0x2b,
	0xcf, 0xf4, 0x07, 0x36, 0x31, 0x97, 0x7c, 0xd0, 0x24, 0x95, 0x6f, 0x77, 0x61, 0xc9, 0x08, 0x8c,
	0x1f, 0xbb, 0x34, 0xa1, 0x1d, 0x79, 0x9f, 0x40, 0xc3, 0xc7, 0x18, 0x09, 0x7f, 0xc1, 0x20, 0xc9,
	0x7a, 0xb7, 0x6c, 0x0d, 0xa9, 0x55, 0x1f, 0x2c, 0x9f, 0x7b, 0xa7, 0xf0, 0x5a, 0x17, 0x4d, 0x45,
	0x49, 0x57, 0x0f, 0xf8, 0xc7, 0x14, 0x9f, 0xd8, 0xd3, 0xdf, 0xfd, 0x26, 0xb8, 0x45, 0x3d, 0x99,
	0x3b, 0xf8, 0xf8, 0xb4, 0x5f, 0x33, 0xd5, 0x62, 0x18, 0xed, 0xc8, 0xfb, 0x19, 0xac, 0x59, 0x6d,
	0xe3, 0x8a, 0x2c, 0xb0, 0x55, 0x8b, 0x2b, 0xdf, 0xae, 0x79, 0x53, 0xbb, 0xa6, 0x26, 0x0b, 0xe4,
	0xd4, 0x23, 0xef, 0x7b, 0x70, 0xbb, 0x6b, 0x5a, 0x94, 0x17, 0x8a, 0x82, 0x97, 0xc2, 0x9d, 0x2e,
	0x8a, 0x16, 0x4b, 0x05, 0x09, 0xc5, 0xe4, 0x05, 0xf7, 0xc7, 0xb0, 0x16, 0x6a, 0x4e, 0xc0, 0x0d,
	0xcb, 0xc0, 0xff, 0x5b, 0xcf, 0x30, 0x71, 0x42, 0x91, 0x7f, 0x2b, 0xbc, 0x4a, 0xf0, 0x7e, 0xaa,
	0xd6, 0xbb, 0x4f, 0x2e, 0x59, 0x4e, 0xc5, 0xcd, 0x3b, 0x36, 0x37, 0xb1, 0x63, 0x94, 0x07, 0x3d,
	0x33, 0xd7, 0x54, 0x1c, 0x50, 0x5e, 0x68, 0xf3, 0xee, 0xc3, 0x66, 0xb7, 0x40, 0xf7, 0x47, 0x48,
	0x6c, 0x52, 0x37, 0x61, 0x5e, 0x20, 0x49, 0x9e, 0x79, 0xb3, 0x94, 0xb2, 0x2d, 0x16, 0xb3, 0xdc,
	0x57, 0x72, 0xb2, 0x5f, 0xe9, 0xf6, 0x68, 0x44, 0xf4, 0x4b, 0xe5, 0x29, 0xeb, 0x17, 0xcd, 0xc9,
	0x97, 0x0e, 0x34, 0xba, 0x12, 0x8e, 0x4e, 0x46, 0x89, 0x7e, 0xe1, 0xbc, 0xa1, 0x79, 0xdb, 0x87,
	0x86, 0x7e, 0x4e, 0x95, 0x48, 0x31, 0x9d, 0x6e, 0x1b, 0x96, 0x69, 0x2f, 0xcb, 0xdc, 0x7d, 0x0f,
	0x36, 0x23, 0xf5, 0x44, 0x75, 0x75, 0x8e, 0xc2, 0x8a, 0xaa, 0x6c, 0xb0, 0x0d, 0xaf, 0xf3, 0xbc,
	0x5b, 0xd0, 0xfc, 0xcc, 0x7d, 0xd1, 0xc2, 0xf5, 0x7d, 0xd1, 0x9f, 0x1c, 0xb8, 0xf3, 0x38, 0x8b,
	0x88, 0xc0, 0x32, 0x28, 0x15, 0xee, 0xbe, 0x03, 0x6b, 0x65, 0x20, 0x53, 0x2e, 0xe9, 0xcc, 0xbf,
	0x55, 0xa6, 0x4b, 0x77, 0x9a, 0xb0, 0x11, 0xe6, 0x28, 0xab, 0x63, 0xba, 0x85, 0xf1, 0xd7, 0x35,
	0xab, 0xdc, 0xbf, 0x7c, 0x5f, 0xc1, 0xbf, 0xd0, 0x67, 0x77, 0x7d, 0xdf, 0x9b, 0xda, 0xad, 0xb2,
	0x3d, 0x1a, 0xa8, 0xf5, 0x04, 0xef, 0x03, 0x68, 0x3c, 0xce, 0xfa, 0x39, 0x89, 0x5e, 0x0c, 0x09,
	0xbc, 0x4f, 0x61, 0xfd, 0x31, 0x47, 0x73, 0xb6, 0x17, 0x73, 0x5a, 0xb0, 0x42, 0x35, 0xe5, 0xc5,
	0x7e, 0x3f, 0x58, 0x36, 0xb3, 0xd4, 0xeb, 0xc4, 0x6f, 0x1d, 0x68, 0x48, 0xd5, 0x02, 0x93, 0x16,
	0xc9, 0xe4, 0x6d, 0xe8, 0xdf, 0x80, 0xb3, 0x93, 0xcd, 0x46, 0x65, 0x96, 0xe7, 0xa3, 0xb9, 0xe9,
	0xe7, 0x23, 0xef, 0x11, 0xec, 0x18, 0xe3, 0x8e, 0xfb, 0xfd, 0x76, 0x1a, 0x0e, 0xcf, 0x89, 0x60,
	0x79, 0xe9, 0xc2, 0x5b, 0xb6, 0x70, 0xc9, 0xae, 0x3f, 0x7d, 0x25, 0x9f, 0x2f, 0x47, 0xf3, 0x77,
	0x0e, 0x6c, 0x15, 0x6a, 0x27, 0xfb, 0xa4, 0xef, 0xc0, 0xbc, 0x54, 0x32, 0xb3, 0xcb, 0x4a, 0x7a,
	0x16, 0x87, 0xf7, 0x60, 0xad, 0xec, 0x70, 0x7f, 0x68, 0x5d, 0xae, 0x8f, 0x5d, 0x3e, 0x19, 0xd2,
	0xc8, 0xfb, 0xb3, 0xa3, 0x77, 0x5b, 0x60, 0x52, 0xfa, 0x95, 0xe5, 0x25, 0xb6, 0x63, 0x5c, 0xf9,
	0x95, 0x1b, 0xae, 0x6d, 0x2f, 0xfd, 0x32, 0x91, 0xc1, 0xa6, 0x31, 0xbd, 0xc3, 0xca, 0xd5, 0xf8,
	0x12, 0xd6, 0x3f, 0xff, 0x7d, 0xa5, 0xb4, 0xa2, 0x8f, 0x97, 0xf4, 0x12, 0x5f, 0xfd, 0x8a, 0xbe,
	0xad, 0x98, 0x4f, 0xb3, 0x43, 0xc6, 0xc6, 0xaf, 0x15, 0x5f, 0x7d, 0x49, 0xaf, 0x09, 0xb7, 0x3f,
	0xc6, 0x9c, 0xf6, 0x46, 0x53, 0xbf, 0x52, 0x6c, 0xc2, 0x82, 0x60, 0x03, 0x4c, 0x0b, 0xd4, 0x56,
	0x83, 0xc3, 0xda, 0x4f, 0xaa, 0xea, 0x07, 0x46, 0xde, 0xf9, 0xbf, 0x8e, 0xd3, 0xa9, 0x74, 0xe6,
	0xce, 0xf5, 0xf8, 0xfd, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x01, 0xfa, 0xad, 0xe1, 0x07, 0x1d,
	0x00, 0x00,
}
