// Code generated by protoc-gen-go.
// source: networking_platform_requests.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BuyItemAndroidRequest struct {
	BuyItemIntent string `protobuf:"bytes,1,opt,name=buy_item_intent,json=buyItemIntent" json:"buy_item_intent,omitempty"`
}

func (m *BuyItemAndroidRequest) Reset()                    { *m = BuyItemAndroidRequest{} }
func (m *BuyItemAndroidRequest) String() string            { return proto.CompactTextString(m) }
func (*BuyItemAndroidRequest) ProtoMessage()               {}
func (*BuyItemAndroidRequest) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{0} }

func (m *BuyItemAndroidRequest) GetBuyItemIntent() string {
	if m != nil {
		return m.BuyItemIntent
	}
	return ""
}

type BuyItemPokeCoinsRequest struct {
	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
}

func (m *BuyItemPokeCoinsRequest) Reset()                    { *m = BuyItemPokeCoinsRequest{} }
func (m *BuyItemPokeCoinsRequest) String() string            { return proto.CompactTextString(m) }
func (*BuyItemPokeCoinsRequest) ProtoMessage()               {}
func (*BuyItemPokeCoinsRequest) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{1} }

func (m *BuyItemPokeCoinsRequest) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type SendEncryptedSignatureRequest struct {
	EncryptedSignature []byte `protobuf:"bytes,1,opt,name=encrypted_signature,json=encryptedSignature,proto3" json:"encrypted_signature,omitempty"`
}

func (m *SendEncryptedSignatureRequest) Reset()                    { *m = SendEncryptedSignatureRequest{} }
func (m *SendEncryptedSignatureRequest) String() string            { return proto.CompactTextString(m) }
func (*SendEncryptedSignatureRequest) ProtoMessage()               {}
func (*SendEncryptedSignatureRequest) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{2} }

func (m *SendEncryptedSignatureRequest) GetEncryptedSignature() []byte {
	if m != nil {
		return m.EncryptedSignature
	}
	return nil
}

type UnknownPtr8Request struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *UnknownPtr8Request) Reset()                    { *m = UnknownPtr8Request{} }
func (m *UnknownPtr8Request) String() string            { return proto.CompactTextString(m) }
func (*UnknownPtr8Request) ProtoMessage()               {}
func (*UnknownPtr8Request) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{3} }

func (m *UnknownPtr8Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BuyItemAndroidRequest)(nil), "SUNProtos.Networking.Platform.Requests.BuyItemAndroidRequest")
	proto.RegisterType((*BuyItemPokeCoinsRequest)(nil), "SUNProtos.Networking.Platform.Requests.BuyItemPokeCoinsRequest")
	proto.RegisterType((*SendEncryptedSignatureRequest)(nil), "SUNProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest")
	proto.RegisterType((*UnknownPtr8Request)(nil), "SUNProtos.Networking.Platform.Requests.UnknownPtr8Request")
}

func init() { proto.RegisterFile("networking_platform_requests.proto", fileDescriptor18) }

var fileDescriptor18 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0xb9, 0xe5, 0x4e, 0x1f, 0x8a, 0x50, 0x91, 0xbb, 0x45, 0x90, 0x0c, 0x87, 0x53, 0x04,
	0x5d, 0xdc, 0xc4, 0x13, 0x87, 0x2e, 0x47, 0x68, 0xb9, 0xc5, 0x25, 0xb4, 0xe6, 0x59, 0x42, 0xed,
	0x4b, 0x4d, 0x5e, 0x39, 0xfa, 0xdf, 0xcb, 0xb5, 0x89, 0x8b, 0x53, 0xf2, 0xf2, 0x7d, 0xbf, 0x1f,
	0xe1, 0x81, 0x20, 0xe4, 0xa3, 0xf3, 0xad, 0xa5, 0x46, 0xf7, 0xdf, 0x15, 0x7f, 0x39, 0xdf, 0x69,
	0x8f, 0x3f, 0x03, 0x06, 0x0e, 0xb2, 0xf7, 0x8e, 0x5d, 0xb6, 0x2d, 0x0f, 0x7b, 0x75, 0xba, 0x05,
	0xb9, 0xff, 0x6b, 0x4b, 0x15, 0xdb, 0xb2, 0x88, 0x6d, 0xf1, 0x02, 0x37, 0xbb, 0x61, 0xcc, 0x19,
	0xbb, 0x57, 0x32, 0xde, 0x59, 0x13, 0x93, 0x6c, 0x0b, 0x57, 0xf5, 0x30, 0x6a, 0xcb, 0xd8, 0x69,
	0x4b, 0x8c, 0xc4, 0x9b, 0xc5, 0xdd, 0xe2, 0xfe, 0xbc, 0xb8, 0xac, 0xe7, 0x7e, 0x3e, 0x3d, 0x8a,
	0x47, 0x58, 0x47, 0x81, 0x72, 0x2d, 0xbe, 0x39, 0x4b, 0x21, 0x29, 0xd6, 0xb0, 0x9a, 0x71, 0x13,
	0xd1, 0xe5, 0x69, 0xcc, 0x8d, 0x50, 0x70, 0x5b, 0x22, 0x99, 0x77, 0xfa, 0xf4, 0x63, 0xcf, 0x68,
	0x4a, 0xdb, 0x50, 0xc5, 0x83, 0xc7, 0x44, 0x3e, 0xc0, 0x35, 0xa6, 0x50, 0x87, 0x94, 0x4e, 0x96,
	0x8b, 0x22, 0xc3, 0x7f, 0x9c, 0x90, 0x90, 0x1d, 0xa8, 0x25, 0x77, 0x24, 0xc5, 0xfe, 0x39, 0x69,
	0x36, 0xb0, 0xea, 0x30, 0x84, 0xaa, 0xc1, 0xf8, 0x81, 0x34, 0xee, 0xce, 0x3e, 0x96, 0xd3, 0x9e,
	0x42, 0x3d, 0x9f, 0x4f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x5a, 0xfe, 0x4b, 0x55, 0x01,
	0x00, 0x00,
}
