// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Breed int32

const (
	Breed_HALP         Breed = 0
	Breed_PERSIAN      Breed = 1
	Breed_BENGAL       Breed = 2
	Breed_RUSSIAN_BLUE Breed = 3
	Breed_CORNISH_REX  Breed = 4
)

var Breed_name = map[int32]string{
	0: "HALP",
	1: "PERSIAN",
	2: "BENGAL",
	3: "RUSSIAN_BLUE",
	4: "CORNISH_REX",
}
var Breed_value = map[string]int32{
	"HALP":         0,
	"PERSIAN":      1,
	"BENGAL":       2,
	"RUSSIAN_BLUE": 3,
	"CORNISH_REX":  4,
}

func (x Breed) String() string {
	return proto.EnumName(Breed_name, int32(x))
}
func (Breed) EnumDescriptor() ([]byte, []int) { return fileDescriptor23, []int{0} }

type Kitten struct {
	Name   string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Breed  Breed   `protobuf:"varint,2,opt,name=breed,enum=SUNProtos.Service.Breed" json:"breed,omitempty"`
	Weight float32 `protobuf:"fixed32,3,opt,name=weight" json:"weight,omitempty"`
	Age    int32   `protobuf:"varint,4,opt,name=age" json:"age,omitempty"`
}

func (m *Kitten) Reset()                    { *m = Kitten{} }
func (m *Kitten) String() string            { return proto.CompactTextString(m) }
func (*Kitten) ProtoMessage()               {}
func (*Kitten) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{1} }

func (m *Kitten) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Kitten) GetBreed() Breed {
	if m != nil {
		return m.Breed
	}
	return Breed_HALP
}

func (m *Kitten) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Kitten) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GetKittenRequest struct {
	// Breed of kitten requested. If not given then the server
	// may provide a kitten of any breed.
	Breed Breed `protobuf:"varint,1,opt,name=breed,enum=SUNProtos.Service.Breed" json:"breed,omitempty"`
}

func (m *GetKittenRequest) Reset()                    { *m = GetKittenRequest{} }
func (m *GetKittenRequest) String() string            { return proto.CompactTextString(m) }
func (*GetKittenRequest) ProtoMessage()               {}
func (*GetKittenRequest) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{2} }

func (m *GetKittenRequest) GetBreed() Breed {
	if m != nil {
		return m.Breed
	}
	return Breed_HALP
}

type GetKittenResponse struct {
	Kitten *Kitten `protobuf:"bytes,1,opt,name=kitten" json:"kitten,omitempty"`
}

func (m *GetKittenResponse) Reset()                    { *m = GetKittenResponse{} }
func (m *GetKittenResponse) String() string            { return proto.CompactTextString(m) }
func (*GetKittenResponse) ProtoMessage()               {}
func (*GetKittenResponse) Descriptor() ([]byte, []int) { return fileDescriptor23, []int{3} }

func (m *GetKittenResponse) GetKitten() *Kitten {
	if m != nil {
		return m.Kitten
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthTicket)(nil), "SUNProtos.Service.AuthTicket")
	proto.RegisterType((*Kitten)(nil), "SUNProtos.Service.Kitten")
	proto.RegisterType((*GetKittenRequest)(nil), "SUNProtos.Service.GetKittenRequest")
	proto.RegisterType((*GetKittenResponse)(nil), "SUNProtos.Service.GetKittenResponse")
	proto.RegisterEnum("SUNProtos.Service.Breed", Breed_name, Breed_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for PetShop service

type PetShopClient interface {
	// Supplies one kitten to the caller.
	GetKitten(ctx context.Context, in *GetKittenRequest, opts ...grpc.CallOption) (*GetKittenResponse, error)
}

type petShopClient struct {
	cc *grpc.ClientConn
}

func NewPetShopClient(cc *grpc.ClientConn) PetShopClient {
	return &petShopClient{cc}
}

func (c *petShopClient) GetKitten(ctx context.Context, in *GetKittenRequest, opts ...grpc.CallOption) (*GetKittenResponse, error) {
	out := new(GetKittenResponse)
	err := grpc.Invoke(ctx, "/SUNProtos.Service.PetShop/GetKitten", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PetShop service

type PetShopServer interface {
	// Supplies one kitten to the caller.
	GetKitten(context.Context, *GetKittenRequest) (*GetKittenResponse, error)
}

func RegisterPetShopServer(s *grpc.Server, srv PetShopServer) {
	s.RegisterService(&_PetShop_serviceDesc, srv)
}

func _PetShop_GetKitten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKittenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetShopServer).GetKitten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SUNProtos.Service.PetShop/GetKitten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetShopServer).GetKitten(ctx, req.(*GetKittenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PetShop_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SUNProtos.Service.PetShop",
	HandlerType: (*PetShopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKitten",
			Handler:    _PetShop_GetKitten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor23) }

var fileDescriptor23 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0x8f, 0xd2, 0x40,
	0x14, 0xc5, 0x2d, 0xb4, 0x05, 0x2e, 0xa8, 0xc3, 0xd5, 0x98, 0xea, 0x13, 0xa9, 0x3e, 0x10, 0x1f,
	0x9a, 0x88, 0x9f, 0xa0, 0x35, 0x15, 0x88, 0x50, 0x9b, 0x29, 0x18, 0xe3, 0x4b, 0x53, 0xe0, 0x06,
	0x1a, 0xd2, 0x3f, 0x76, 0x06, 0xf4, 0xe3, 0x9b, 0x4e, 0x71, 0x77, 0xb3, 0x4b, 0x36, 0xfb, 0x34,
	0xe7, 0xce, 0xb9, 0x73, 0x7e, 0x77, 0x26, 0x03, 0xcf, 0x05, 0x55, 0xe7, 0x74, 0x4b, 0x4e, 0x59,
	0x15, 0xb2, 0xc0, 0x61, 0xb4, 0x0e, 0xc2, 0x5a, 0x09, 0x27, 0x6a, 0x0c, 0x7b, 0x07, 0xe0, 0x9e,
	0xe4, 0x61, 0x95, 0x6e, 0x8f, 0x24, 0xf1, 0x35, 0x18, 0x42, 0x26, 0x95, 0xb4, 0xb4, 0x91, 0x36,
	0x1e, 0xf0, 0xa6, 0x40, 0x07, 0x5e, 0xd1, 0xdf, 0x32, 0xad, 0x28, 0x96, 0x69, 0x46, 0x42, 0x26,
	0x59, 0x19, 0x67, 0xc2, 0x6a, 0x8d, 0xb4, 0xb1, 0xce, 0x87, 0x8d, 0xb5, 0xfa, 0xef, 0x2c, 0x05,
	0x32, 0x68, 0x53, 0xbe, 0xb3, 0xda, 0x2a, 0xa3, 0x96, 0xf6, 0x19, 0xcc, 0x6f, 0xa9, 0x94, 0x94,
	0x23, 0x82, 0x9e, 0x27, 0x19, 0x29, 0x40, 0x8f, 0x2b, 0x8d, 0x0e, 0x18, 0x9b, 0x8a, 0x68, 0xa7,
	0x12, 0x5f, 0x4c, 0x2c, 0xe7, 0xc1, 0x98, 0x8e, 0x57, 0xfb, 0xbc, 0x69, 0xc3, 0x37, 0x60, 0xfe,
	0xa1, 0x74, 0x7f, 0x90, 0x0a, 0xd1, 0xe2, 0x97, 0xaa, 0xe6, 0x26, 0x7b, 0xb2, 0xf4, 0x91, 0x36,
	0x36, 0x78, 0x2d, 0x6d, 0x0f, 0xd8, 0x94, 0x64, 0x83, 0xe6, 0xf4, 0xfb, 0x44, 0x42, 0xde, 0xd2,
	0xb4, 0x27, 0xd1, 0xec, 0xaf, 0x30, 0xbc, 0x93, 0x21, 0xca, 0x22, 0x17, 0x84, 0x9f, 0xc0, 0x3c,
	0xaa, 0x1d, 0x95, 0xd2, 0x9f, 0xbc, 0xbd, 0x92, 0x72, 0x39, 0x72, 0x69, 0xfc, 0xb8, 0x04, 0x43,
	0xe5, 0x62, 0x17, 0xf4, 0x99, 0xbb, 0x08, 0xd9, 0x33, 0xec, 0x43, 0x27, 0xf4, 0x79, 0x34, 0x77,
	0x03, 0xa6, 0x21, 0x80, 0xe9, 0xf9, 0xc1, 0xd4, 0x5d, 0xb0, 0x16, 0x32, 0x18, 0xf0, 0x75, 0x54,
	0x1b, 0xb1, 0xb7, 0x58, 0xfb, 0xac, 0x8d, 0x2f, 0xa1, 0xff, 0xe5, 0x3b, 0x0f, 0xe6, 0xd1, 0x2c,
	0xe6, 0xfe, 0x4f, 0xa6, 0x4f, 0x12, 0xe8, 0x84, 0x24, 0xa3, 0x43, 0x51, 0xe2, 0x0f, 0xe8, 0xdd,
	0x4c, 0x88, 0xef, 0xaf, 0x4c, 0x72, 0xff, 0x0d, 0xde, 0x7d, 0x78, 0xbc, 0xa9, 0xb9, 0xa4, 0xd7,
	0xfd, 0x65, 0xaa, 0x7f, 0x23, 0x36, 0xcd, 0xfa, 0xf9, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25,
	0x5a, 0xe6, 0x43, 0x50, 0x02, 0x00, 0x00,
}
