// Code generated by protoc-gen-go.
// source: settings_master_pokemon.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of NotificationState from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

type CameraAttributes struct {
	DiskRadiusM       float32 `protobuf:"fixed32,1,opt,name=disk_radius_m,json=diskRadiusM" json:"disk_radius_m,omitempty"`
	CylinderRadiusM   float32 `protobuf:"fixed32,2,opt,name=cylinder_radius_m,json=cylinderRadiusM" json:"cylinder_radius_m,omitempty"`
	CylinderHeightM   float32 `protobuf:"fixed32,3,opt,name=cylinder_height_m,json=cylinderHeightM" json:"cylinder_height_m,omitempty"`
	CylinderGroundM   float32 `protobuf:"fixed32,4,opt,name=cylinder_ground_m,json=cylinderGroundM" json:"cylinder_ground_m,omitempty"`
	ShoulderModeScale float32 `protobuf:"fixed32,5,opt,name=shoulder_mode_scale,json=shoulderModeScale" json:"shoulder_mode_scale,omitempty"`
}

func (m *CameraAttributes) Reset()                    { *m = CameraAttributes{} }
func (m *CameraAttributes) String() string            { return proto.CompactTextString(m) }
func (*CameraAttributes) ProtoMessage()               {}
func (*CameraAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{0} }

func (m *CameraAttributes) GetDiskRadiusM() float32 {
	if m != nil {
		return m.DiskRadiusM
	}
	return 0
}

func (m *CameraAttributes) GetCylinderRadiusM() float32 {
	if m != nil {
		return m.CylinderRadiusM
	}
	return 0
}

func (m *CameraAttributes) GetCylinderHeightM() float32 {
	if m != nil {
		return m.CylinderHeightM
	}
	return 0
}

func (m *CameraAttributes) GetCylinderGroundM() float32 {
	if m != nil {
		return m.CylinderGroundM
	}
	return 0
}

func (m *CameraAttributes) GetShoulderModeScale() float32 {
	if m != nil {
		return m.ShoulderModeScale
	}
	return 0
}

type EncounterAttributes struct {
	BaseCaptureRate            float32             `protobuf:"fixed32,1,opt,name=base_capture_rate,json=baseCaptureRate" json:"base_capture_rate,omitempty"`
	BaseFleeRate               float32             `protobuf:"fixed32,2,opt,name=base_flee_rate,json=baseFleeRate" json:"base_flee_rate,omitempty"`
	CollisionRadiusM           float32             `protobuf:"fixed32,3,opt,name=collision_radius_m,json=collisionRadiusM" json:"collision_radius_m,omitempty"`
	CollisionHeightM           float32             `protobuf:"fixed32,4,opt,name=collision_height_m,json=collisionHeightM" json:"collision_height_m,omitempty"`
	CollisionHeadRadiusM       float32             `protobuf:"fixed32,5,opt,name=collision_head_radius_m,json=collisionHeadRadiusM" json:"collision_head_radius_m,omitempty"`
	MovementType               PokemonMovementType `protobuf:"varint,6,opt,name=movement_type,json=movementType,enum=SUNProtos.Enums.PokemonMovementType" json:"movement_type,omitempty"`
	MovementTimerS             float32             `protobuf:"fixed32,7,opt,name=movement_timer_s,json=movementTimerS" json:"movement_timer_s,omitempty"`
	JumpTimeS                  float32             `protobuf:"fixed32,8,opt,name=jump_time_s,json=jumpTimeS" json:"jump_time_s,omitempty"`
	AttackTimerS               float32             `protobuf:"fixed32,9,opt,name=attack_timer_s,json=attackTimerS" json:"attack_timer_s,omitempty"`
	BonusCandyCaptureReward    int32               `protobuf:"varint,10,opt,name=bonus_candy_capture_reward,json=bonusCandyCaptureReward" json:"bonus_candy_capture_reward,omitempty"`
	BonusStardustCaptureReward int32               `protobuf:"varint,11,opt,name=bonus_stardust_capture_reward,json=bonusStardustCaptureReward" json:"bonus_stardust_capture_reward,omitempty"`
	AttackProbability          float32             `protobuf:"fixed32,12,opt,name=attack_probability,json=attackProbability" json:"attack_probability,omitempty"`
	DodgeProbability           float32             `protobuf:"fixed32,13,opt,name=dodge_probability,json=dodgeProbability" json:"dodge_probability,omitempty"`
	DodgeDurationS             float32             `protobuf:"fixed32,14,opt,name=dodge_duration_s,json=dodgeDurationS" json:"dodge_duration_s,omitempty"`
	DodgeDistance              float32             `protobuf:"fixed32,15,opt,name=dodge_distance,json=dodgeDistance" json:"dodge_distance,omitempty"`
	CameraDistance             float32             `protobuf:"fixed32,16,opt,name=camera_distance,json=cameraDistance" json:"camera_distance,omitempty"`
	MinPokemonActionFrequencyS float32             `protobuf:"fixed32,17,opt,name=min_pokemon_action_frequency_s,json=minPokemonActionFrequencyS" json:"min_pokemon_action_frequency_s,omitempty"`
	MaxPokemonActionFrequencyS float32             `protobuf:"fixed32,18,opt,name=max_pokemon_action_frequency_s,json=maxPokemonActionFrequencyS" json:"max_pokemon_action_frequency_s,omitempty"`
}

func (m *EncounterAttributes) Reset()                    { *m = EncounterAttributes{} }
func (m *EncounterAttributes) String() string            { return proto.CompactTextString(m) }
func (*EncounterAttributes) ProtoMessage()               {}
func (*EncounterAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{1} }

func (m *EncounterAttributes) GetBaseCaptureRate() float32 {
	if m != nil {
		return m.BaseCaptureRate
	}
	return 0
}

func (m *EncounterAttributes) GetBaseFleeRate() float32 {
	if m != nil {
		return m.BaseFleeRate
	}
	return 0
}

func (m *EncounterAttributes) GetCollisionRadiusM() float32 {
	if m != nil {
		return m.CollisionRadiusM
	}
	return 0
}

func (m *EncounterAttributes) GetCollisionHeightM() float32 {
	if m != nil {
		return m.CollisionHeightM
	}
	return 0
}

func (m *EncounterAttributes) GetCollisionHeadRadiusM() float32 {
	if m != nil {
		return m.CollisionHeadRadiusM
	}
	return 0
}

func (m *EncounterAttributes) GetMovementType() PokemonMovementType {
	if m != nil {
		return m.MovementType
	}
	return PokemonMovementType_MOVEMENT_STATIC
}

func (m *EncounterAttributes) GetMovementTimerS() float32 {
	if m != nil {
		return m.MovementTimerS
	}
	return 0
}

func (m *EncounterAttributes) GetJumpTimeS() float32 {
	if m != nil {
		return m.JumpTimeS
	}
	return 0
}

func (m *EncounterAttributes) GetAttackTimerS() float32 {
	if m != nil {
		return m.AttackTimerS
	}
	return 0
}

func (m *EncounterAttributes) GetBonusCandyCaptureReward() int32 {
	if m != nil {
		return m.BonusCandyCaptureReward
	}
	return 0
}

func (m *EncounterAttributes) GetBonusStardustCaptureReward() int32 {
	if m != nil {
		return m.BonusStardustCaptureReward
	}
	return 0
}

func (m *EncounterAttributes) GetAttackProbability() float32 {
	if m != nil {
		return m.AttackProbability
	}
	return 0
}

func (m *EncounterAttributes) GetDodgeProbability() float32 {
	if m != nil {
		return m.DodgeProbability
	}
	return 0
}

func (m *EncounterAttributes) GetDodgeDurationS() float32 {
	if m != nil {
		return m.DodgeDurationS
	}
	return 0
}

func (m *EncounterAttributes) GetDodgeDistance() float32 {
	if m != nil {
		return m.DodgeDistance
	}
	return 0
}

func (m *EncounterAttributes) GetCameraDistance() float32 {
	if m != nil {
		return m.CameraDistance
	}
	return 0
}

func (m *EncounterAttributes) GetMinPokemonActionFrequencyS() float32 {
	if m != nil {
		return m.MinPokemonActionFrequencyS
	}
	return 0
}

func (m *EncounterAttributes) GetMaxPokemonActionFrequencyS() float32 {
	if m != nil {
		return m.MaxPokemonActionFrequencyS
	}
	return 0
}

type EvolutionBranch struct {
	Evolution                PokemonId `protobuf:"varint,1,opt,name=evolution,enum=SUNProtos.Enums.PokemonId" json:"evolution,omitempty"`
	EvolutionItemRequirement ItemId    `protobuf:"varint,2,opt,name=evolution_item_requirement,json=evolutionItemRequirement,enum=SUNProtos.Inventory.Item.ItemId" json:"evolution_item_requirement,omitempty"`
	CandyCost                int32     `protobuf:"varint,3,opt,name=candy_cost,json=candyCost" json:"candy_cost,omitempty"`
}

func (m *EvolutionBranch) Reset()                    { *m = EvolutionBranch{} }
func (m *EvolutionBranch) String() string            { return proto.CompactTextString(m) }
func (*EvolutionBranch) ProtoMessage()               {}
func (*EvolutionBranch) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{2} }

func (m *EvolutionBranch) GetEvolution() PokemonId {
	if m != nil {
		return m.Evolution
	}
	return PokemonId_MISSINGNO
}

func (m *EvolutionBranch) GetEvolutionItemRequirement() ItemId {
	if m != nil {
		return m.EvolutionItemRequirement
	}
	return ItemId_ITEM_UNKNOWN
}

func (m *EvolutionBranch) GetCandyCost() int32 {
	if m != nil {
		return m.CandyCost
	}
	return 0
}

type PokemonGenderSettings struct {
	MalePercent       float32 `protobuf:"fixed32,1,opt,name=male_percent,json=malePercent" json:"male_percent,omitempty"`
	FemalePercent     float32 `protobuf:"fixed32,2,opt,name=female_percent,json=femalePercent" json:"female_percent,omitempty"`
	GenderlessPercent float32 `protobuf:"fixed32,3,opt,name=genderless_percent,json=genderlessPercent" json:"genderless_percent,omitempty"`
}

func (m *PokemonGenderSettings) Reset()                    { *m = PokemonGenderSettings{} }
func (m *PokemonGenderSettings) String() string            { return proto.CompactTextString(m) }
func (*PokemonGenderSettings) ProtoMessage()               {}
func (*PokemonGenderSettings) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{3} }

func (m *PokemonGenderSettings) GetMalePercent() float32 {
	if m != nil {
		return m.MalePercent
	}
	return 0
}

func (m *PokemonGenderSettings) GetFemalePercent() float32 {
	if m != nil {
		return m.FemalePercent
	}
	return 0
}

func (m *PokemonGenderSettings) GetGenderlessPercent() float32 {
	if m != nil {
		return m.GenderlessPercent
	}
	return 0
}

type StatsAttributes struct {
	BaseStamina      int32 `protobuf:"varint,1,opt,name=base_stamina,json=baseStamina" json:"base_stamina,omitempty"`
	BaseAttack       int32 `protobuf:"varint,2,opt,name=base_attack,json=baseAttack" json:"base_attack,omitempty"`
	BaseDefense      int32 `protobuf:"varint,3,opt,name=base_defense,json=baseDefense" json:"base_defense,omitempty"`
	DodgeEnergyDelta int32 `protobuf:"varint,8,opt,name=dodge_energy_delta,json=dodgeEnergyDelta" json:"dodge_energy_delta,omitempty"`
}

func (m *StatsAttributes) Reset()                    { *m = StatsAttributes{} }
func (m *StatsAttributes) String() string            { return proto.CompactTextString(m) }
func (*StatsAttributes) ProtoMessage()               {}
func (*StatsAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{4} }

func (m *StatsAttributes) GetBaseStamina() int32 {
	if m != nil {
		return m.BaseStamina
	}
	return 0
}

func (m *StatsAttributes) GetBaseAttack() int32 {
	if m != nil {
		return m.BaseAttack
	}
	return 0
}

func (m *StatsAttributes) GetBaseDefense() int32 {
	if m != nil {
		return m.BaseDefense
	}
	return 0
}

func (m *StatsAttributes) GetDodgeEnergyDelta() int32 {
	if m != nil {
		return m.DodgeEnergyDelta
	}
	return 0
}

func init() {
	proto.RegisterType((*CameraAttributes)(nil), "SUNProtos.Settings.Master.Pokemon.CameraAttributes")
	proto.RegisterType((*EncounterAttributes)(nil), "SUNProtos.Settings.Master.Pokemon.EncounterAttributes")
	proto.RegisterType((*EvolutionBranch)(nil), "SUNProtos.Settings.Master.Pokemon.EvolutionBranch")
	proto.RegisterType((*PokemonGenderSettings)(nil), "SUNProtos.Settings.Master.Pokemon.PokemonGenderSettings")
	proto.RegisterType((*StatsAttributes)(nil), "SUNProtos.Settings.Master.Pokemon.StatsAttributes")
}

func init() { proto.RegisterFile("settings_master_pokemon.proto", fileDescriptor27) }

var fileDescriptor27 = []byte{
	// 856 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x95, 0xdf, 0x8e, 0x1b, 0x35,
	0x14, 0xc6, 0x49, 0x69, 0xda, 0xae, 0xb3, 0x49, 0x36, 0x6e, 0x51, 0x47, 0x91, 0xb6, 0xec, 0x46,
	0x45, 0x44, 0x85, 0xe6, 0x62, 0x11, 0x12, 0x12, 0x57, 0xfb, 0xaf, 0x25, 0x17, 0x41, 0xd1, 0x0c,
	0xdc, 0x70, 0x81, 0xe5, 0xcc, 0x9c, 0xcd, 0x9a, 0x1d, 0xdb, 0xc1, 0xf6, 0x2c, 0xcd, 0x5b, 0x20,
	0xf1, 0x0e, 0x3c, 0x0c, 0x8f, 0xc2, 0x53, 0x20, 0x1f, 0x7b, 0x66, 0x92, 0x8a, 0xf6, 0x26, 0x1a,
	0x7f, 0xe7, 0xe7, 0xcf, 0xf6, 0xf1, 0xf1, 0x09, 0x39, 0xb6, 0xe0, 0x9c, 0x50, 0x6b, 0xcb, 0x24,
	0xb7, 0x0e, 0x0c, 0xdb, 0xe8, 0x3b, 0x90, 0x5a, 0xcd, 0x36, 0x46, 0x3b, 0x4d, 0x4f, 0xb3, 0x9f,
	0x7f, 0x5c, 0xfa, 0x2f, 0x3b, 0xcb, 0x22, 0x38, 0x5b, 0x20, 0x38, 0x5b, 0x06, 0x70, 0xdc, 0x03,
	0x55, 0x49, 0x1b, 0xf8, 0xf1, 0x33, 0xa1, 0xee, 0x41, 0x39, 0x6d, 0xb6, 0x4c, 0x38, 0x90, 0x41,
	0x9d, 0xfc, 0xdb, 0x21, 0x47, 0x97, 0x5c, 0x82, 0xe1, 0xe7, 0xce, 0x19, 0xb1, 0xaa, 0x1c, 0x58,
	0x3a, 0x21, 0xfd, 0x42, 0xd8, 0x3b, 0x66, 0x78, 0x21, 0x2a, 0xcb, 0x64, 0xd2, 0x39, 0xe9, 0x4c,
	0x1f, 0xa4, 0x3d, 0x2f, 0xa6, 0xa8, 0x2d, 0xe8, 0x2b, 0x32, 0xca, 0xb7, 0xa5, 0x50, 0x05, 0x98,
	0x96, 0x7b, 0x80, 0xdc, 0xb0, 0x0e, 0xfc, 0x1f, 0x7b, 0x0b, 0x62, 0x7d, 0xeb, 0x98, 0x4c, 0x3e,
	0xdd, 0x67, 0x7f, 0x40, 0x7d, 0x9f, 0x5d, 0x1b, 0x5d, 0xa9, 0x82, 0xc9, 0xe4, 0xe1, 0x3e, 0xfb,
	0x16, 0xf5, 0x05, 0x9d, 0x91, 0xa7, 0xf6, 0x56, 0x57, 0xa5, 0x67, 0xa5, 0x2e, 0x80, 0xd9, 0x9c,
	0x97, 0x90, 0x74, 0x91, 0x1e, 0xd5, 0xa1, 0x85, 0x2e, 0x20, 0xf3, 0x81, 0xc9, 0x5f, 0x8f, 0xc9,
	0xd3, 0x6b, 0x95, 0xeb, 0x4a, 0x39, 0x30, 0x3b, 0xe7, 0x7d, 0x45, 0x46, 0x2b, 0x6e, 0x81, 0xe5,
	0x7c, 0xe3, 0x2a, 0x03, 0xcc, 0x70, 0x07, 0xf1, 0xcc, 0x43, 0x1f, 0xb8, 0x0c, 0x7a, 0xca, 0x1d,
	0xd0, 0x97, 0x64, 0x80, 0xec, 0x4d, 0x09, 0x11, 0x0c, 0x87, 0x3e, 0xf4, 0xea, 0x9b, 0x12, 0x02,
	0xf5, 0x35, 0xa1, 0xb9, 0x2e, 0x4b, 0x61, 0x85, 0x56, 0x6d, 0x7a, 0xc2, 0x91, 0x8f, 0x9a, 0x48,
	0x9d, 0x9f, 0x3d, 0xba, 0x49, 0xd0, 0xc3, 0xf7, 0xe8, 0x3a, 0x43, 0xdf, 0x92, 0xe7, 0xbb, 0x34,
	0x2f, 0xda, 0x05, 0xc2, 0xc9, 0x9f, 0xed, 0x4c, 0xe1, 0x45, 0xbd, 0xc8, 0x9c, 0xf4, 0xa5, 0xbe,
	0x07, 0x09, 0xca, 0x31, 0xb7, 0xdd, 0x40, 0xf2, 0xe8, 0xa4, 0x33, 0x1d, 0x9c, 0xbd, 0x9c, 0xb5,
	0x75, 0x74, 0x8d, 0xe5, 0x12, 0xab, 0x67, 0x11, 0xe1, 0x9f, 0xb6, 0x1b, 0x48, 0x0f, 0xe5, 0xce,
	0x88, 0x4e, 0xc9, 0x51, 0x6b, 0x25, 0x24, 0x18, 0x66, 0x93, 0xc7, 0xb8, 0xf4, 0xa0, 0xe1, 0xbc,
	0x9c, 0xd1, 0x17, 0xa4, 0xf7, 0x5b, 0x25, 0x37, 0x48, 0x31, 0x9b, 0x3c, 0x41, 0xe8, 0xc0, 0x4b,
	0x1e, 0xc8, 0x7c, 0x36, 0xb9, 0x73, 0x3c, 0xbf, 0x6b, 0x7c, 0x0e, 0x42, 0x36, 0x83, 0x1a, 0x5d,
	0xbe, 0x27, 0xe3, 0x95, 0x56, 0x95, 0x65, 0x39, 0x57, 0xc5, 0xb6, 0xbd, 0x26, 0xf8, 0x83, 0x9b,
	0x22, 0x21, 0x27, 0x9d, 0x69, 0x37, 0x7d, 0x8e, 0xc4, 0xa5, 0x07, 0xea, 0xeb, 0xc2, 0x30, 0x3d,
	0x27, 0xc7, 0x61, 0xb2, 0x75, 0xdc, 0x14, 0x95, 0x75, 0xef, 0xcf, 0xef, 0xe1, 0xfc, 0xb0, 0x42,
	0x16, 0x99, 0x7d, 0x8b, 0xd7, 0x84, 0xc6, 0x5d, 0x6e, 0x8c, 0x5e, 0xf1, 0x95, 0x28, 0x85, 0xdb,
	0x26, 0x87, 0xa1, 0xcc, 0x42, 0x64, 0xd9, 0x06, 0xe8, 0x57, 0x64, 0x54, 0xe8, 0x62, 0x0d, 0x7b,
	0x74, 0x3f, 0xdc, 0x26, 0x06, 0x76, 0xe1, 0x29, 0x09, 0x1a, 0x2b, 0x2a, 0xc3, 0x9d, 0xbf, 0x52,
	0x9b, 0x0c, 0x42, 0x2e, 0x51, 0xbf, 0x8a, 0x72, 0x46, 0xbf, 0x20, 0x83, 0x48, 0x0a, 0xeb, 0xb8,
	0xca, 0x21, 0x19, 0x22, 0xd7, 0x0f, 0x5c, 0x14, 0xe9, 0x97, 0x64, 0x98, 0xe3, 0x83, 0x6e, 0xb9,
	0xa3, 0xe0, 0x17, 0xe4, 0x06, 0xbc, 0x20, 0x2f, 0xa4, 0x50, 0x75, 0x57, 0x61, 0x3c, 0xc7, 0xd5,
	0x6f, 0x0c, 0xfc, 0x5e, 0x81, 0xca, 0xb7, 0xcc, 0x26, 0x23, 0x9c, 0x37, 0x96, 0x42, 0xc5, 0x9a,
	0x38, 0x47, 0xe6, 0x4d, 0x8d, 0x64, 0xe8, 0xc1, 0xdf, 0x7d, 0xcc, 0x83, 0x46, 0x0f, 0xfe, 0xee,
	0x03, 0x1e, 0x93, 0x7f, 0x3a, 0x64, 0x78, 0x7d, 0xaf, 0xcb, 0xca, 0xeb, 0x17, 0x86, 0xab, 0xfc,
	0x96, 0x7e, 0x47, 0x0e, 0xa0, 0x96, 0xf0, 0x25, 0x0e, 0xce, 0xc6, 0x1f, 0x2a, 0xd4, 0x79, 0x91,
	0xb6, 0x30, 0xfd, 0x95, 0x8c, 0x9b, 0x01, 0x36, 0x3a, 0xe6, 0x57, 0x12, 0x06, 0xab, 0x12, 0xdf,
	0xea, 0xe0, 0xec, 0x64, 0xc7, 0x6a, 0x5e, 0x77, 0xc5, 0xd9, 0xdc, 0x77, 0x45, 0xff, 0x33, 0x2f,
	0xd2, 0xa4, 0xf1, 0xf0, 0x42, 0xda, 0x3a, 0xd0, 0x63, 0x42, 0x62, 0x15, 0x6a, 0xeb, 0xf0, 0x45,
	0x77, 0xd3, 0x03, 0x54, 0x2e, 0xb5, 0x75, 0x93, 0x3f, 0x3b, 0xe4, 0xb3, 0xb8, 0xaf, 0xb7, 0xe0,
	0x7b, 0x55, 0xdd, 0x9b, 0xe9, 0x29, 0x39, 0x94, 0xbc, 0x04, 0xb6, 0x01, 0x93, 0xfb, 0xad, 0xc4,
	0x9e, 0xea, 0xb5, 0x65, 0x90, 0xfc, 0x0d, 0xdf, 0xc0, 0x1e, 0x14, 0x7a, 0x4b, 0x3f, 0xa8, 0x35,
	0xf6, 0x9a, 0xd0, 0x35, 0x7a, 0x97, 0x60, 0x6d, 0x83, 0x86, 0xe6, 0x32, 0x6a, 0x23, 0x11, 0x9f,
	0xfc, 0xdd, 0x21, 0xc3, 0xcc, 0x71, 0x67, 0x77, 0x3a, 0xde, 0x29, 0xc1, 0x7e, 0xe5, 0xdf, 0x84,
	0x14, 0x8a, 0xe3, 0x66, 0xba, 0x69, 0xcf, 0x6b, 0x59, 0x90, 0xe8, 0xe7, 0x04, 0x87, 0x2c, 0xd4,
	0x37, 0xee, 0xa4, 0x9b, 0x12, 0x2f, 0x9d, 0xa3, 0xd2, 0x78, 0x14, 0x70, 0x03, 0xca, 0x42, 0xcc,
	0x05, 0x4e, 0xba, 0x0a, 0x92, 0x6f, 0x6c, 0xa1, 0x64, 0x41, 0x81, 0x59, 0x6f, 0x59, 0x01, 0xa5,
	0xe3, 0xd8, 0x05, 0xba, 0xf1, 0x29, 0x5c, 0x63, 0xe0, 0xca, 0xeb, 0x17, 0x4f, 0x7e, 0x79, 0x84,
	0x7f, 0x4a, 0x76, 0xf9, 0xc9, 0xb2, 0xb3, 0x0a, 0xdf, 0xdf, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x45, 0x96, 0x4a, 0x62, 0x07, 0x07, 0x00, 0x00,
}
