go_library(
    name = 'kitten2',
    srcs = ['kitten2.pb.go'],
    deps = [
        '//third_party/go:grpc',
        '//third_party/go:protobuf',
        '//third_party/go:protoc-gen-go',
    ],
    visibility = ['PUBLIC',],
)
